/* Isbell adjunction, visual interpretation of localisation in commutative algerbra:  one can do localising via Isbell adjunction. Localisation can be seen as a restriction to the complement of subspace Y included into X such that elements of multiplicative subset S vanish when you localise at S. This looks like zooming in onto the space, but only seeing the surroundings. So you only see what is nearby in neighbourhood but not what the object is, compare this quotient where you see what is inside the thing, everything else vanish. In commutative algebra side, it means the relation is equal and made zero, in geometry it means what you see is left because that is the curve = 0. This motivates the name localisation. */
/* Ring, two operations:  a ring can viewed as a commutative group under addition, and a monoid under multiplication. */
/* Ring, number system:  the basic example of a ring is the integers. In fact, the ring is the initial object in the category of commutative rings. This means I can represent every other ring by a ring homomorphism that forgets certain properties of the ring. The prime spectrum of the ring of integers, Spec Z, is therefore the final object in the category of (affine) varieties (or for more general constructs). This means when I draw a picture of a scheme, I can forget parts of the scheme to get back Spec Z. */
/* Ring, function space:   a ring can be viewed as a set of functions from a space to a field, addition and multiplication are defined pointwise. This is the ontology required for polynomial rings. Recall that polynomials are raised to integer powers. */
/* Ring, linear operator algebra:  Consider linear operators acting on a vector space or a module. Addition is the sum of operators, multiplication is composition of operators. */
/* Ring, closure axiom:  one of the nice properties inherited from the ring of integers is the closure property. When one add, subtract, or multiply elements of the ring, then it will still be a ring element. This is the closure property of rings. */
/* Ring, division free domain:  Start with a field, remove requirement for multiplicative inverses */
/* Ring, scalars on modules:  Ring elements act as scalars on modules, generalising vector spaces */
/* Ring, contains ideals:  Rings contain ideals that capture the essence of divisibilities and factor rings or quotient rings. In fact, from the perspective of algebraic number theory, one can take integral closure to obtain unique prime factorisation of ideals. */
/* Ring, ring of integers as infinite number lines and Gaussian integers as 2D lattice:  The rings of integers of number fields are higher-dimensional generalizations, like a 2D lattice for the Gaussian integers, which still retain the essential arithmetic structure of addition and multiplication. */
/* Ring, enabling zero divisors:  Rings allow product to be zero. This leads to nonunique factorisation. This is associated with the characteristic of th ering. */
/* Rings, integer characteristic:  Number of times to add multiplicative identity to itself to get additive identity. Example in Z_2, 1 + 1 = 0. */
/* Ring, geometric point: a ring may be designed to be a locally ringed space with nformation associated with a point in geometric space */
/* Ring, as a group object:  Group object in the monoidal category of abelian groups */
/* Ring, endomorphism ring:  a ring can be viewed as a set of endomorphisms (structure preserving maps) of an abelian group, addition is pointwise sum of maps, multiplication is their composition */
/* Finite module, chain condition:  the ascending chain condition on submodules satisified if the ring is Noetherian. */
/* Finite module, projective object in category of modules:  a projective object in the category of modules, means suitable lift exists. */
/* Finite module, applications to rings as actions:  finite modules are the multiplication table of a ring, module elements are multiplied by the ring elements */
/* Finite module, vector space:  generalisation of finite dimensional vector spaces. In general, modules are generalisations of finite dimensional vector spaces. Therefore, one can also think of representation theory as maps from groups to modules. */
/* Finite module, homomorphic image of free module:  Homomorphic image of free module of finite rank, "quotient" of free module */
/* Finite module, spanning set:  a finite module has a finite spanning set */
/* Finitely presented module, finite descriptions:  Finite generators, finite relations. Computational. */
/* Finitely presented module, kernel of map:  Kernel of map between two modules of finite rank */
/* Finitely presented module, double finiteness:  Finite generating set, and finite relations. More subtle than finitely generated. */
/* Finitely presented, quotient:  Quotient of finitely generated free module, submodule of relations is also finitely generated */
/* Finitely presented module, vector space with relations:  finitely presented module is a generalization of a finite-dimensional vector space where the "basis vectors" are subject to a finite number of linear relations (over a ring instead of a field). */
/* Finitely presented module, projective:  Over a Noetherian ring, a finitely presented module is a projective module. */
/* Finitely presented module, flatness and projective:  module is finitely presented and flat if and only if it is projective. */
/* Finitely presented module, coherent sheaf:  finitely presented module corresponds to a coherent sheaf */
/* Finitely presented modules, coherent sheaf categories:  category of finitely presented modules is equivalent to the category of coherent sheaves on a ring's spectrum */
/* Ideal, subring with absorption:  Assume two sided, coefficient r in R, a in I, ar in I, ra in I, two sided */
/* Ideal, kernel of homomorphism:  Kernel of ring homomorphism always an ideal of ring R */
/* Ideal, element generator:  Principal ideal, generated by one element, multiples of a in the ring */
/* Ideal, equivalence class partition:  ideal I in ring R define equivalence classes of cosets, forming quotient ring R/I, elements form r + I, mod out an ideal to create new a simpler ring */
/* Ideal, lattice operations:  meet is intersection of ideals, join is their sum */
/* Ideal, primitive element in domain:  Prime ideal, product of two elements in ideal, at least one of its elements must be, generalising prime number */
/* Ideal, maximal, consider case of Z/2 versus Z/4:  Maximal ideal, not properly contained in any ideal, maximal means what can be made into a unit is made into a unit or invertible, largest possible quotient rings aka fields, Z/2 is a field, everything is invertible, (2) has identified all even numbers so elements are {0,1}, Z/4 is not a field, not maximal, {0,1,2,3}, still cannot find inverses for 2b = 1 (mod 4). */
/* Ideal, local geometry:  Prime ideal, irreducible algebraic variety, this forms prime spectrum */
/* Ideal, sheaf stalk:  Ideal is stalk of sheaf of ideals on a topological space */
/* Ideal, encoded by morphisms:  implicitly defined by morphism properties, example kernels of morphisms (ring homomorphisms in category of rings) means morphisms encode ideals */
/* Ideal, filters for ring operation:  Ideals absorb under multiplication, stronger than simple additive subgroup */
/* Ideal, radical:  Radical ideal, raised to some power fall into the ideal. */
/* Ideal, filter in order:  In poset of ideal, maximal ideals are maximal elements */
/* Ideals, representation of module:  Ideal, submodule of a ring, ring as module over itself */
/* Ideal, direct limit:  Direct limit of a system of principal ideals or a colimit. */
/* Ideal, annihilator of a module M: set of all elements of ring R that multiply with every element of module M to produce 0. */
/* Ideal, cokernel:  cokernel of inclusion map I in R is quotient ideal R/I for abelian categories */
/* Ideal, finitely generated:  finitely generated ideal, written as finite sum of principal ideals */
/* Ideal, primary as fuzzy points: A primary ideal is a proper ideal Q such that if a product ab is in Q and a is not in Q, then some power of b is in Q. Visual Intuition: Primary ideals are like "fuzzy points" or "infinitesimal neighborhoods" around a point. The radical of a primary ideal is a prime ideal, which means it is a point with some "fuzzy" information attached to it. */
/* Tensor product, universal bilinear map:  Vector space with bilinear map, factors uniquely through it */
/* Tensor product, free vector space modulo relations:  Take free vector space V * W, mod out subspace generated by relations that enforce bilinearity, distributive law and constants */
/* Tensor product, basis construction:  set of all formal products form basis for tensor product, simple extension of basis so dimension of tensor product is simple product of dimension */
/* Tensor product, representation of multilinear maps:  space of all bilinear maps from dual to underlying field */
/* Tensor product, functor:  bifunctor from category Module to itself, take pair of spaces to tensor product, pair of linear maps to tensor product map */
/* Tensor product, modules over commutative ring:  Replace vector space with module, Cartesian product becomes tensor product */
/* Tensor product, algebras:  use (a ** b)(a' ** b') = aa' ** bb' */
/* Tensor product, adjoint functor:  left adjoint to hom functor, for hom in R as inner product form (U * V, W) = (U, (V, W)) */
/* Tensor product, product in monoidal category:  associative and commutative binary operation defining products in monoidal categories */
/* Tensor product, colimits:  Tensor product of modules, colimit over diagram with bilinearity relations */
/* Tensor product, global section space considering tangent spaces:  Tensor product of tangent spaces at a point, space of tensors at that point */
/* Tensor product, space of sections of product bundle:  Tensor product of two vector bundles over manifold is new vector bundle, fibres are tensor products of the original fibres */
/* Tensor product, operation of coherent sheaf:  Tensor product of coherent sheaf is a coherent sheaf */
/* Tensor product, combine spaces:  Topological tensor product is a topological vector space that is formed from two topological vector spaces */
/* Tensor product, commutative product in cohomology:  cup product turns cohomology group into a graded ring, ring multiplication is tensor product */
/* Tensor product, machine learning:  tensor, multi dim array of number, tensor product, operation for combining these arrays */
/* Tensor product, generalises bilinear forms:  Turns bilinear forms on V cross W into linear maps on V tensor W */
/* Tensor product, two affine lines over the complex numbers, A_C1​=Spec(C[t]) and A_C1​=Spec(C[u]). Their product is the affine plane AC2​=Spec(C[t] tensor_C ​C[u]). This tensor product is isomorphic to C[t,u]. Geometrically, this is a literal multiplication of two lines to form a plane, but the tensor product provides the algebraic machinery for it. It's how we build higher-dimensional spaces from lower-dimensional ones:  The tensor product of two schemes X and Y over a base field k, denoted X ×_k ​Y, is a scheme whose ring of functions is the tensor product of the rings of functions of X and Y. Specifically, for affine schemes Spec(A) and Spec(B), their product is Spec(A tensor_k ​B). This construction allows us to "multiply" geometric objects. */
/* Tensor product, two representations of a group G, say the cyclic group C_2​={e,a} acting on two 1-dimensional vector spaces, V1​ and V2​, over a field of characteristic 2. The action is given by matrices. The tensor product is a new representation on the space V1​⊗V2​ which is 1-dimensional. The matrix for the action of a on the tensor product is the product of the matrices for the action of a on V1​ and V2​. This is a way of "multiplying" the representations, which is a powerful way to understand the structure of the group:  The tensor product of modules is a key operation in modular representation theory. For two modules M and N over a group algebra kG, their tensor product M tensor_k ​N is a new module over kG with the diagonal action g(m tensor n)=gm tensor gn. This construction allows us to build new representations from old ones, and it is a key tool for understanding the structure of representation blocks. */
/* Tensor product, imagine two curves C1​ and C2​ that both project to the same line L. The fiber product C1 ​cross_L ​C2​ is a new curve whose points are pairs of points (p1​,p2​) from C1​ and C2​ that map to the same point on L. This is like a "pullback" of the two curves. For example, if we take two lines that intersect at the origin in the plane, their fiber product over the origin is just the origin itself. This is a very powerful way to capture how two geometric objects relate to a common base:  The fiber product of two schemes X and Y over a base scheme S, denoted X cross_S ​Y, is a scheme that captures the "intersection" or "common parts" of X and Y over the base S. It is a generalization of the tensor product of rings. For affine schemes, Spec(A) and Spec(B) over Spec(C), the fiber product is Spec(A tensor_C ​B). */
/* Tensor product, a line bundle on a manifold, which is a collection of lines attached to each point of the manifold. For example, the tangent bundle of a circle is a line bundle. The tensor product of two line bundles is a new bundle where the line at each point is the tensor product of the two lines. For example, if we take the tangent bundle of a circle and tensor it with itself, we get a new bundle. This is a way of "squaring" a line bundle:  tensor product of line bundles is a key operation. For two line bundles L and M on a scheme X, their tensor product is a new line bundle L tensor {O_X} ​​M. This operation corresponds to multiplying the sections of the line bundles. */
/* Tensor product, the character of a representation is a function on the group that tells us about the trace of the matrices. We can visualize the characters as functions on a graph of the group. The tensor product of two representations corresponds to a new character which is the product of the two original character functions. This is a way of "multiplying" the functions on the group:  the character of a tensor product of representations is the product of the characters of the individual representations. The character X_{V tensor W} ​(g)= X_{V​(g)} X_{W​(g)}. This is a very powerful property that allows us to compute the character of a new representation by simply multiplying the characters of the old ones. */
/* Tensor product, two topological spaces, say two circles. The tensor product of their chain complexes gives us the chain complex of the torus. The homology of the torus is the tensor product of the homologies of the circles. This is a way of "multiplying" the spaces in a homological sense. The tensor product of the chain complexes is a combinatorial object that tells us about the holes of the product space:  The tensor product of chain complexes is a key construction in homotopy theory. It is used to compute the homology of a product of spaces. The Eilenberg-MacLane space K(A,n) has a homology group that is the tensor product of the homology of the space with a module. */
/* Tensor product, two dynamical systems, one on a circle and one on a line. The topological entropy measures how fast the number of orbits grows. The tensor product is a new system on a cylinder. The topological entropy of the cylinder system is the sum of the entropies of the circle and the line. This is a way of "adding" the complexity of two systems:  The topological entropy of a tensor product of dynamical systems is the sum of the topological entropies of the individual systems. This is a measure of the complexity of the combined system. */
/* Tensor product, an elliptic curve over the real numbers. It can have a number of connected components. If we extend the base field to the complex numbers, the curve becomes a torus. This is a change of base. The tensor product of the scheme of the elliptic curve with the scheme of the complex numbers is the new scheme. This is a way of "multiplying" a real object with a complex one:  The tensor product of schemes over different fields is a way to change the base field. For a scheme X over a field k and a field extension L/k, the new scheme is X cross_Spec(k)​ Spec(L). This is a fundamental construction for studying schemes over different fields. */
/* Tensor product, polynomial ring in three variables. We can build a chain complex for it by taking the tensor product of three simple chain complexes, one for each variable. The resulting complex has a nice combinatorial structure. This is a way of "multiplying" the one-variable problems to get a multi-variable one:  The Koszul complex is a chain complex that is a tensor product of simpler complexes. It is a fundamental tool for computing the homology of a module over a polynomial ring. */
/* Tensor product, a collection of indecomposable modules for a group algebra. We can form a new ring where the elements are formal sums of these modules. The multiplication in this ring is the tensor product of the modules. This is a way of turning the category of modules into an algebraic object that we can study with the tools of ring theory:  The Green's ring of a group algebra is a ring whose elements are the isomorphism classes of finitely generated modules. The addition is the direct sum, and the multiplication is the tensor product. */
/* Quotient ring, form of the elements of the cosets of ideal:  for the cosets of the ideal, the elements are of a form a + I */
/* Quotient ring, definition of set via equivalence classes:  set of all equivalence classes under a equivalent to b if and only if a - b is in I where I is an ideal */
/* Quotient ring, partition of ring:  Partition ring into disjoint coset, each coset has a ring structure */
/* Quotient ring, kernel of homomorphism: a quotient ring isomorphic to the image of a ring homomorphism, where the ideal is the kernel of the homomorphism */
/* Quotient ring, modulo ring:  ring modulo an ideal denoted R / I, example Z/2Z, generalising modular arithmetic from integers to any ring */
/* Quotient ring, homomorphic image:  homomorphic image of the canonical projection map from R to R/I */
/* Quotient ring, measure of collapse:  degree which ring collapses when elements ideal are treated as zero */
/* Quotient ring, data structure:  modelled as data structure representing a ring with a zero out property for all elements in the ideal */
/* Quotient ring, construction of field:  field constructed by quotienting ring with maximal ideal */
/* Quotient ring, collapse elements of ideals, example of ideal like a line passing through the origin, quotient ring collapses the plane along this line:  "collapsing" all the elements of an ideal I in a ring R to zero. The elements of the quotient ring are the cosets of the ideal. Visual intuition: Think of a plane (the ring R). An ideal I is a line passing through the origin. The quotient ring R/I is like collapsing the plane along this line, creating a new, smaller space */
/* Quotient ring, kernel as set of things you cannot tell apart:  kernel is the set of elements that are mapped to zero. Visual intuition: The kernel is the "set of things you can't tell apart" after a transformation. */
/* Quotient ring, quotient module is collapsing vector space onto line:  vector space M. A subspace N is a line. The quotient module is like collapsing the vector space along this line. */
/* Isotone Galois connection, adjoint functors:  adjoint functors between two posets */
/* Isotone Galois connection, order preserving maps:  pair of order preserving maps between two posets */
/* Isotone Galois connection, duality of lattices:  establishes poset duality */
/* Isotone Galois connection, special case of categorical adjunction:  categories are ordered sets, so Galois connections are special case of adjunctions */
/* Antitone Galois connections, order reversing duality:  order reversing maps between two ordered sets */
/* Antitone Galois connections, contravariant duality:  contravariant adjunction, reverses direction of inequalities */
/* Antitone Galois connection, generalises annihilators and ideals:  generalises annihilators in linear algebra, and ideal in ring theory */
/* Torsion in commutative algebra, module element annhilation:  module element annhilated by nonzero element */
/* Torsion in commutative algebra, finite order:  all elements of finite order */
/* Torsion, measure of locality:  measures the extent a module is local, nonzero ring element can act as local zero */
/* Torsion, kernel of localisation is field of fractions is torsion submodule:  torsion submodule is the kernel of the natural map from a module to its localization at the zero ideal, which is the field of fractions of the ring. */
/* Torsion, decomposition:  "finite part" of a finitely generated module over a principal ideal domain (PID), as per the Fundamental Theorem of Finitely Generated Modules. */
/* Torsion, dual of torsionfree, definition of torsionfree module:  conceptual dual of a torsion-free module, where every non-zero element of the ring acts injectively */
/* Torsion, collapsed structure:  "collapsed" or "simplified" structure where elements are not unique, but are identified via a non-zero annihilator. */
/* Torsion, homological invariant:  homological invariant captured by the Tor functors, which measure the extent to which tensor products fail to be exact. */
/* Torsion, measure of non-flatness:  how far a module is from being a flat module, a module whose tensor product with other modules preserves exact sequences. */
/* Torsion, injective from annihilated:  boundary phenomenon in a module, where the behavior of its elements changes from "injective" to "annihilated." */
/* Torsion, classification purposes via decomposition:  primary tool for classifying modules over rings, particularly PIDs, by decomposing them into a free part and a torsion part */
/* Projective module, direct summand of free module:  direct sum of projective module and another module forming a free module */
/* Projective module, lifting property:  lifts surjective module homomorphism module M to module N and any homomorphism projective module P to module N using ring homomorphism from projective P to module M. Very similar to direct sum definition. */
/* Projective module, split short exact sequence:  projective if every 0 -> K -> M -> P -> 0, is split exact aka M is isomorphic to direct sum of K and P */
/* Projective module, exactness of Hom functor:  TFAE: (1) projective; (2) Hom(P, - ) is exact. */
/* Projective module, projective resolution:  Projective resolution of length 0, -> P_1 -> P_0 -> M -> 0, all P_i are projective */
/* Projective module, dual basis:  for a projective module, a dual basis exists, linear forms in Hom(P, R) for coefficients x_i in projective module P, ring R. */
/* Projective modules, flat:  All projective modules are flat modules, flat modules preserve injectivity under tensor product */
/* Projective modules, condition via localisation at each prime ideal to get a free R_p module:  TFAE: (1) for each and every prime ideal p in ring R, localised P_p is a free R_p module; (2) P is projective. */
/* Projective module, idempotent endomorphism:  TFAE: (1) P is finitely generated projective module; (2) P is the image of idempotent endomorphism of a free module. Idempotent endomorphism is map p from F to F, such that p^2 = p. */
/* Projective module, 0 Ext group:  TFAE: (1) module projective; (2) Ext^1_R(P, M). Vanishing of first Ext group means it is acyclic in some sense */
/* Projective module, locally free sheaf:  TFAE (1) finitely generated projective module over commutative ring R; (2) locally free sheaf on affine scheme Spec(R) */
/* Projective module, vector bundles:  Projective modules are to free modules (take resolutions of free modules) as vector spaces are to trivial bundles (use many trivial bundles to get vector space, no need to consider global twisting) */
/* Projective module, flat and finitely presented:  For finitely generated modules, being projective is equivalent to being flat (tensor product is exact, resolution of free modules gives flat module) and finitely presented (generators and relations) */
/* Projective module, over local ring and locally free: A projective module over a local ring is always free. */
/* Projective module, unimodular row:  fg projective module of rank 1 is a unimodular row that can be completed to an invertible matrix. */
/* Projective module, monoid:  isomorphism classes of finitely generated modules form a commutative monoid under direct sum, construction of K-group K_0(R) */
/* Projective module, projective cover:  projective cover is minimal surjection of projective module, TFAE: (1) projective module; (2) projective cover of every homomorphic module */
/* Projective module, faithfully flat module can generate entire module category:  TFAE: (1) finitely generated projective module generating entire module category; (2) faithfully flat module */
/* Projective module, torsion free comparison in Dedekind domains:  TFAE: (1) projective over Dedekind domain; (2) torsionfree over Dedekind domain. Show that a module is direct sum of finitely generated free module and fractional ideal, in a Dedekind domain, finitely generated module is isomorphic to direct sum of free module and an ideal. */
/* Projective module, sections of vector bundle like object:  modules whose elements are "sections" of a vector bundle like object */
/* Injective module, categorical dual to projective module:  Reverse arrows in commutative diagram for projective module gives injective module diagram */
/* Injective module, Hom-tensor adjunction:  Contravariant hom functor, so becomes hom-tensor duality */
/* Injective module, cogenerator:  TFAE: (1) module C is injective cogenerator; (2) injective and for all nonzero module M, nonzero homomorphism from M to C */
/* Injective module, Matlis theorem, local structure:  Matlis theorem is for a commutative Noetherian ring, every injective module is uniquely a direct sum of indecomposable injective modules. */
/* Injective module, injective hull of quotient:  every indecomposable injective module over a commutative Noetherian ring R is isomorphic to the injective hull of a module of the form R/p for some prime ideal p of R. This establishes a powerful correspondence between indecomposable injective modules and prime ideals. */
/* Injective module, flabby sheaf:  flabby sheaf, any section over open subset can be extended as a section over the full space. Geometric parallel to homomorphism extension property of injective modules */
/* Injective modules, divisibility has no holes:  divisible module, all elements can be divided by any nonzero ring element, module has no holes that prevent division */
/* Injective module, space of functions:  space of functions with no constraint on domain extension, corresponds to sections over opens becoming sections over the whole space */
/* Injective module, definition via corepresenting object: Q is injective object if corepresenting Hom(-, Q) maps monomorphisms to epimorphisms, formally dual for projective modules */
/* Injective module, direct products:  direct product of any family of injective modules is an injective module. The corresponding property for direct sums holds only for Noetherian rings. */
/* Injective module, no proper essential extensions:  module Q is injective if and only if it has no proper essential extensions. An essential extension of a module M is a module N containing M as a submodule, such that every nonzero submodule of N has a nonzero intersection with M. */
/* Injective module, injective hull of any module:  module M has a minimal injective module containing it, called its injective hull, denoted E(M). A module Q is injective if and only if it is its own injective hull. The injective hull is an essential extension, meaning Q is an essential submodule of E(Q). */
/* Injective module, divisible module:  integral domain R, a module Q is injective if and only if it is divisible. A module M is divisible if for every nonzero element r in R and every m in M, there exists n in M such that rn in m. For example, the rational numbers Q are an injective Z-module. */
/* Injective module, injective resolution: 0 to M to I_0 to I_1, I_i all injective modules */
/* Injective module, splitting of short exact sequence: 0 -> Q -> M -> N -> 0 is split exact, M is isomorphic to direct sum of Q and N, Q is injective module, N is projective module */
/* Injective module, homomorphism extension:  TFAE: (1) Q is injective module; (2) injective if for any submodule A of an R-module B, and any homomorphism f : A to Q, there exists an extension homomorphism g: B to Q such that g restricted to A is homomorphism f. */
/* Flat module, preserves tensor product:  Tensor product functor (- *_R M) is exact */
/* Flat module, preserve monomorphisms:  tensor product is always right exact, a module M is flat if and only if for every injective module homomorphism ϕ: A into B, the induced map ϕ ** 1_M​ : A **_R ​M to B **_R ​M is also injective. This means that tensoring with a flat module doesn't "collapse" submodules. */
/* Flat module, condition for a flat module to not have torsion:  for a module over an integral domain (product of nonzero is nonzero), flat means torsionfree */
/* Flat module, acyclic Tor functor:  TFAE: (1) flat module; (2) Tor_1^R(N, M) = 0 for all modules N. */
/* Flat module, direct limit of free module:  direct limit of finitely generated free module */
/* Flat module, locally free:  localisation every prime ideal is free module over the local ring of prime module, flatness is a local property */
/* Flat module, example of flat module that is not a projective module:  Z-module Q is flat but not projective */
/* Flat module, faithfully flat: a module is faithfully flat if tensor product with it preserves exactness if and only if original sequence is exact */
/* Flat module, direct sum:  direct sum of an arbitrary family of modules is flat if and only if each module in the family is flat. This is a very useful closure property. */
/* Flat module, module of scalars:  flat module can be thought of as a module that "behaves like the base ring" with respect to the tensor product. It doesn't introduce any new relations or "torsion-like" behavior when tensoring. */
/* Flat module, flat morphisms of schemes:  morphism of schemes X to Y is flat at a point X if the corresponding local ring map is flat module, no deformation of fibres */
/* Flat module, vector space analogy:  over a field, every module is vector space, or every module is flat, because every short exact sequence of vector spaces split. */
/* Flat module, local freeness:  correct generalisation of locally free modules for non fg modules or non-Noetherain ring */
/* Flat modules, compare flatness to torsion:  integral domains with no torsion generalises to broader notion of flatness, torsion is about annhilators module having nonzero element m annihilated by nonzero element r is a form of torsion. */
/* Flat modules, geometric slicing or flat morphisms as a family of schemes:  flat morphism is family of schemes with nicely parametised base schemes with consistent dimension and no unexpected jumps */
/* Flat modules, finitely presented and flat:  fg module over Noetherian ring is flat if and only if it is projective */
/* Flat modules, unimodular row:  Replace projective module using relation and lifting property. Module is flat if every relation on finite set of elements of M lifts to a relation on the free module where M is a quotient. */
/* Injective module, similar to Q: Q as Z-module is prototype example for injective module */
/* Injective resolution, motivation for Ext functor:  Every module has an injective resolution so this can be used to derive Ext functors */
/* Ext functor, cohomology, cochain and injective resolution:  Take injective resolution, take cochain complex, take cohomology of this complex, get Ext group */
/* Injective module, enough injectives:  To form Ext functors need enough injectives, need existence of monomorphism from any object to injective object */
/* Ext functor, contravariant construction and covariant construction:  Ext of dimension i over ring R for (A, B) is contravariant in A (take cohomology of cochain complex of projective resolutions of A) and covariant in B (take cohomology of cochain complex of injective resolutions of B). */
/* Nakayama's lemma, finiteness annihilator: M be fg module over commutative ring R, I be an ideal of R, if IM = M, then there exists an element x in R such that x = 1 mod I, and xM = 0. */
/* Nakayama's lemma, local ring version:  Let R be comm. ring, m maximal ideal, (R, m) be local ring, let M be a fg R-module if M = mM, M = 0, most common form, immediate consequence of finiteness annhilator definition, pick I = m, 1 - x in m, x is unit xM = 0 implies M = 0. */
/* Nakayama's lemma, basis version:  Commutative ring R, maximal ideal m, (R, m) local ring, M a finitely generated R-module, if the images of a set of elements m_1 to m_n form a basis for the vector space M/mM over the residue field R/m, these elements generate M as an R-module. */
/* Nakayama's lemma, minimum generators version:  Min. generators of fg module over local ring (R, m) equal to dimension of vector space M/mM over residue field R/m. Quotient ring is like vector space, R/m is residue field, m maximal ideal. */
/* Nakayama's lemma, submodule version:  Let M be fg R-module, N submodule of M, I is ideal of R contained in Jacobson radical of R, if M = N + IM, then M = N. */
/* Nakayama's lemma, local result:  local result since works on maximal ideals, but can be applied to global statements. Example, homomorphism of fg modules is surjection iff induced map of localisation on every maximal ideal is surjection */
/* Nakayama's lemma, germ of objects:  local ring at point of scheme corresponds to set of neighbourhoods of that point. Nakayama's state that if fg module is trivial at infinitesimal neighbourhood of the point (stalk or filtered colimit of fg modules at that point is zero), then the module is zero in a neighbourhood */
/* Nakayama's lemma, algebraic homotopy theory, Jacobson radical is infinitesimal neighbourhood of the closed point, consider connected components of local ring:  About connected components in local ring, Jacobson radical is infinitesimal neighbourhood of the closed point, lemma says that if module is zero in the neighbourhood, must be zero globally. */
/* Nakayama's lemma, sheaf theory:  coherent sheaf of modules (finitely presented) F on a scheme X, if stalk F_x is 0 at every point in X, then F is the zero sheaf. */
/* Nakayama's lemma, vector bundle analogy:  if vector bundle is trivial when restricted to an infinitesimal neighbourhood of a point, must be trivial in a full neighbourhood */
/* Nakayama's lemma, conditions for filtered ring:  associated graded ring Noetherian, filtration is "nice" */
/* Nakayama's lemma, derived algebraic geometry:  spectrally ringed space (X, O_X), if a perfect complex of O_X modules P have zero fiber (space of sections instead of volumes) at all points of the space (infinitesimal neighbourhood), then the complex is 0 */
/* Nakayama's lemma for perfect complexes:  perfect complex P over local ring (R, m) is 0 iff derived tensor product with residue field R/m is 0. Compare this to vector space M/mM over residue field R/m version. */
/* Nakayama's lemma, fails without finitely generated:  let the ring R be the integers localised at 2, the module is Q, the maximal ideal m = (2), Q as Z_(2)-module is obviously nonzero, so need finitely generation. */
/* Filtration, of a module:  sequence of submodules indexed by poset */
/* Filtration, ordinal:  filtration with ordinal numbers up to limit ordinal */
/* Filtration, ascending submodules:  sequence of submodules is increasing */
/* Filtration, continuity:  submodule is union of all previous submodules */
/* Filtration, exhaustive:  union of all submodules is entire module */
/* Filtration, associated graded module:  associated graded module is direct sum of quotients of increment modules ++ M_{a+1} / M_{a} */
/* Filtration, Krull:  Defined by M_n = m^n M, ring R with maximal ideal m */
/* Filtration, chain condition:  module satisfies ascending chain condition if every strictly ascending chain of submodules is finite */
/* Filtration, prime ideal:  construction of composition series of modules are finite filtrations */
/* Filtration, n-primary:  filtration by powers of prime ideal M_n = p^n M, similar to Krull's filtration */
/* Filtration, Postnikov tower:  spectrum can be filtered by sequence of spectra E_n, n nonnegative, fiber of map E_n -> E_{n-1} is product of Eilenberg-Maclane spectra */
/* Filtration, spectral sequence:  computation that formalises the idea of an ordinal filtration, successive approximations from simpler filtered object to true complex object */
/* Filtrations, graded versus filtered:  gradings are rigid direct sums, filtrations are more flexible inclusions */
/* Radical, nilradical:  ideal of all nilpotent elements x^n = 0 for positive integer n */
/* Radical, Jacobson:  intersection of all maximal ideals, ideal of small elements, in the sense that Nakayama's lemma */
/* Radical, prime:  lower nilradical, intersection of all prime ideals, nilradical and prime ideal are the same need to prove */
/* Radical, ideal:  radical of an ideal, set of all elements x in the ring such that x^n is in the ideal for positive integer n. */
/* Radical, smallest:  radical of an ideal, intersection of all prime ideals containing I */
/* Radical, extremal:  nilradical is smallest prime ideal of the ring */
/* Radical, Noetherian:  nilradical is nilpotent ideal in Noetherian ring */
/* Radical, nilpotent elements:  elements in radical ideals are those that are eventually zero up to some power */
/* Radical, infinitesimal part:  nilradical of ring in algebraic geometry, corresponds to non-reduced part of the affine scheme Spec(R), infinitesimal fuzziness of geometric object */
/* Radical, Jacobson radical as local part:  Jacobson radical captures the properties of the ring that are local to its maximal ideals, for example a ring is a local ring if its Jacobson radical (intersection of all maximal ideals) is its unique maximal ideal */
/* Radical, nilradical spectrum of homotopy groups:  spectrum whose homotopy groups are nilradicals of the ring's homotopy groups */
/* Radical, nilradical of ring spectra:  the nilradical can be defined as the ideal of elements x such that the multiplication map by x is a nilpotent endomorphism in the stable homotopy category. This is a higher categorical generalization of the classical definition. */
/* Radical, Jacobson Radical in ring spectra:  Jacobson radical of a commutative ring spectrum R is defined as the intersection of all maximal ideals of the homotopy ring π0​(R). This concept is more subtle and relies on the structure of the homotopy ring. */
/* Radical, reduced:  an object is reduced if its nilradical is zero. The nilradical thus serves as a powerful criterion for an object to be "sharp" or "without infinitesimal thickening." */
/* Radical, closure of points:  radical of an ideal I is the ideal of all functions that vanish on the vanishing locus of I. It gives an algebraic description of the closure of the set of points where the ideal is zero. */
/* Radical, infinitesimals:  radical in a higher setting captures the "infinitesimal" properties of objects in a way that respects their homotopical nature. It describes how things are "close to zero" in a more structured way. */
/* Radical, nonseparatedness:  Jacobson radical can be viewed as a measure of how "non-separated" the maximal ideals of a ring are. If the Jacobson radical is zero, the maximal ideals are "well-separated" in some sense since the intersection of maximal ideals is zero. */
/* Local ring, maximal ideal:  single maximal ideal */
/* Local ring, set of non units:  ring is local if and only if its set of non-units (elements that don't have a multiplicative inverse) forms an ideal. This ideal is then the unique maximal ideal. */
/* Local ring, Jacobson:  ring is local if its Jacobson radical, which is the intersection of all maximal ideals, is a maximal ideal itself. */
/* Local ring, residue field:  local ring (R,m) has a unique residue field, which is the quotient ring k=R/m. */
/* Local ring, Nakayama's:  Local rings are the rings for which Nakayama's Lemma applies in its most direct form. The lemma states that if a finitely generated module M is equal to mM, then M=0. */
/* Local ring, direct products:  ring that is a direct product of two or more non-zero rings is never a local ring. A ring is local if and only if it is not a direct product of non-trivial rings. */
/* Local ring, localisation:  ring R and a prime ideal p, the localization of R at p, denoted Rp​, is a local ring with a unique maximal ideal pRp​. This is the primary way local rings arise in practice. */
/* Local ring, rational functions:  affine variety, the local ring at a point p is the set of rational functions that are defined at that point. This ring is local, with its maximal ideal consisting of functions that are zero at p. */
/* Local ring, Zariski topology:  Zariski topology on the prime spectrum of a ring, the local ring at a point (a prime ideal) is the ring of "functions" on the "infinitesimal neighborhood" of that point. */
/* Local ring, commutative ring spectrum:  commutative ring spectrum R is a local ring spectrum if its homotopy ring p0​(R) is a local ring. This is the most direct generalization. */
/* Local ring, localisation functor:  process of localizing a ring at a prime ideal has a direct analogue in spectral algebraic geometry: the localization functor on a category of modules over a ring spectrum. */
/* Local ring, infinitesimal:  algebraic model for an infinitesimal neighborhood of a point on a scheme. It discards global information to focus on what happens in a tiny region. */
/* Local ring, antithesis of global:  antithesis of a ring that is a direct product. It's "connected" in a strong algebraic sense, as it has no non-trivial idempotents besides 0 and 1. */
/* Minimal prime ideal, zero dimensional local ring:  prime ideal p is a minimal prime if and only if the localization Rp is a zero-dimensional local ring. This means its unique maximal ideal is also its nilradical. */
/* Minimal prime ideal, irreducible components:  minimal primes of a ring correspond to the irreducible components of its spectrum Spec(R). Each minimal prime is the generic point of an irreducible component. */
/* Minimal prime ideal, no other prime ideal:  no other prime ideal q such that q is in p */
/* Minimal prime ideal, associated prime:  minimal prime ideal of a Noetherian ring is an associated prime of the zero ideal. An associated prime of a module M is a prime ideal p that is the annihilator of some element in M. */
/* Minimal prime, radical of zero ideal:  nilradical of a ring is the intersection of all its minimal prime ideals (lol need not be minimal). This is a fundamental result that links the nilradical to the geometric structure of the ring. */
/* Minimal prime, Noetherian:  Noetherian ring, there are only a finite number of minimal prime ideals. This is a crucial finiteness property that simplifies many arguments. */
/* Minimal prime over an ideal I, ideal theoretic:  ideal I, a minimal prime over I is a prime ideal p containing I such that there are no other prime ideals between I and p. The minimal primes of the ring are just the minimal primes over the zero ideal. */
/* Minimal prime, chain of primes:  prime ideal is a minimal prime if and only if any chain of prime ideals contained in it must terminate at the prime itself. */
/* Minimal prime, nilpotent elements:  minimal primes are precisely the prime ideals that contain the nilradical. Since the nilradical is the set of all nilpotent elements, minimal primes are those that capture the most fundamental "non-reduced" parts of the ring. */
/* Minimal primes, intersections:  minimal prime cannot be written as the intersection of two strictly larger ideals. */
/* Minimal prime, generic point:  minimal prime is the generic point of an irreducible component. This means that a property that is true on a dense open subset of the component is also true at the minimal prime. */
/* Polynomial ring, formal expressions:  polynomial ring in one variable x over a ring R, denoted R[x], is the set of all expressions of the form a_n x^n to a_0. */
/* Polynomial ring, universal property:  ring that freely adjoints an element to the ring, for any R-algebra A and any element a in A, there is a unique R-algebra hom from R[x] to A that maps x to a */
/* Polynomial ring, monoid algebra:  monoid algebra of the monoid (N0​,+) over the ring R. This generalizes to multiple variables and other monoids. */
/* Polynomial ring, free commutative algebra:  polynomial ring in n variables, R[x1​,…,xn​], is the free commutative R-algebra on n generators. */
/* Polynomial, functions:  polynomial can be viewed as a function from R to R, but in general, this is a distinct concept. For infinite fields, the two are isomorphic. */
/* Polynomial ring, Hilberts basis theorem: R is a Noetherian ring, then R[x] is also Noetherian. This is the Hilbert Basis Theorem. */
/* Polynomial ring, Gauss's lemma: R is a UFD, then R[x] is also a UFD. This is Gauss's Lemma for polynomial rings. */
/* Polynomial rings, affine n-space:  prime spectrum of the polynomial ring k[x1​,…,xn​] over an algebraically closed field k is the affine n-space, A_k^n​. The polynomial ring is the ring of regular functions on this space. */
/* Polynomial ring, symmetric algebra: M free module with basis, Sym_R(M) is poly ring R of basis */
/* Polynomial rings, homological resolution:  construct free resolutions of modules */
/* Polynomial ring, exterior algebra:  anticommutative analogue of symmetric algebra, generalises noncommutative poly rings with de Rham cohomology */
/* Polynomial ring, stable homotopy theory:  polynomial ring spectrum is a commutative ring spectrum that is "freely generated." It's an object in a higher category that generalizes the concept of a polynomial ring. */
/* Polynomial ring, affine schemes:  polynomial rings is the foundation for defining affine schemes in algebraic geometry. An affine scheme is defined by a ring, and the polynomial ring defines affine space. */
/* Polynomial ring, projective space:  geometric object that extends affine space by adding a "hyperplane at infinity." */
/* Polynomial ring, function ring of schemes:  for any affine scheme X, the ring of regular functions on X is a quotient of a polynomial ring. This establishes the fundamental correspondence between geometry and commutative algebra. */
/* Polynomial ring, formal power series ring:  completion of the polynomial ring, consisting of infinite sums. It is used in local algebra and formal geometry. */
/* Polynomial ring, algebraic closure:  construction of the algebraic closure of a field. For any field k, every polynomial in k[x] has a root in the algebraic closure of k. An algebraically closed field is equal to its algebraic closure. */
/* Nilpotent, zero power element:  nilpotent element x in a ring is an element such that some positive integer power of it is zero, i.e., x^n = 0 for some n in positive integers */
/* Nilpotent, kernel of reduction map, reduced ring has nilradical as kernel:  nilradical is the kernel of the map from a ring R to its reduced ring R_red​ = R/nilrad(R)​. The reduced ring has no nonzero nilpotents because all parts in the nilradical are identified and vanished */
/* Nilpotent, algebraic variety analogy:  nilpotent element is an algebraic manifestation of a geometric object having "fat points" or "multiple components" at a single location. The algebraic variety defined by a polynomial equation might have a non-reduced structure at certain points due to nilpotents. */
/* Nilpotent, vanishing to high order:  nilpotent element can be seen as a function that vanishes to a high enough order at every point of the spectrum. For example, in the ring k[x]/(x^2), the element x is a non-zero nilpotent, and it corresponds to a function on a single point that vanishes to order 2. */
/* Nilpotent, morphism:  derived algebraic geometry, a nilpotent morphism is a morphism of ring spectra that is, in some sense, "infinitesimal." */
/* Nilpotent, in spectrum:  nilpotent element in a commutative ring spectrum R is an element x in derived ring p(R) such that the multiplication map x: R to R is a nilpotent map in the stable homotopy category. */
/* Module, vector space where you cannot scale down scalars: a grid of points, like a vector space. A module is a more flexible grid where the "scalars" (the ring elements) may not have multiplicative inverses, so you can't always "divide" or scale down. */
/* Module, direct sum as stacking of two grids:  direct sum of two modules is a new module whose elements are pairs of elements from the original modules. Imagine two grids. The direct sum is a new, larger grid that's a "stacking" of the two original grids. */
/* Module, free module as perfect regular grid:  free module is a module that has a basis, just like a vector space. Every element can be uniquely written as a linear combination of basis elements. Visual Intuition: A free module is a "perfectly regular" grid. Every point in the grid can be reached by a unique combination of "steps" along the basis vectors. */
/* Module, finitely generated grid:  finitely generated if it can be generated by a finite number of elements. Visual Intuition: A finitely generated module is like a grid that can be "drawn" with a finite number of lines, as opposed to a potentially infinite number of lines. */
/* Module, projective module as one that sits nicely in a perfectly regular grid:  projective module is like a "subset" of a perfectly regular grid that is itself a module. It's not a perfectly regular grid itself, but it sits nicely inside one. A projective module is a direct summand of a free module. */
/* Module, injective module as a module with no holes:  module with "no holes." Any map to the module from a submodule can be extended to a map from the whole module. */
/* Module, chain complex of modules and intuition with maps that go from one grid to a next:  the homology of this chain complexes measures its "holes." Chain complex is a sequence of grids, with "maps" that go from one grid to the next. The homology is a measure of the "failed" maps. */
/* Module, sheaf of modules:  gluing together local modules. Imagine a collection of grids, one for each open set, that are consistently glued together. */
/* Module, quasicoherent sheaf as global modules that look like simple local modules when you zoom in: a quasicoherent sheaf is a sheaf of modules that is locally isomorphic to a module. It's the geometric equivalent of an abstract module. "global module" that looks like a simple, local module when you "zoom in." */
/* Quasicoherent sheaf, sheaf of OX modules that is locally isomorphic to R-module:  quasicoherent sheaf on a scheme X is a sheaf of OX​-modules that is locally isomorphic to the sheaf associated with an R-module. It's the correct way to transport module theory to a geometric setting. */
/* Quasicoherent sheaf, sheaf from a module:  ring R, every R-module M gives rise to a quasicoherent sheaf M on the affine scheme Spec(R). */
/* Quasicoherent sheaf, module functor:  associating a sheaf to a module, the quasicoherent sheaf M~, defines a functor from the category of R-modules to the category of quasicoherent sheaves on Spec(R). This functor is an equivalence of categories. */
/* Quasicoherent sheaf, local isomorphism on the level of stalks:  sheaf F is quasicoherent if for every point x in scheme X, there exists an affine open neighborhood U = Spec(R) of x and an R-module M such that the section on the open neighbourhood F_U is locally isomorphic to the quasicoherent sheaf M-. */
/* Quasicoherent sheaf, global module patching modules over local rings:  "global module" that is constructed by patching together modules over local rings. */
/* Quasicoherent sheaf, compared to coherent sheaf:  quasicoherent sheaf is coherent if it is locally isomorphic to a sheaf associated with a finitely presented module. Coherent sheaves are the geometric counterparts of finitely presented modules, whereas quasicoherent sheaves correspond to all modules. */
/* Quasicoherent sheaf, pushforward of a module using structural morphism of affine scheme:  quasicoherent sheaf on a scheme can be defined by the pushforward of an R-module under the structural morphism from an affine scheme to the given scheme. */
/* Quasicoherent sheaf, visual analogy as space of functions:  quasicoherent sheaf can be visualized as a "space of functions" on a scheme, where the "functions" are sections that are defined locally and glued together. */
/* Quasicoherent sheaf, on the level of stalks:  stalk: localisation of module M at prime ideal p which is a local ring; section over U is isomorphic to quasicoherent sheaf M-; stalk of quasicoherent sheaf at a prime ideal p is localisation of module M at prime ideal p, which is a local ring */
/* Quasicoherent sheaf, homotopical derived quasicoherent sheaf:  sheaf whose stalk at every point is a complex of modules that is "homotopically quasicoherent," meaning it satisfies a local property in the stable homotopy category. */
/* Quasicoherent sheaf, derived quasicoherent sheaves that is locally quasi-isomorphic:  sheaf of complexes of modules that is locally quasi-isomorphic to a complex of modules over a ring. */
/* Quasicoherent sheaves, derived functors:  forming a derived quasicoherent sheaf from a module can be seen as a derived functor of the classical functor. */
/* Quasicoherent sheaf, stacks:  quasicoherent sheaves generalizes to stacks, where a quasicoherent sheaf on a stack is a more general type of a bundle that has symmetries. */
/* Locally free module, locally free object is analogous to product of base space and fibre, or fibration with contractible:  locally free object is analogous to a space that is a product of its base space and a fiber, locally. A fibration with a contractible fiber is analogous to a locally trivial bundle. */
/* Locally free module, classification leads to algebraic K-theory to measure farness from all modules being locally free:  classification of locally free modules (vector bundles) leads to algebraic K-theory. This is an ontology where we "measure" how far a ring is from having all its locally free modules be free. The Grothendieck group K0​(R) is a way to make the set of isomorphism classes of locally free modules into a group. */
/* Locally free modules, projective resolutions as generalisation of locally free module:  in homological algebra, we use projective resolutions to "resolve" (approximate) a module with a sequence of projective (or free) modules. This is a generalization of the idea that locally free modules are "like" free modules. */
/* Locally free modules, line bundles as locally free sheaf of rank 1: line bundle is a locally free sheaf of rank 1. Geometrically, it's a vector bundle where each fiber is a one-dimensional vector space. Think of the tangent bundle of a circle, which is a line bundle. */
/* Locally free module, tangent sheaf as locally free sheaf:  tangent sheaf of a scheme is a locally free sheaf that captures the infinitesimal behavior of the scheme. Its fibers are the tangent spaces at each point. This is a direct generalization of the tangent bundle of a manifold */
/* Associated prime, module R/(xy) as with irreducible axes as the irreducible primes:  associated prime of a module M over a commutative ring R is a prime ideal p that is the annihilator of some element x in M, Consider the ring of polynomials R=k[x,y] and the module M = R/(xy). The prime ideals corresponding to the x-axis and y-axis are (x) and (y). The associated primes are (x) and (y) because they annihilate the elements y and x respectively in the quotient ring. This can be visualized as the set of irreducible components of the variety defined by the annihilator of the module, which in this case are the x and y axes. */
/* Associated prime, embedded prime, x-axs as embedded prime subset of ideals, but origin is embedded in x-axis case of polynomial ring k[x,y], and module k[x,y]/(x^2, xy):  An embedded prime is an associated prime that is contained in another associated prime. Consider the ring k[x,y] and the module k[x,y]/(x^2,xy). The associated primes are (x) and (x,y). Here, (x) is an embedded prime because it is a subset of (x,y). Geometrically, the ideal (x,y) corresponds to the origin, which is embedded in the line defined by the ideal (x). */
/* Associated primes, on a sheaf are associated primes of a stalk since these are algebraic, corresponds to irreducible components on the support of the sheaf:  The associated primes of a sheaf on a scheme are the associated primes of the stalks of the sheaf at its points. The associated primes of a sheaf correspond to the irreducible components of the support of the sheaf. The support is the set of points where the sheaf is non-zero. For example, a sheaf of functions that is non-zero only on the x-axis has (x) as an associated prime. */
/* Associated points, singular points or subvariety on the support of the sheaf, example for k[x,y]/(x^2, xy) on affine plane, associated points are origin and entire x-axis:  An associated point is a point in the support of a sheaf that corresponds to an associated prime. An associated point is a "singular point" or "subvariety" of the support of a sheaf. For the sheaf k[x,y]/(x2,xy) on the affine plane, the associated points are the origin and the entire x-axis. The origin is "embedded" in the x-axis. */
/* Associated primes, support of Ext functors, Ext functors measure obstruction of homomorphism:  The associated primes can be used to compute the support of the Ext functors. The Ext functors measure the "obstructions" to a homomorphism. The associated primes tell you where these obstructions live, geometrically. */
/* Associated primes, ideals that give the rank of the module, associated primes are locations where the module behaviour changes:  rank of a module is the dimension of the free module it looks like locally. The associated primes are the ideals that give the rank of the module. The associated primes of a module are the "points" where the dimension of the module changes. For a module over a polynomial ring, the associated primes can be thought of as the locations where the module's behavior changes, such as where it has a singularity. */
/* Ramification, prime ideals, imagine the prime ideals of Z as points on a number line. When we extend to a larger number field, this line is "unfolded" into a higher-dimensional space. The prime ideals in the larger field are also points, but some of them might "pile up" on top of the original prime ideal. In the case of Q(root 5)/Q, the prime (5) splits into (5) twice, which can be visualized as two points "collapsing" onto the original point. This is the geometric intuition of ramification:  In algebraic number theory, ramification describes the behavior of a prime ideal p in a number field K when it is extended to a larger number field L. The ideal pO_L​ factors into a product of prime ideals in the ring of integers of L. Ramification occurs when at least one of these prime factors appears with a power greater than 1. This "bunching up" or "confluence" of prime factors is a fundamental concept. For example, in the extension Q(root 5)/Q, the prime ideal (5) of Z"ramifies" as it becomes the ideal (root 5​)^2 in the ring of integers Z[1 + root(5) / 2] */
/* Ramification, domain P^1 as a sphere. The map z to z^2 wraps the sphere around itself twice. The points z=0 and z= infity are ramification points. This is where the wrapping "bunches up," and the pre-image of the image point is not a single point but a single point with multiplicity:  For a non-constant morphism of smooth curves f: X to Y, a point p in X is a ramification point if the corresponding map on local rings is not an isomorphism. This is a geometric phenomenon where the map "folds" or "pinches" the curve at a point. The degree of ramification is measured by the ramification index, which is a key invariant. For example, the map f: P^1 to P^1 given by z to z2 is ramified at the point z = 0. */
/* Ramification, real place is a point on a line. A complex place is a pair of points. The ramification of a real place into a complex one can be visualized as a single point on a line "splitting" into two points in a higher-dimensional space:  In the theory of valuations, ramification describes the behavior of a place of a number field in an extension. A place can be a prime ideal (finite place) or an embedding into the real or complex numbers (infinite place). Ramification of a finite place means the valuation of an element changes in a non-trivial way, while for infinite places it means a real place becomes a complex one. For example, in Q(root(-1))/Q, the real place of Q is ramified because it becomes a complex place. */
/* Ramification, Galois group as a group of symmetries of the extension. The decomposition group of a prime ideal is a subgroup that fixes the ideal. Ramification means that this subgroup is not trivial, so there are some "symmetries" that leave the ideal unchanged:  In a Galois extension of number fields L/K, ramification occurs when the decomposition group of a prime ideal is not trivial. This means that there are elements in the Galois group that fix the prime ideal but not the elements in its ring. This is a subtle but deep concept that links the algebraic properties of the extension to its number-theoretic properties. */
/* Ramification, imagine a sheet of paper. A branched cover is like folding the paper and then projecting it onto a line. The folds are the ramification locus, and the line they are projected onto is the branch locus. The map from the curve to the line is a branched cover that folds the curve at the points where the tangent is vertical: A branched cover is a surjective map of varieties with ramification. The set of ramification points is called the ramification locus, and its image is the branch locus. The map from a variety to its base is a local isomorphism everywhere except at the ramification locus. For example, the map from the curve y^2 = x(x−1)(x−2) to the affine line given by projection to the x-axis is a branched cover. */
/* Ramification, imagine a map from a disk to a disk. A critical point is a point where the map "flattens" or "folds" the disk. The dynamics around this point are very complex and can lead to chaotic behavior:  In dynamics, ramification occurs in complex dynamics when a map has critical points. A critical point is a point where the derivative of the map is zero. This is a point where the map "folds" or "pinches." For example, the map z to z^2 has a critical point at z=0. */
/* Ramification, canonical divisor is a geometric object that is a "dual" to the tangent bundle. It is a line bundle that is related to the ramification of the map:  The canonical divisor of a curve is a divisor that is related to the ramification of the curve. The degree of the canonical divisor is related to the genus of the curve and the ramification of the map. */
/* Ramification, Hilbert symbol is a "map" that measures the ramification. It is a way of "quantifying" the ramification:  The Hilbert symbol is a symbol that measures the ramification of a number field extension. The Hilbert symbol is a key tool in class field theory. */
/* Ramification, Serre duality is a "duality" between two geometric objects. The ramification of the map is a key ingredient in this duality:  The concept of ramification is used to formulate Serre duality, which is a duality theorem for coherent sheaves on a scheme. The duality is between the cohomology of a sheaf and the cohomology of its dual. */
/* Ramification, covering space is a "bundle" of spaces. A ramified covering space is a covering space that "folds" or "pinches" at some points: A ramified covering space is a generalization of a covering space. A covering space has the property that the fibers are discrete sets. A ramified covering space has the property that the fibers can have "ramification." */
/* Ramification, moduli space of curves is a geometric object. The ramification of a family of curves is a phenomenon that occurs when the fibers of the family have "non-trivial" automorphisms:  The concept of ramification is used to study the moduli space of curves. The moduli space is a geometric object that classifies curves. The ramification of a family of curves is a phenomenon that occurs when the fibers of the family have "non-trivial" automorphisms. */
/* Automorphisms, the number field Q(root 2) as a 2D plane with rational coordinates. The points are of the form (a,b) representing a+b root(2)​. The nontrivial automorphism is a reflection of this plane across the a-axis. It maps every point to its reflection while preserving all algebraic operations: A nontrivial automorphism of a number field K is a field isomorphism from K to itself that is not the identity. These are also known as Galois automorphisms. For example, the number field Q(root(2)) has an automorphism that maps a+ b root(2)​ to a− b root(2). */
/* Automorphisms, affine line as a line. An automorphism is a transformation of this line that preserves its algebraic structure. A nontrivial automorphism is a shift or a scaling of the line, like the map x↦x+1 or x↦2x: A nontrivial automorphism of a scheme X is a scheme isomorphism from X to itself that is not the identity. These are more general than automorphisms of varieties. For example, the affine line A_k^1​ has automorphisms of the form x to ax+b, entry fields in k. */
/* Automorphisms, groupoid as a collection of objects with arrows between them. The automorphisms are loops from an object to itself. A nontrivial automorphism is a loop that is not just the identity: A nontrivial automorphism of an object in a groupoid is an isomorphism from the object to itself that is not the identity. The groupoid is a category where all morphisms are isomorphisms. */
/* Automorphisms, fundamental group of a space, like a torus, is a group of loops. A nontrivial automorphism of this group is a transformation that shuffles the loops in a way that is not just conjugation: A nontrivial automorphism of the fundamental group of a space is an automorphism of the group that is not inner. */
/* Automorphisms, a family of elliptic curves. Some of the curves have extra automorphisms, like a curve with complex multiplication. This corresponds to a fiber with a larger automorphism group:  The study of nontrivial automorphisms of fibers in a family of varieties is a key topic in algebraic geometry. The group of automorphisms can change from fiber to fiber. */
/* Automorphisms, module is a geometric object. Its automorphisms are symmetries of this object. The study of these automorphisms helps us understand the structure of the module:  The study of nontrivial automorphisms of objects in a category is a key topic in homological algebra. For example, the study of automorphisms of a module is a key topic. */
/* Quasicoherent sheaf, imagine the ring Z as a single point, Spec(Z). A Z-module is a group. A quasicoherent sheaf on Spec(Z) is just a group. A more complex example is the ring of polynomials C[x]. A module over this ring is a vector space with a linear operator. A quasicoherent sheaf over Spec(C[x]) is a family of vector spaces parameterized by the affine line, together with a linear operator that varies smoothly: A quasicoherent sheaf is the geometric analogue of a module in commutative algebra. Just as a module over a ring R is a "linear" object, a quasicoherent sheaf is a "linear" object over a scheme. It is the natural setting for studying modules from a geometric perspective. */
/* Gorenstein ring, a Gorenstein ring is like a geometric space that is "homologically symmetric." Imagine a regular local ring, which is geometrically a smooth point. A Gorenstein ring is a generalization of this. It's a point that might have a singularity, but the singularity has a "homological symmetry." For example, the ring k[x,y]/(x^2,y^2) has a singularity at the origin, but it is Gorenstein. Its homological structure is symmetric, and it has a "mirror" image in its injective dimension: A Gorenstein ring is a commutative Noetherian local ring (R,m) that has finite injective dimension as a module over itself. This is a crucial property that makes these rings "well-behaved" from a homological perspective. For example, a regular local ring is always Gorenstein. */
/* Gorenstein ring, is a geometric object that is "homologically symmetric." A smooth variety is a Gorenstein scheme, which can be visualized as a surface with no singularities. A Gorenstein scheme can have singularities, but they are "well-behaved." For example, a variety with a single isolated singularity can be Gorenstein. The canonical sheaf is a line bundle, which is a very simple and well-behaved object: A Noetherian scheme X is Gorenstein if it is Cohen-Macaulay and its canonical sheaf is an invertible sheaf. A Gorenstein scheme is a geometric object with a well-behaved canonical sheaf. For example, a smooth variety is Gorenstein. */
/* Gorenstein ring, a group algebra as a geometric object. A Gorenstein group algebra is a symmetric object. The left and right injective dimensions are finite. This is a very strong property that is a generalization of the commutative case: A group algebra kG is Gorenstein if it has finite injective dimension as a module over itself. This is a key property that is used to study the modular representations of a group. A Gorenstein group algebra is a "symmetric" object. */
/* Gorenstein ring, Ext groups measure the "extensions" of modules. A Gorenstein ring has symmetric Ext groups. This is a very strong property that makes the ring easy to work with: A commutative Noetherian local ring (R,m) is Gorenstein if the Ext groups of the residue field k with itself are symmetric. */
/* Cohen-Macaulay ring, geometric space that has a "well-behaved" dimension. Imagine a smooth variety, which is always Cohen-Macaulay. The dimension of a smooth variety is the number of independent parameters needed to describe a point on it. The depth is the length of a maximal regular sequence, which can be thought of as the number of "cuts" you can make without hitting a singularity. A Cohen-Macaulay ring is a ring where these two numbers are the same. A nonsingular variety is a great example: A Cohen-Macaulay ring is a commutative Noetherian local ring (R,m) such that its depth is equal to its dimension. The depth of a ring is the length of a maximal regular sequence in the maximal ideal. This is a crucial property that makes these rings "well-behaved" from a geometric and homological perspective. For example, a regular local ring is always Cohen-Macaulay. */
/* Cohen-Macaulay, scheme is a geometric object that is "well-behaved." It is a generalization of a smooth variety. A variety with a single isolated singularity can be Cohen-Macaulay, but a variety with a "cone-like" singularity, like the cusp y^2 = x^3, is not. The Cohen-Macaulay property ensures that the singularities are "not too bad.": A Noetherian scheme X is Cohen-Macaulay if its local rings are all Cohen-Macaulay. A Cohen-Macaulay scheme is a geometric object with a "well-behaved" dimension. For example, a smooth variety is Cohen-Macaulay. */
/* Valuations, imagine the rational numbers Q as a line. The usual absolute value measures the distance from zero. A p-adic valuation measures a different kind of "distance" from zero, where numbers divisible by higher powers of p are "closer" to zero.This creates a "tree-like" structure on the rational numbers. For instance, in the 5-adic valuation, the numbers 1,2,3,4 are all at "distance" 1 from 0. The number 5 is at "distance" 1/5, and the number 25 is at "distance" 1/25: A valuation on a field K is a function that assigns a real number to each element of the field, satisfying certain properties that generalize the notion of absolute value. A non-archimedean valuation is one for which the triangle inequality is replaced by a stronger condition, norm(x+y) ≤max(norm(x), norm(y(). This is a powerful tool for studying the arithmetic properties of a field. For example, the p-adic valuation on the field of rational numbers Q assigns to each non-zero rational number x a value that depends on the highest power of the prime p that divides x. */
/* Valuation, valuation ring is like a "local neighborhood" around a point on a curve. For a valuation on the field of rational functions on a curve, the valuation ring is the ring of functions that are regular at a point. This is a very powerful geometric intuition that connects algebraic objects to geometric ones: A valuation on a field K is a function v: K to G union {point at infinity}, where G is an ordered abelian group, satisfying v(xy) = v(x) + v(y) and v(x+y) more than min(v(x),v(y)). The ring of a valuation is the set of all elements with non-negative valuation. For example, the p-adic valuation on Q has the ring of p-adic integers Z(p)​. */
/* Valuation, number field is a geometric object. The places are the "points" of the number field. A valuation is a way of "measuring" a number in a way that is compatible with the "geometry" of the number field: A place of a number field is an equivalence class of valuations. The finite places correspond to the prime ideals of the ring of integers, and the infinite places correspond to the embeddings into the real or complex numbers. A valuation gives us a way to "measure" a number in a way that is compatible with the number field. */
/* Valuation, variety is a geometric object. A valuation is a way of "zooming in" on a point on the variety. The valuation ring is the ring of all functions that are "well-behaved" at that point: A valuation on a field K is a function that gives rise to a valuation ring. The valuation rings on a field of rational functions on a variety correspond to the points on the variety. This is a very powerful tool for studying the geometry of a variety. For example, a valuation on the field of rational functions on the affine line A1 corresponds to a point on the line. */
/* Valuation, module over a group algebra is a geometric object. A valuation is a way of "measuring" the "size" of this object:  In modular representation theory, a valuation is a function that gives us a way to "measure" the "size" of a module. For a module over a group algebra, a valuation is a function that is related to the prime ideals of the group algebra. */
/* Valuation, a divisor is a geometric object. A valuation is a way of "measuring" the "multiplicity" of this object: A divisor on a variety is a formal sum of prime divisors. A valuation is a function that gives us a way to "measure" the "multiplicity" of a divisor. This is a key concept in the theory of divisors. */
/* Valuation, imagine a polynomial as a curve. Hensel's Lemma says that if the curve has a "root" in a small "neighborhood," then it has a "root" in a "bigger neighborhood.":  Hensel's Lemma is a key result in number theory that gives a criterion for the existence of roots of a polynomial in a complete field with respect to a non-archimedean valuation. This is a powerful tool for solving equations. */
/* Valuation, "measuring" the "size" of an ideal. This is a key concept in the theory of ideals. Krull's Theorem states that every proper ideal in a commutative ring is contained in a maximal ideal. This is a key result in commutative algebra. A valuation is a way of "measuring" the "size" of an ideal:   */
/* Splitting lemma, projection map from R3 onto the xy-plane. The kernel of this map is the z-axis, and the image is the xy-plane. The Rank-Nullity Theorem says that the dimension of the starting space (3) is the sum of the dimension of the kernel (1) and the dimension of the image (2). This can be visualized as a 3D space that is a direct sum of a line and a plane:  In linear algebra, the Splitting Lemma is a formalization of the Rank-Nullity Theorem. For a linear map T: V to W, the short exact sequence is 0 to ker(T) to V to Im(T) to 0. The theorem states that dim(V)=dim(ker(T))+dim(Im(T)). Since any short exact sequence of vector spaces splits, this is always true. Consider example of projection map from R3 onto the xy-plane. The kernel of this map is the z-axis, and the image is the xy-plane. The Rank-Nullity Theorem says that the dimension of the starting space (3) is the sum of the dimension of the kernel (1) and the dimension of the image (2). This can be visualized as a 3D space that is a direct sum of a line and a plane. */
/* Splitting lemma, dihedral group D3​, the group of symmetries of an equilateral triangle. There is a short exact sequence 1 to C3​to D3​ to C2​ to 1, where C3​ is the group of rotations and C2​ is the group of reflections. The sequence splits, but D3​ is not the direct product C3​ × C2​. Instead, it's a semidirect product. The reflection "twists" the rotations, preventing a simple direct sum structure:  For non-abelian groups, the Splitting Lemma isn't quite the same. If a short exact sequence of groups 1 to A to B to C to 1 is right split, then B is a semidirect product of A and C. It is only a direct product if the splitting map is trivial. */
/* Splitting lemma, trivial line bundle on a circle, which is a cylinder. We can "split" the tangent bundle of the cylinder into a vertical tangent line bundle and a horizontal tangent line bundle. The total tangent bundle is the direct sum of these two, which corresponds to the splitting of the exact sequence:  The splitting of a short exact sequence of vector bundles on a variety corresponds to the direct sum decomposition of the bundles. A sequence 0 to E′ to E to E′′ to 0 splits if and only if E is isomorphic to direct sum of E′ and E′′. */
/* Splitting lemma, group Z ++ Z/2​. The torsion subgroup is Z/2​. The free part is Z. The splitting is the decomposition of the group into a number line and a two-point group. This shows how the group is built from these two pieces:  For a finitely generated abelian group A, the sequence 0→A_tor​→A→A/A_tor​→0 splits, where A_tor​ is the torsion subgroup. This means A can be decomposed into its torsion part and a free part. */
/* Splitting lemma, the Wedderburn-Artin theorem says that a "nice" non-commutative ring can be broken down into a simple, geometric structure of matrices. The Splitting Lemma is the underlying tool that allows this decomposition:  The Wedderburn-Artin theorem states that a semisimple ring is a direct product of matrix rings over division rings. This theorem is a consequence of the fact that every module over a semisimple ring is a direct sum of simple modules, which is a result of the Splitting Lemma. Visual intuition: The Wedderburn-Artin theorem says that a "nice" non-commutative ring can be broken down into a simple, geometric structure of matrices. The Splitting Lemma is the underlying tool that allows this decomposition. */
/* Splitting lemma, ring of integers as a lattice of points. The class group measures "holes" in this lattice. The splitting lemma says that the lattice has no "holes" if and only if a certain sequence splits:  The class group of a number field is a measure of the failure of unique factorization. A certain short exact sequence involving the class group splits if and only if the ring of integers is a principal ideal domain. Visual intuition: Imagine the ring of integers as a lattice of points. The class group measures "holes" in this lattice. The splitting lemma says that the lattice has no "holes" if and only if a certain sequence splits. */
/* Splitting lemma, the composition series is like a way of building up a complex object from simple blocks. The Splitting Lemma is a condition that allows this process to be reversible, allowing a complex object to be decomposed into simpler ones:  The Jordan-Hölder theorem states that a composition series of a module is unique up to isomorphism and permutation. While not a direct application of the Splitting Lemma, it is a consequence of related ideas. A module is a finite direct sum of simple modules if and only if it has a composition series whose simple subquotients are those simple modules. */
/* Completion, construction of the real numbers R from the rational numbers Q. Imagine the rational numbers as discrete points on a line with many "holes." The completion process fills in these holes with the irrational numbers, such as root(2) or π. This creates a continuous, unbroken line. The completed space, R, is "complete" because every sequence that "should" converge does converge to a point within the space:  In analysis, a completion is the process of constructing a complete metric space from an incomplete one by adding all the limits of its Cauchy sequences. */
/* Completion, ring R with an ideal I as a space. The quotients R/I, R/I^2, R/I^3,… represent a sequence of increasingly "finer" approximations of the ring, where we are progressively ignoring less and less information about the ideal. The inverse limit is the "final product" that incorporates all this information. For example, the ring of integers Z completed with respect to the ideal (p) for a prime p gives the p-adic integers Zp​, which contain infinite "series" of powers of p. The elements of Zp​ are "infinite strings" of numbers in Z/p^n Z that are compatible with each other:  In commutative algebra, the I-adic completion of a commutative ring R with respect to a proper ideal I is defined as the inverse limit of the quotient rings invlim​ ​R/I^n. This construction gives R a topology where the powers of I form a basis of open neighborhoods around 0. */
/* Completion, algebraic variety, the Zariski topology is very "coarse." Points are "isolated" and neighborhoods are very large. By completing the local ring at a point, we are essentially "zooming in" to such an extreme degree that we can see the "infinitesimal" structure around it. This process gives a much richer topology (the m-adic topology) that's closer to what we'd expect from a manifold. For example, completing the ring of polynomials C[x] at the ideal (x) gives the ring of formal power series C[[x]]. This allows us to think of functions near x=0 using infinite series:  In algebraic geometry, completion of the local ring of a scheme at a point allows us to study the "infinitesimal" or "formal" neighborhood of that point. For a point x on a scheme X with local ring O_{X,x}​, the completion is the ring O_{X,x}​, which is the inverse limit of the quotients of the maximal ideal. */
/* Completion, circle S1 has a fundamental group Z. The profinite completion of Z is Z = invlim​_n ​Z/nZ. The profinite completion of the circle is a space with a fundamental group that is "filled in" with all the "finite pieces" of the integers:  In homotopy theory, the profinite completion of a space X is a space X^ whose fundamental group and higher homotopy groups are the profinite completions of the original groups. It's constructed as an inverse limit of spaces with finite covers. */
/* Completion, module as a vector space over a ring. The completion is like taking a sequence of projections onto smaller and smaller subspaces and then "piecing" them back together. This process allows us to study a complex module by analyzing a series of simpler, finite-dimensional quotients, and the completion itself is the ultimate "assembly.":  In homological algebra, the completion of a module M over a ring R with an ideal I is defined as the inverse limit lim​ ​M/I^n M. This process allows us to study the local properties of a module in the I-adic topology. */
/* Completion, group ring F_p​[G] is the "space" of all representations. The completion at a Sylow p-subgroup is like "zooming in" on a specific point of this space. This allows us to study the representations of the whole group by studying the representations of a simpler subgroup, which can be visualized as a "local" analysis of a global object:  In modular representation theory, the completion of a group ring F_p​[G] at the ideal generated by a Sylow p-subgroup is a powerful tool. It allows for a transfer of knowledge between the group algebra and its local properties. */
/* Completion, rational function on the complex plane can behave erratically at infinity. By compactifying the complex plane into a sphere by adding a "point at infinity," we can study the behavior of the map at that point. This makes the map a continuous function from the sphere to itself. The completion provides a "holistic" view of the dynamics:  In dynamics, the completion of a rational map f(x) in C(x) is the process of extending the map to the Riemann sphere P^1(C). The completion adds a point at infinity, which allows for a more complete study of the map's dynamics. */
/* Completion, scheme as a geometric space. A closed subscheme is a "subspace." The formal completion is a space that is "sewn" onto the original scheme along the subscheme. It allows us to study the geometry of the original space in a very small neighborhood of the subscheme:  In algebraic geometry, the formal completion of a scheme X along a closed subscheme Y is a new scheme that "lives" in the infinitesimal neighborhood of Y. */
/* Completion, an algebra with a filtration is a set of "approximations." The completion is the "limit" of these approximations, which is a new algebra that is "finished" in a sense. This allows for a more robust study of the original algebra:  In non-commutative ring theory, the completion of an algebra with a filtration is a process that creates a new algebra that is complete with respect to the filtration. */
/* Completion, a number field is a "global" object. The completion at a prime ideal is like "zooming in" on that prime ideal to study its properties. This is analogous to studying a manifold by looking at its tangent spaces:  In arithmetic number theory, the completion of a number field K at a prime ideal p is a local field. This process allows us to study the number-theoretic properties of K "locally." */
/* Completion, division ring is a set of "numbers" with division. The completion is a process of adding "missing numbers" to make the set complete. This is analogous to constructing the real numbers from the rationals:  in non-commutative ring theory, the completion of a division ring with a valuation is a new division ring that is complete with respect to the valuation. */
/* Completion, Dedekind domain is a "global" object. The completion at a prime ideal is like "zooming in" on that prime ideal to study its properties. This is analogous to studying a manifold by looking at its tangent spaces:  In arithmetic number theory, the completion of a Dedekind domain at a prime ideal is a discrete valuation ring, which is a key tool in studying the local properties of the domain. */
/* Locally free module, vector bundle over the space:  "space" is the spectrum of the ring, Spec(R), and the module M corresponds to the collection of "fibers" (vector spaces) over each point of the space. A module is locally free if the fibers over points in a neighborhood all have the same dimension, and the bundle is trivial (like a product) over that neighborhood. */
/* Locally free, deformation of a free module: a free module as a perfectly straight, rigid structure. A locally free module is like a deformed or twisted version of this structure that, when you zoom in, still looks straight. The Möbius strip is a classic example of a line bundle that is locally trivial (looks like a line locally) but not globally trivial. */
/* Module, projective subspace that can be projected back:  projective module is like a subspace that can be "projected back" onto the larger space without losing information, for example, a plane in R3. Projective modules are always locally free. */
/* Dedekind domain, unique factorization of ideals:  Need not be a unique factorization domain on elements, but it does have unique factorization of ideals. */
/* Dedekind domain, visual intuition of an ring of regular functions on an algebraic curve on a smooth affine variety:  Imagine a smooth curve with no sharp corners or self intersections, this corresponds to a Dedekind domain on the ring of regular functions on a smooth affine varieties. The “prime ideals” correspond to points on the curve with unique factorization in these points. */
/* Dedekind domain, visual intuition for the standard definition of Noetherian, integrally closed, of dimension 1 using the ring of regular functions as your guide: A ring of regular functions on a smooth affine variety with no self intersections. Noetherian means every ascending chain of ideals terminates, think visually of a finite inclusion of ideals, integrally closed means there are no holes where no element from the field of fractions can be an algebraic integer or a root of a monic polynomial as a hole, dimension one means lines, points are the only one dimensional subobjects. */
/* Dedekind domain, visual comparison with (higher dimensional) Krull domain both with some factorisation due to prime ideals:  Prime ideals of height 1 are what matters for factorisation of prime ideals, these corresponds to lines whose . So a Krull domain is a higher dimensional analogue, with the same factorization property as Dedekind domain. */
/* Dedekind domain, ideal class group to distinguish between Dedekind domains and unique factorization domains:  Ideal class group measures the twisting in the Dedekind domain (factorization on ideals) that prevents it from being a unique factorization domain (factorisation of elements), a trivial ideal class group means the structure is flat */
/* Dedekind domain, defined with homological projective resolution of dimension 1 and is an integral domain, visual intuition:  Recall the visual intuition for an integral domain is that it has no “holes” that are formed out by elements in the field of fractions to serve as algebraic integers in the roots of polynomials. A projective resolution of dimension 1 is very simple? It only has a set of generators as a free module (with a basis) and a set of relations as a free module as well (with a basis) */
/* Dedekind domains, ideal visually viewed as lattices:  Ideals in a Dedekind domain can be viewed as lattices in a vector space. */
/* Cogenerator, visual intuition for non-zero elements as a detector (right M-module) using sensory input (ring homomorphism from M to Q): A cogenerator is a detector for nonzero element from a nonzero module using a ring homomorphism (as a sensory input). Let Q be a right R-module (detector) that for a nonzero module M and a nonzero element m in module M, there is always a ring homomorphism (sensory input) f from M to Q such that f(m) is nonzero in module Q. We can say Q is a cogenerator. */
/* Cogenerators, faithful functor and distinguishing detector analogy and using Hom to turn other modules into sensory input:  Let Q be a right R-module, we can turn it into maps by applying Hom functors into Q, Hom(-, Q) (sensory input) this takes a set of maps of right R-modules (category) to a set of maps of abelian groups (category) that is able to distinguish if two maps are different (detecting faithfulness) */
/* Partition of unity, sphere S2 and an open cover consisting of two open hemispheres. We can construct a partition of unity with two functions, ρ1​ and ρ2​. Function ρ1​ is 1 on a smaller open set in the northern hemisphere and smoothly drops to 0 at the equator. Function ρ2​ is 1 on a smaller open set in the southern hemisphere and smoothly drops to 0 at the equator. The sum ρ1​+ ρ2​ is always 1 on the equator: A partition of unity on a manifold M is a family of smooth functions {ρi​} such that the sum of all functions is identically 1 (∑i​ρi​=1) and the support of each function is contained within a given open cover. It’s a tool for smoothly piecing together local information to get global information. Visual Intuition: Consider a sphere S2 and an open cover consisting of two open hemispheres. We can construct a partition of unity with two functions, ρ1​ and ρ2​. Function ρ1​ is 1 on a smaller open set in the northern hemisphere and smoothly drops to 0 at the equator. Function ρ2​ is 1 on a smaller open set in the southern hemisphere and smoothly drops to 0 at the equator. The sum ρ1​+ ρ2​ is always 1 on the equator. . This lets us smoothly glue a local function on the northern hemisphere and a local function on the southern hemisphere to create a global function on the sphere. */
/* Partition of unity, sheaf can be thought of as a collection of local data (e.g., functions, sections) on a space. A partition of unity allows us to build a complex of sheaves that "resolves" the sheaf, meaning it captures its structure:  In homological algebra, a partition of unity for a sheaf F on a space X is a way to construct an acyclic resolution. An acyclic resolution is a complex of sheaves whose higher cohomology groups are zero. Visual Intuition: A sheaf can be thought of as a collection of local data (e.g., functions, sections) on a space. A partition of unity allows us to build a complex of sheaves that "resolves" the sheaf, meaning it captures its structure. For instance, on a manifold, we can construct a fine resolution of the sheaf of smooth functions. This fine resolution is acyclic because we can "smoothly" glue local sections using the partition of unity, preventing the formation of "holes" in the complex. */
/* Partition of unity, group algebra Fp​[G] of a finite group G over a field Fp​. We can find orthogonal idempotents that act as a "partition of unity." These idempotents decompose the group algebra into a direct sum of indecomposable modules:  In modular representation theory, a partition of unity can be seen as a set of orthogonal idempotents that sum to the identity in a group algebra. These idempotents decompose the group algebra into a direct sum of modules. Visual Intuition: Consider the group algebra Fp​[G] of a finite group G over a field Fp​. We can find orthogonal idempotents that act as a "partition of unity." These idempotents decompose the group algebra into a direct sum of indecomposable modules. Geometrically, this is like breaking down a complicated object into its fundamental, non-decomposable building blocks. */
/* Partition of unity, ring Z6​, orthogonal idempotents e1​=3 and e2​=4 (since 3^2 = 9 ≡ 3 mod 6 and 4^2=16 ≡ 4 mod 6, and 3⋅4 = 12 ≡ 0 mod 6). Their sum is 3+4=7 ≡ 1 mod 6. The ring Z6​ is the direct product of Z2​ and Z3​. This is a "partition" of the ring into two "independent" components:  In commutative algebra, a partition of unity is a set of orthogonal idempotents {e1​,…,en​} in a ring R such that ei​ej​=0for i not equal to j and sum of e_i​=1. These idempotents decompose the ring as a direct product of subrings. Consider ring Z6​, orthogonal idempotents e1​=3 and e2​=4 (since 3^2 = 9 ≡ 3 mod 6 and 4^2=16 ≡ 4 mod 6, and 3⋅4 = 12 ≡ 0 mod 6). Their sum is 3+4=7 ≡ 1 mod 6. The ring Z6​ is the direct product of Z2​ and Z3​. This is a "partition" of the ring into two "independent" components. */
/* Partition of unity, coprime decomposition to the Chinese Remainder Theorem states that Zmn​ is isomorphic to Zm​×Zn​ when m and n are coprime. This is a decomposition of the ring into two "independent" parts:  In arithmetic number theory, a partition of unity can be seen as a decomposition of the ring of integers Z into a direct product of rings Zp​, using the Chinese Remainder Theorem. Visual Intuition: Consider the ring Z. The Chinese Remainder Theorem states that Zmn​ is isomorphic Zm​×Zn​ when m and n are coprime. This is a decomposition of the ring into two "independent" parts. This is a number-theoretic analog of a "partition of unity" in the sense that we are "decomposing" the ring into a direct product of its constituent "factors." */
