/* Abelian variety, projective variety that is a group:  one can see this via the chord tangent process on x^3 + y^3 = 9 since a + b + c = 0, a, b, c collinear. Not birational to the affine line A^1 since it has genus 1 not 0 as a Riemann surface. Projective coordinates (x, y, z) mod lambda or x^3 + y^3 = 9z^3, z is not 1. Associativity is hard to prove directly, follows from sum of a_1 to a_n = sum of b_1 to b_n if and only if there is a rational function with zeroes at 'a's, poles at 'b's. */
/* Abelian varieties, varieties that are abelian contrasting symplectic groups: a proof strategy for complex numbers, any map from projective variety to the complex numbers is constant by the maximum principle, so the adjoint map to the automorphism group of tangent space of origin is 0. Abelian linear groups are not abelian, this is old names for symplectic group, an affine algebraic group. */
/* Enumerative geometry, surprising answers with scheme theory:  27 lines on cubic surface is a classical example, example w^3 + x^3 + y^3 + z^3 = 0 in projective spaceP^3, typical line is (1, -1, t, -t), the order is 3^3 * 4! (exercising), surprisingly when this is thought of a group, there are 27 images under this group, acted on permutation group. */
/* Hausdorff condition, affine line over field is not Hausdorff:  affine line over field k is not Hausdorff, counterexample, consider set of generic point in V(I) for variety of ideal I. If this is the case, then the ideal I is in the zero ideal, the algebraic set cut out is the affine line, therefore the closure of the generic point is the whole affine line, this means there exists a nonclosed point {0}. The topological space is not Hausdorff, but the affine line over k is separated as a scheme. */
/* Stalk, germ of section:  Germ is equivalence class of section on open neighbourhood, same section if agree on smaller, stalk of sheaf is set of all germs */
/* Stalk, local data:  captures local data */
/* Stalk, colimit of sections over all open neighbourhoods:  formalises closer and closer to the point, related to germs equivalence class if agree on smaller neighbourhood */
/* Stalk, extension of section:  set of all possible ways to germ-wise extend a section, recall that the stalk is the filtered colimit to some point. */
/* Stalk, colimit algebra:  colimiting object of directed system of restriction maps on the sheaf sections */
/* Stalk, functorial construction:  Functor from sheaves to category of algebraic objects (etale space, use sets, but generalises to groups and rings). Maps a sheaf to collection of stalks */
/* Stalk, homomorphism of sections over neighbourhood to stalk:  map from section over neighbourhood of p to the stalk is universal homomorphism respecting restriction maps */
/* Stalk, local rings:  sheaf of rings on a scheme, stalk at point p is local ring with a unique maximal ideal */
/* Stalk, adjoint to constant sheaf functor. Recall that you can first look at a section from the constant sheaf to the codomain to turn it into a stalk functor into a representable functor:  constant sheaf functor is left adjoint to stalk functor, see example of stalk of sheaf F on local U is stalk morphism on U as constant sheaf to sheaf F. Recall that you can first look at a section from the constant sheaf to the codomain to turn it into a representable functor of the stalk. */
/* Stalk, geometric point as a ringed space:  ringed space, whose ring is a field */
/* Stalk, irreducible components or points:  stalk is field, point is closed (maximal ideal), stalk is integral domain, irreducible component (prime ideal) */
/* Stalk, local property on manifold:  stalk of sheaf of smooth function, germs of smooth function */
/* Stalk, pointwise sheaf:  Sheaf is completely determined by its stalks and restriction maps between sections */
/* Stalk, gluing:  compatability of sections checked on level of stalks */
/* Stalk, filtered colimit:  filtered colimit over the category of open neighbourhood of a point */
/* Stalk, fibre of point of cospan:  Fibre of cospan, so it is a pullback */
/* Stalk, localised object:  localisation of sheaf with respect to multiplicative set of non-vanishing functions at a point */
/* Stalk, representation of presheaf under sheafification:  stalk, sheafification of presheaf at a point p is identical to the stalk of the original presheaf at p. Sheafification only changes global glueing. */
/* Section, right inverse:  Right inverse of a map f * s is identity on codomain, s is section */
/* Section, choice function:  Choose single element from each preimage set by having the section be applied first */
/* Section, splits a surjection:  section for surjection means codomain can be embedded back into the domain. */
/* Section, embedding:  embedding of codomain in domain. Codomain is now subobject of domain */
/* Section, continuous maps for each point in fibre to base space (global slice):  section is continuous map that assigns a point in the fibre to each point in the base space (codomain) a.k.a fibre bundle */
/* Section, direct sum:  Category of modules, map has section, means can be composed as direct sum domain M is isomorphic to ker(f) ++ im(s), ++ direct sum, splitting lemma */
/* Section, basis of free modules:  surjective module homomorphism from free module F to module M, section is choice of basis in codomain M that can be lifted to generators for F */
/* Section, representation of coset:  f: G -> H, H is coset space, section s: H to G, choses unique element from each coset of the kernel in the domain group G */
/* Section, projective object:  module P is projective if every surjection on module P has a section */
/* Section, homomorphism:  section for homomorphism means it has trivial cokernel, domain splits into direct sum */
/* Section, inverses to compare section versus retractions:  section is a map that has a right inverse retraction, map that has left inverse Context: model categories */
/* Section, short exact sequence: 0 -> A -> B -> C -> 0, splits if B -> C has a section */
/* Section, morphism in slice category (see also functor of point construction with base scheme [or base category of Set to get scheme maps], here you have a base category):  Section of f from X to Y is object in slice category over Y */
/* Section, global section of a sheaf:  Section of entire space is global section of the sheaf */
/* Section, sheaf morphism when considering section of sheaf F over U, and constant sheaf of U, to make this representable:  Section of a sheaf F over open U is sheaf morphism from constant sheaf of U to sheaf F, representable, recall that it is the step before thinking about the domain (which in this case it is the sheaf F over U) */
/* Section, projective variety:  section of line bundles on projective variety, map from variety into projective space */
/* Section, vector field as sections of the tangent bundle:  Vector field is section of tangent bundle (imagine fibres extending out of a tangent line), assigned to each tangent vector of manifold in a smooth way */
/* Germ, equivalence class:  germ of a function at a point p is an equivalence class of functions, where the equivalence relation is defined by f is equivalent to g if there exists an open neighborhood U of p on which f and g are equal. */
/* Germ, stalk of presheaf:  collection of all germs of a presheaf F at a point p forms an algebraic object called a stalk, denoted Fp​. This is the direct categorical definition. */
/* Germ, direct limit:  stalk (as collection of all germs) of a presheaf at a point p is the direct limit of the values of the presheaf on all open neighborhoods of p. The direct limit formalism gives a precise categorical construction of the stalk. */
/* Germ, local ring:  local ring at a point of a scheme is the ring of germs of regular functions at that point. This is a fundamental link between germs and local rings. */
/* Germ, sheaf of rings:  local ring at a point p of a scheme is the stalk of the sheaf of rings OX​ at p, where the "functions" are regular functions. */
/* Germ, function on neighbourhood:  function defined on an "infinitesimal neighborhood" of a point, a concept made precise by the direct limit. */
/* Germ, of morphisms:  germs of morphisms between topological spaces are equivalence classes of continuous maps that agree on a neighborhood of a point. */
/* Germ, algebraic:  germ can be defined in a purely algebraic way as an element of a local ring, without explicit reference to topological neighborhoods. */
/* Germ, local property:  germ embodies the local property of an object or function at a point. It discards all global information and focuses solely on the behavior near a single point. */
/* Germ, stalk of a complex:  stalk generalizes to complexes of sheaves, where the stalk of a complex is a complex of modules. */
/* Germ, homological stalk:  suppose you have a complex of sheaves F^, its homological stalk at a point p is the stalk of the homology sheaf, denoted Hq​(F^)p​. */
/* Germ, stalks as derived functor of the global sections functor:  stalk (recall that stalks are collections of germs) functor, which takes a sheaf to its stalk, is the derived functor of the global section functor. */
/* Germ, etale sheaf:  étale cohomology, the concept of a stalk is generalized to an étale stalk, where the neighborhoods are not just Zariski open sets, but are more general étale neighborhoods. */
/* Germ, spectra of a ring spectrum:  "local ring" at a prime of a ring spectrum is defined using a homotopical localization process, where a germ of a function corresponds to an element in the localized ring spectrum. */
/* Sheaf, generalises continuity:  generalises continuity by ensuring local data can be smoothly and consistently patched together with no issues */
/* Sheaf, generalises continuous functions:  Instead of assigning a value, assign a set of sections to each open set. */
/* Sheaf, abstraction of vector bundles:  Local trivialisations are sections, transition maps are restrictions */
/* Sheaf, as a functor:  From category of open sets of a topological space, inclusions as morphisms to other category */
/* Sheaf, etale space, etale looks like locally:  Sheaf isa sheaf of sections of an etale space, etale space locally looks like a product of open set and discrete space OR local homeomorphism */
/* Sheaf, model of constructive logic:  Proposition is considered true if it has a proof consistent across all local domains */
/* Generic point, affine line A_k^1​ as a one-dimensional space. The closed points correspond to the roots of the polynomials. The generic point is a special, non-closed point that "sees" all the other points. It can be visualized as a "shadow" of all the other points. It is not a specific point, but a concept that captures the "generic" behavior of the scheme:  In algebraic geometry, a generic point of an irreducible scheme X is a point whose closure is all of X. For an affine scheme X=Spec(R), the generic point corresponds to the zero ideal (the set of all functions that are zero everywhere on the scheme). This point "sees" all the other points in the scheme. For example, the affine line A_k^1​ has a generic point corresponding to the zero ideal in the polynomial ring k[x]. */
/* Generic point, ring of polynomials k[x] as a geometric object. The prime ideals are the "points" of the object. The generic point is a special point that is "contained" in every other point. It is a "shadow" of all the other points:  In commutative algebra, a generic point of a variety corresponds to the zero ideal in the ring of functions on the variety. This point is a prime ideal that is contained in every other prime ideal. It is the minimal prime ideal of the ring. For example, the ring of polynomials k[x] has a generic point corresponding to the zero ideal. */
/* Generic point, the number field Q as a single point. The generic point is this point. The prime ideals are the "closed" points. The generic point is the "unclosed" point that sees all the other points:  In number theory, the generic point of the spectrum of the ring of integers of a number field is the zero ideal. This point corresponds to the field itself. It is the "generic" point of the number field. */
/* Generic point, category as a collection of objects with arrows between them. A generic object is an object that has an arrow to every other object. It is a "universal" object:  In homological algebra, the concept of a generic point can be generalized to the concept of a "generic object" in a category. A generic object is an object that is "contained" in every other object. */
/* Pushforward, vector on the surface of a sphere. If we have a map from the sphere to a plane (e.g., a map projection), the pushforward is how that vector "stretches" or "squashes" as it's projected onto the plane. The direction and magnitude of the projected vector are the pushforward:  in differential geometry, the pushforward of a tangent vector is the map induced by a smooth function between two manifolds. For a smooth map f: M to N, the pushforward f∗​ maps a tangent vector at a point p in M to a tangent vector at the image point f(p) in N. */
/* Pushfoward, group of rotations of a square. We can represent these rotations as 2 by 2 matrices. If we rotate our coordinate system, the matrices change. The pushforward is the new set of matrices that describes the same rotations in the new coordinate system:  In group theory, the pushforward can be seen as the change of basis for a representation. If we have a representation p: G to GL(V), and we choose a new basis for V using a change-of-basis matrix T, the new representation is the pushforward of p by T. */
/* Pushfoward, map from a torus to a sphere. The fundamental group of the torus is Z ++ Z, and the fundamental group of the sphere is trivial. The pushforward map sends any loop on the torus to a contractible loop on the sphere. The pushforward tells you how the "holes" of one space get mapped to the "holes" of another:  In homotopy theory, a continuous map f: X to Y induces a pushforward map f∗​: pi_n​(X) to  pi_n​(Y) on the homotopy groups. This map sends an n-sphere in X to an n-sphere in Y. */
/* Pushfoward, map from a solid torus to a solid cylinder. The pushforward maps the cycles of the torus (e.g., the longitude and meridian) to cycles of the cylinder. The homology of the torus is non-trivial, while the homology of the cylinder is non-trivial for loops, but trivial for 2-cycles. The pushforward tells you how the "holes" of one object are mapped to the "holes" of another:  In homological algebra, a continuous map f:X→Y induces a pushforward map f∗​:H_n​(X,A) to H_n​(Y,f(A)) on homology groups. This is a covariant functor. */
/* Pushfoward, module is like a vector space over a ring. The pushforward is the new vector space we get when we extend the ring. For example, extending the scalars from the integers Z to the rational numbers Q. We are "pushing forward" the integer vectors to become rational vectors:  In non-commutative ring theory, the pushforward can be seen as the induction of a module. If we have a module M over a ring R and a ring homomorphism p: R to S, the pushforward is the new module S tensor_R ​M over the ring S. */
/* Pushforward, sheaf is a way of assigning data to open sets of a space. The pushforward is how that data is "pushed" from one space to another. For example, a map from a sphere to a point collapses all the data on the sphere to a single point:  In algebraic geometry, a map of schemes f: X to Y induces a pushforward functor f∗​: Sh(X) to Sh(Y) from the category of sheaves on X to the category of sheaves on Y. It's a way of transporting sheaves along a map. */
/* Pushforward, ideal can be thought of as a collection of lattice points. The pushforward is the new collection of lattice points that we get by extending the number field. The pushforward "spreads out" the ideal to a larger field:  In arithmetic number theory, the pushforward of an ideal from a number field K to a number field L (where K is in L) is the ideal of L generated by the ideal of K. */
/* Pushforward, module for a group is like a vector space with a group action. The pushforward is the new vector space we get by "blowing up" the representation to a larger group:  In modular representation theory, the pushforward is the induction of a module. If H is a subgroup of G and M is a module for F_p​[H], the pushforward is the induced module Ind_H^ G ​M = F_p​[G] tensor_{F_p​[H]} ​M. */
/* Pushforward, coherent sheaf can be thought of as a family of vector spaces over a variety. The pushforward is the new family of vector spaces we get when we "push" the variety onto a new space:  In algebraic geometry, a map of schemes induces a pushforward functor for coherent sheaves. This is a very powerful tool that allows us to move geometric objects from one space to another. */
/* Pushforward, vector field on a sphere. The pushforward is the new vector field on a plane that you get by projecting the sphere onto the plane. The vectors are "pushed" to new locations:  In differential geometry, the pushforward of a vector field X on a manifold M to a vector field Y on a manifold N is defined such that it satisfies a specific commutativity property with the map f: M to N. */
/* Presheaf, visual intuition, space with open patches on it:  for a space, say a sphere, with open patches on it. A presheaf assigns a set of "functions" to each patch. For example, for a presheaf of smooth functions, each patch has all the smooth functions defined on it. As you move from a larger patch to a smaller one inside it, you just "restrict" your functions to the smaller patch. */
/* Scheme, ring spectrum:  irreducibles of an affine scheme (but in this case points) of Spec(R) are the prime ideals of R, and the topology, known as the Zariski topology, is defined by the closed sets corresponding to the vanishing loci of ideals. */
/* Scheme, locally ringed space:  topological space equipped with a sheaf of rings, called the structure sheaf, such that the stalks are local rings. This structure captures the local properties of the geometric object. */
/* Scheme, gluing:  gluing process is defined by an isomorphism of locally ringed spaces over the intersections of the open sets. */
/* Scheme, ring of regular functions:  ring of regular functions on an affine scheme Spec(R) is precisely the ring R itself. This establishes a deep correspondence between rings and affine schemes. */
/* Scheme, generic point:  irreducible closed subset of a scheme has a unique generic point, which is the point whose closure is that entire subset. This concept generalizes the notion of a generic point of an irreducible variety. */
/* Scheme, reduced:  reduced if its structure sheaf has no nilpotent elements in its stalks. Geometrically, this means the scheme has no "infinitesimal fuzziness." */
/* Scheme, projective:  projective scheme is a scheme that can be embedded in a projective space, which is constructed from a graded polynomial ring. These are the algebraic counterparts of projective varieties. */
/* Scheme, motivation:  study sets of solutions to polynomial equations over any commutative ring, not just algebraically closed fields. This allows algebraic geometry to be applied to number theory. */
/* Scheme, category of schemes:  morphisms are maps of locally ringed spaces that are compatible with the ring structure. */
/* Schemes, derived:  derived algebraic geometry that generalizes a scheme by allowing its structure sheaf to be a sheaf of differential graded algebras or commutative ring spectra. This framework is crucial for studying derived moduli spaces. */
/* Schemes, stacks:  scheme, which allows for families of objects with symmetries. A scheme is a special case of a stack. */
/* Scheme, local ring as functors:  local rings of a scheme can be defined as a functor on the category of affine schemes, which provides a categorical view of localization. */
/* Scheme, etale sheaves:  étale cohomology, schemes are studied using sheaves on the étale site, which is a more refined topology than the Zariski topology. This is key for studying arithmetic properties. */
/* Scheme, ring spectra in homotopy theory:  concept of the prime spectrum Spec(R) is generalized to the spectrum of a ring spectrum, which is a "space" that reflects the homotopical properties of the ring. */
/* Scheme, homological:  homological scheme is an object in homological algebra whose structure is given by a complex of modules. This is a first step towards derived schemes. */
/* Schemes, A-infinity spaces:  generalized to objects in the category of A_infinity-spaces, which are a kind of "homotopy-coherent" ring. */
/* Schemes, functor of points:  functor from the opposite category of affine schemes to the category of sets taking affine schemes to set of scheme maps */
/* Schemes, formal scheme:  scheme that has been "infinitesimally thickened." This concept is used in formal geometry to study local properties of schemes near a point or a subscheme. */
/* Generic point, dense point:  point p in a topological space X is a generic point if its closure, {p}​, is the entire space X. */
/* Generic point, point of irreducible algebraic variety:  irreducible algebraic variety has a unique generic point. This point is the set of all polynomials that vanish on the variety. */
/* Generic point, prime ideal:  algebraic counterpart of a generic point of an irreducible affine variety is a prime ideal of its coordinate ring. A prime ideal p is a generic point of the irreducible closed set V(p). */
/* Generic point, minimal prime ideal:  prime ideal is a generic point of its closure if and only if it is a minimal prime ideal. */
/* Generic point, context of spectrum of a ring:  context of the spectrum of a ring Spec(R), the points are the prime ideals. The generic point of an irreducible component is the prime ideal that corresponds to it. */
/* Generic point, generic property:  property is true "at the generic point" if it holds for the entire irreducible variety except for a lower-dimensional subset. This is a powerful way to make statements about the "general" case. */
/* Generic point, generic filter:  generic point of an algebraic variety corresponds to a generic filter on the lattice of ideals of the coordinate ring. */
/* Generic point, dimension zero:  dimension zero in the Zariski topology, meaning it does not have any proper non-empty closed subsets. */
/* Generic point, stack:  generic point is a point that is dense in a stack. The concept is more complex as it involves the presence of automorphisms at the point. */
/* Generic point, derived:  derived generic point is a point that is dense in a derived scheme. This concept is richer as it captures homotopical information. */
/* Generic point, equivalent in localisation:  two objects are equivalent "at the generic point" if they are equivalent in the localization of the category at that point. */
/* Generic point, prime spectrum in spectral algebraic geometry:  the points of the prime spectrum of a ring spectrum are the prime ideals. The generic points of the irreducible components are the minimal prime ideals. */
/* Integral scheme, reduced and irreducible:  scheme is integral if and only if its underlying topological space is irreducible and its structure sheaf has no non-zero nilpotent elements in its stalks. */
/* Integral scheme, definition for affine schemes via integral domain:  affine scheme Spec(R) is integral if and only if the ring R is an integral domain. This is the most fundamental algebraic definition. */
/* Integral scheme, generic point:  unique generic point, which is a point whose closure is the entire scheme. This point corresponds to the zero ideal of the coordinate ring. */
/* Integral scheme, no infinitesimal fuzziness, single piece:  geometrically "clean." The "reduced" property means it has no infinitesimal fuzziness or non-trivial higher-order behavior at any point. The "irreducible" property means it is a single piece with no "cracks." */
/* Integral scheme, subscheme of a variety:  irreducible algebraic variety is an integral scheme. This is how the concept generalizes to modern algebraic geometry. */
/* Integral scheme, function ring:  ring of regular functions on a connected component of an integral scheme is an integral domain. */
/* Integral scheme, morphisms to affine line:  set of morphisms from an integral scheme to the affine line A1 can be identified with the ring of regular functions on the scheme, which is an integral domain. */
/* Integral scheme, dimensions:  non-empty affine integral scheme has a well-defined dimension, which is the Krull dimension of its coordinate ring. */
/* Integral scheme, reduced means nilradical vanishing:  scheme is reduced if and only if its nilradical is zero. The nilradical is the ideal of all nilpotent elements. */
/* Integral scheme, intersection of components:  integral scheme cannot be written as the union of two or more proper closed subschemes. Geometrically, it means it is not a composite object. */
/* Integral scheme, derived integral scheme:  integral scheme is a scheme with a structure sheaf of derived algebras that is "homotopically integral." This means the derived ring has no non-trivial derived nilpotents. */
/* Integral scheme, homotopically reduced:  homotopically reduced if its structure sheaf has no homotopical nilpotents. These are elements that are "eventually zero" in a derived sense. */
/* Integral scheme, homotopically irreducible:  derived scheme is homotopically irreducible if its prime spectrum is a single connected component in a homotopical sense. */
/* Integral scheme, prime spectrum of integral ring spectrum:  integral scheme generalizes to the prime spectrum of an integral ring spectrum, which is a ring spectrum whose prime spectrum is irreducible. */
/* Integral scheme, Homological duality:  important in homological algebra because they admit strong homological properties, such as being Gorenstein or Cohen-Macaulay, which are properties of their local rings. */
/* Integral scheme, generic flatness theorem:  generic point of an integral scheme is used to formulate the generic flatness theorem, which states that a module over a Noetherian integral domain is locally free on a dense open set. */
/* Integral scheme, function field:  field of fractions of its coordinate ring. This is a fundamental invariant that captures the generic properties of the scheme. */
/* Normal scheme, normal Noetherian integral domains:  Noetherian integral domain R is normal if it is integrally closed in its field of fractions. This means any element of the field of fractions that is a root of a monic polynomial with coefficients in R must already be in R. */
/* Normal scheme, integrally closed where concept of being normal is a refinement of integrality:  ring is integrally closed if it contains all the "algebraic integers" from its field of fractions. */
/* Normal scheme, definition of local domains:  scheme X is normal if all its local rings are normal domains. This means the scheme is "normal at every point." */
/* Normal schemes, regular local ring and normal rings:  regular local rings is always a normal ring. Geometrically, a smooth scheme is always normal. */
/* Normal scheme, unmixed dimension of irreducible components:  all their irreducible components have the same dimension. */
/* Normal scheme, Krull's criterion (with two conditions) on Noetherian integral domains:  Noetherian integral domain is normal if and only if it satisfies two conditions: it is a Krull domain and it is a unique factorization domain (UFD). */
/* Normal scheme, singularity analogy:  normal singularity is a singularity that is "as mild as possible" in the sense that it has no "infinitesimal" or "sub-dimensional" components that are not accounted for. */
/* Normal scheme, definition commutative factorial ring or unique factorisation domain:  commutative ring is a factorial ring, or a unique factorization domain (UFD), if every non-zero, non-unit element can be written as a product of prime elements, and this factorization is unique up to order and units. */
/* Normal scheme, prime means irreducible in factorial ring:  factorial ring, every prime element is irreducible. This simplifies the study of factorization. */
/* Normal scheme, regular implies factorial links smoothness to unique factorization:  regular local ring is a unique factorisation domain / factorial ring. This is a fundamental result that links smoothness to unique factorization. */
/* Normal scheme, normality as no bumps where cone example as not normal:  normal variety or scheme has no "bumps" or "creases" of codimension one. For example, a cone is not normal at its vertex, as it is singular there. */
/* Normal scheme, factoriality as algebraic and geometric (geometric visualising unique decomposition):  factoriality is a purely algebraic property that corresponds to a very strong geometric property: the unique decomposition of functions into prime functions. */
/* Normal scheme, codimension 1 condition of Noetherian domains:  Noetherian domain is normal if and only if it satisfies a few conditions on its prime ideals of height one, which are analogous to subvarieties of codimension one. */
/* Normal scheme, normality is a local property on the level of stalks of a scheme:  scheme is normal if and only if all its stalks are normal domains. This means we can check for normality "locally." */
/* Normal scheme, uniqueness of irreducible components:  factorial ring corresponds to a geometric object where functions have a unique decomposition into irreducible components. */
/* Normal scheme, smoothness/regular as stronger than normality and factoriality:  normality and factoriality are consequences of a scheme being smooth (or regular). Normality is a weaker condition than regularity, and factoriality is a weaker condition than regularity. */
/* Normal scheme, Cohen-Macaulay:  Normal and factorial rings are a special case of Cohen-Macaulay rings, which have nice homological properties. */
/* Morphism of schemes, continuous map with ring homomorphism: a morphism of a schemes, it is a map of topological spaces and map of sheaves of rings */
/* Morphism of schemes, collection of locally affine morphisms for each open subset in codomain: a collection of locally affine morphisms of affine schemes for each open subset in codomain that are glued together */
/* Morphism of schemes, contravariant functor from category of rings:  contravariant functor from category of rings to the category of affine schemes, maps of affine schemes Spec(B) to Spec(A) corresponds to ring homomorphism A to B. */
/* Morphism of schemes, functor of points relative to a base scheme: a map of morphism of schemes from X to Y can be understood as how it acts on all possible morphisms from other schemes T to X and Y */
/* Morphism of schemes, closed immersion: a closed immersion is a morphism that embeds a scheme as a closed subscheme, map from scheme X to scheme Y that is a homeomorphism onto a closed subset of Y, and induces a surjetive map on the sheaves */
/* Morphism of schemes, open immersion:  morphism that embeds a scheme as an open subscheme. It is a homeomorphism onto an open subset of the target scheme. This allows us to think of affine schemes as the basic building blocks that are glued together to form a general scheme. */
/* Morphism of schemes, flat morphisms:  induced map on local rings makes the target a flat module over the source. Geometrically, this means the fibers of the morphism are "well-behaved" and don't experience "unexpected jumps" in dimension. Think of a family of schemes parameterized by Y where the fibers have a consistent dimension. */
/* Morphism of schemes, smooth morphisms:  smooth morphism is a flat morphism whose fibers are "geometrically nice" or smooth manifolds. This is the algebraic counterpart of a submersion in differential geometry. A smooth morphism has no singular points in its fibers. */
/* Morphism of schemes, etale morphisms:  flat, unramified morphism. Geometrically, it is an algebraic analog of a local isomorphism in topology. It preserves the local ring structure and is key to defining étale cohomology for schemes. */
/* Morphism of schemes, finite morphisms:  finite morphism if it is affine and the induced map on rings makes the source a finitely generated module over the target. This is the algebraic analog of a finite covering map in topology. */
/* Morphism of schemes, proper morphisms:  proper morphism is the algebraic counterpart of a compact map in topology. A morphism is proper if it is separated, of finite type, and universally closed. */
/* Morphism of schemes, chain maps:  chain map between chain complexes. A chain map is a sequence of module homomorphisms that commutes with the differentials. This preserves the homological structure of the complexes. */
/* Morphism of schemes, derived morphisms: a derived morphism between derived schemes is a morphism of the corresponding ring spectra. These maps are defined up to homotopy and are much more flexible than classical morphisms. */
/* Morphism of schemes, morphism of stacks:  stacks is a more general type of morphism that allows for maps that have nontrivial automorphisms. This is a key concept in moduli theory, where the objects can have symmetries. */
/* Morphism of schemes, morphism of ring spectra:  morphism of ring spectra is a map that preserves the multiplicative and additive structure up to homotopy. This is a powerful tool for studying higher algebraic structures. */
/* Moduli space, space of geometric objects:  geometric space whose points are in one-to-one correspondence with isomorphism classes of some type of geometric or algebraic object. For example, a point in the moduli space of ellipses represents a unique ellipse. */
/* Moduli space, moduli problems:  moduli problem is the task of classifying a collection of objects. For example, the problem of classifying all elliptic curves is a moduli problem. The solution is the moduli space. */
/* Moduli space, fine moduli space:  moduli space that has a "universal object." This is a single object that lives over the moduli space itself, and any other object in the collection can be obtained by pulling back this universal object. This is a very strong, and rare, condition. */
/* Moduli space, coarse moduli space:  course moduli space is a moduli space that classifies the objects set-theoretically but doesn't have a universal object. It's a "near perfect" catalog, but it may not have a single master object from which all others can be built. */
/* Moduli space, orbit space:  constructed as a quotient space or an orbit space of a larger space by a group action. Think of the space of all possible shapes, and you "mod out" by a group of transformations (like rotations and translations) that leave the shape unchanged. */
/* Moduli space, stable object:  moduli spaces often classify "stable" objects. Stability is a technical condition that ensures the objects are well-behaved and have a finite automorphism group. This helps in forming a geometric quotient. */
/* Moduli space, moduli stack:  moduli stack is a generalization of a moduli space that accounts for objects with non-trivial automorphisms. It's like a moduli space, but with "extra data" at each point that tells you about the symmetries of the object. */
/* Moduli space, catalogue of symmetry data:  catalog of shapes, but on each page, there is a small diagram showing the symmetries of that particular shape. That's a moduli stack. The "stackiness" is that extra data. */
/* Moduli space, fuzzy catalogue for derived moduli space:  derived moduli space is like a catalog where the pages are "fuzzy" or "blurry." Each point in the catalog is not a single, crisp object but a collection of objects that are equivalent up to a homotopy. */
/* Moduli space, perfect obstruction theory:  geometry of a derived moduli space is governed by a perfect obstruction theory, which is a complex that measures the "obstructions" to deforming an object. The existence of a perfect obstruction theory allows one to compute the virtual fundamental class of the moduli space. */
/* Moduli space, homological:  homological algebra, a moduli space can be defined as the classifying space for certain types of chain complexes. The points of the moduli space are the isomorphism classes of these complexes. */
/* Moduli space, categorical moduli space:  categorical moduli space is a solution to a moduli problem in the context of category theory. The moduli space is itself a category whose objects are the objects being classified. */
/* Moduli space, D-modules:  theory of D-modules, which are modules over the ring of differential operators. */
/* Cotangent space, rulers of the tangent vector:  cotangent space Tp∗​M at a point p on a smooth manifold M is the dual vector space of the tangent space Tp​M. Visual Intuition: If the tangent space is the space of all possible directions (velocity vectors) you can go in, the cotangent space is the space of all possible linear measurements you can make on those directions. Think of it as a set of "rulers" that can measure the length of a tangent vector. */
/* Cotangent space, directions and measurements:  tangent space captures the "first-order" directions, while the cotangent space captures the "first-order" measurements. They are dual concepts. Visual Intuition: A tangent vector is a direction, like a compass arrow. A cotangent vector is a way of measuring a direction, like a ruler that measures distance along a compass arrow. */
/* Cotangent space, obstruction theory with deformation:  cotangent space plays a key role in obstruction theory, where cotangent vectors correspond to first-order deformations. Higher-order obstructions to deformations lie in higher cohomology groups. Visual Intuition: The cotangent space is the "space of constraints," and obstructions are the things that prevent you from satisfying those constraints. */
/* Tangent space, smooth surface:  Imagine a smooth surface; the tangent space at a point is a flat plane that just touches the surface at that point, representing all the directions one could move in instantaneously. */
/* Tangent space, derivations:  the tangent space at a point p on a variety is defined as the space of derivations at that point. A derivation is a linear map D: O_{X,p}​ to k that satisfies the Leibniz rule, where O_{X,p}​ is the local ring at p and k is the residue field. Visual Intuition: A derivation measures the "rate of change" of functions at a point, which is exactly what a tangent vector does. */
/* Tangent space, Zariski tangent space:  Zariski tangent space Tp​X of a scheme X at a point p is the dual of the vector space mp​/mp2​, where mp​ is the maximal ideal of the local ring at p. Visual Intuition: mp​ represents the functions vanishing at p. mp2​ represents functions vanishing to a higher order. The quotient captures the first-order behavior, which is the linear approximation of the geometry around the point—exactly what a tangent space is. */
/* Tangent space, cotangent space:  dual vector space of the tangent space. It is the space mp​/mp2​. Visual Intuition: If the tangent space is the space of all possible directions, the cotangent space is the space of all possible "infinitesimal measurement tools" at that point. */
/* Tangent space, A_infty algebra:  tangent space at a point is not just a vector space but a more complex object that captures higher-order information. The tangent space is a differential graded vector space, reflecting the homotopical nature of the algebra. Visual Intuition: It's like a fuzzy, multi-layered version of a tangent plane, with each layer representing a different level of "infinitesimal" information. */
/* Tangent space, tangent bundle:  tangent bundle TX of a manifold X is the union of all the tangent spaces at all points, with a natural manifold structure. It's a vector bundle over the manifold. Visual Intuition: It's like a a "hairy" surface, where each hair is a tangent vector. */
/* Tangent space, cotangent bundle:  cotangent bundle is the dual vector bundle to the tangent bundle. It's the union of all the cotangent spaces. Visual Intuition: It’s the "space of all possible infinitesimal measurements" on the manifold. */
/* Tangent bundle, tangent sheaf:  tangent bundle is generalized to the tangent sheaf. It's the sheaf of derivations, which is a key object for studying the geometry of schemes. Visual Intuition: It’s a "sheaf of hairs," where the "hairs" are tangent vectors. */
/* Tangent sheaf, normal sheaf subscheme Y of a scheme X as a quotient, measuring extent of embedding:  subscheme Y of a scheme X, the normal sheaf is the quotient of the tangent sheaf of X by the tangent sheaf of Y. It measures how Y is embedded in X. Visual Intuition: It’s like the space of all directions perpendicular to a sub-manifold. */
/* Tangent sheaf, obstruction theory:  tangent space plays a key role in obstruction theory, where tangent vectors correspond to first-order deformations, and higher-order obstructions to deformations lie in higher cohomology groups. Visual Intuition: The tangent space is the "space of possibilities," and obstructions are the things that prevent you from realizing those possibilities. */
/* Tangent space, derived tangent space in derived algebraic geometry:  the tangent space at a point on a derived scheme is no longer just a vector space. It is a chain complex, which captures higher-order homotopical information. Visual Intuition: The tangent "plane" is now a "fuzzy" or "homotopically-structured" object. */
/* Tangent sheaf, tangent complex:  tangent complex is the correct categorical generalization of the tangent sheaf. It is a chain complex of sheaves that encodes the first-order information of a scheme or stack. Visual Intuition: It’s a multi-layered object that measures the "rates of change" of a scheme, where each layer is a different type of rate of change. */
/* Tangent sheaf, tangent cone at a singular point of the variety:  tangent cone at a point p of an algebraic variety is the set of all tangent lines to the variety at p. It's a cone in the tangent space. Visual Intuition: At a singular point on a variety, the tangent space is often too large. The tangent cone is the true "tangent approximation" of the variety at that point. */
/* Tangent sheaf, local ring:  local ring at a point p on a scheme contains all the information about the geometry of the scheme in an "infinitesimal" neighborhood of p. The tangent space is extracted from this local ring. Visual Intuition: The local ring is the "universe of functions" around a point, and the tangent space is the "linearization" of that universe. */
/* Ramification, prime ideals, imagine the prime ideals of Z as points on a number line. When we extend to a larger number field, this line is "unfolded" into a higher-dimensional space. The prime ideals in the larger field are also points, but some of them might "pile up" on top of the original prime ideal. In the case of Q(root 5)/Q, the prime (5) splits into (5) twice, which can be visualized as two points "collapsing" onto the original point. This is the geometric intuition of ramification:  In algebraic number theory, ramification describes the behavior of a prime ideal p in a number field K when it is extended to a larger number field L. The ideal pO_L​ factors into a product of prime ideals in the ring of integers of L. Ramification occurs when at least one of these prime factors appears with a power greater than 1. This "bunching up" or "confluence" of prime factors is a fundamental concept. For example, in the extension Q(root 5)/Q, the prime ideal (5) of Z"ramifies" as it becomes the ideal (root 5​)^2 in the ring of integers Z[1 + root(5) / 2] */
/* Ramification, domain P^1 as a sphere. The map z to z^2 wraps the sphere around itself twice. The points z=0 and z= infity are ramification points. This is where the wrapping "bunches up," and the pre-image of the image point is not a single point but a single point with multiplicity:  For a non-constant morphism of smooth curves f: X to Y, a point p in X is a ramification point if the corresponding map on local rings is not an isomorphism. This is a geometric phenomenon where the map "folds" or "pinches" the curve at a point. The degree of ramification is measured by the ramification index, which is a key invariant. For example, the map f: P^1 to P^1 given by z to z2 is ramified at the point z = 0. */
/* Ramification, real place is a point on a line. A complex place is a pair of points. The ramification of a real place into a complex one can be visualized as a single point on a line "splitting" into two points in a higher-dimensional space:  In the theory of valuations, ramification describes the behavior of a place of a number field in an extension. A place can be a prime ideal (finite place) or an embedding into the real or complex numbers (infinite place). Ramification of a finite place means the valuation of an element changes in a non-trivial way, while for infinite places it means a real place becomes a complex one. For example, in Q(root(-1))/Q, the real place of Q is ramified because it becomes a complex place. */
/* Ramification, Galois group as a group of symmetries of the extension. The decomposition group of a prime ideal is a subgroup that fixes the ideal. Ramification means that this subgroup is not trivial, so there are some "symmetries" that leave the ideal unchanged:  In a Galois extension of number fields L/K, ramification occurs when the decomposition group of a prime ideal is not trivial. This means that there are elements in the Galois group that fix the prime ideal but not the elements in its ring. This is a subtle but deep concept that links the algebraic properties of the extension to its number-theoretic properties. */
/* Ramification, imagine a sheet of paper. A branched cover is like folding the paper and then projecting it onto a line. The folds are the ramification locus, and the line they are projected onto is the branch locus. The map from the curve to the line is a branched cover that folds the curve at the points where the tangent is vertical: A branched cover is a surjective map of varieties with ramification. The set of ramification points is called the ramification locus, and its image is the branch locus. The map from a variety to its base is a local isomorphism everywhere except at the ramification locus. For example, the map from the curve y^2 = x(x−1)(x−2) to the affine line given by projection to the x-axis is a branched cover. */
/* Ramification, imagine a map from a disk to a disk. A critical point is a point where the map "flattens" or "folds" the disk. The dynamics around this point are very complex and can lead to chaotic behavior:  In dynamics, ramification occurs in complex dynamics when a map has critical points. A critical point is a point where the derivative of the map is zero. This is a point where the map "folds" or "pinches." For example, the map z to z^2 has a critical point at z=0. */
/* Ramification, canonical divisor is a geometric object that is a "dual" to the tangent bundle. It is a line bundle that is related to the ramification of the map:  The canonical divisor of a curve is a divisor that is related to the ramification of the curve. The degree of the canonical divisor is related to the genus of the curve and the ramification of the map. */
/* Ramification, Hilbert symbol is a "map" that measures the ramification. It is a way of "quantifying" the ramification:  The Hilbert symbol is a symbol that measures the ramification of a number field extension. The Hilbert symbol is a key tool in class field theory. */
/* Ramification, Serre duality is a "duality" between two geometric objects. The ramification of the map is a key ingredient in this duality:  The concept of ramification is used to formulate Serre duality, which is a duality theorem for coherent sheaves on a scheme. The duality is between the cohomology of a sheaf and the cohomology of its dual. */
/* Ramification, covering space is a "bundle" of spaces. A ramified covering space is a covering space that "folds" or "pinches" at some points: A ramified covering space is a generalization of a covering space. A covering space has the property that the fibers are discrete sets. A ramified covering space has the property that the fibers can have "ramification." */
/* Ramification, moduli space of curves is a geometric object. The ramification of a family of curves is a phenomenon that occurs when the fibers of the family have "non-trivial" automorphisms:  The concept of ramification is used to study the moduli space of curves. The moduli space is a geometric object that classifies curves. The ramification of a family of curves is a phenomenon that occurs when the fibers of the family have "non-trivial" automorphisms. */
/* Functor of points, imagine the affine line A1 as a set of points. The functor of points view says, don't look at the points, look at all the maps into the line. A map from a scheme T to A1 is just a function on T. The functor of points for A1 is the rule that says, for any ring R, give me the set of all polynomials with coefficients in R. This is a "generalized" way of viewing the line:  The functor of points perspective views a scheme X not as a set of points, but as a rule that assigns a set of maps to X from any other scheme T. This rule is a functor from the category of schemes to the category of sets, denoted as Hom(−,X). This allows one to study a scheme by studying its relationship with all other schemes, providing a more robust and flexible definition of a "geometric object." For example, the affine line A1 is the functor that assigns to each ring R the set of its elements. */
/* Functor of points, group Z as a number line. The functor of points view says, don't look at the numbers, look at all the maps into the number line. A map from a group H to Z is a homomorphism. This is a "generalized" way of viewing the group:  In group theory, a group G can be viewed as a functor of points. This functor assigns to each group H the set of all group homomorphisms from H to G. This generalizes the idea of a group as a set with a multiplication rule. It is a more abstract way of thinking about groups. For example, the group Z is the functor that assigns to each group H the set of its elements. */
/* Functor of points, a chain complex as a tower of vector spaces. The functor of points view says, don't look at the spaces, look at all the maps into the tower. A map from a chain complex D*​ to C*​ is a chain map. This is a "generalized" way of viewing the chain complex:  In homological algebra, a chain complex C*​ can be viewed as a functor of points. This functor assigns to each chain complex D*​ the set of all chain maps from D*​ to C*​. This generalizes the idea of a chain complex as a sequence of modules with maps between them. */
/* Functor of points, ring as a space with a non-commutative multiplication rule. The functor of points view says, don't look at the points, look at all the maps into the space. A map from a ring S to R is a ring homomorphism. This is a "generalized" way of viewing the ring:  In non-commutative ring theory, a ring R can be viewed as a functor of points. This functor assigns to each ring S the set of all ring homomorphisms from S to R. This generalizes the idea of a ring as a set with two operations. */
/* Functor of points, a group algebra as a geometric object. The functor of points view says, don't look at the points, look at all the maps into the object. A map from an algebra A to kG is an algebra homomorphism:  In modular representation theory, a group algebra kG can be viewed as a functor of points. This functor assigns to each algebra A the set of all algebra homomorphisms from A to kG. This generalizes the idea of a group algebra as a ring with an action of a group. */
/* Functor of points, sphere. The functor of points view says, don't look at the points, look at all the maps into the sphere. A map from a space Y to the sphere is a continuous map. This is a "generalized" way of viewing the sphere:  In homotopy theory, a topological space X can be viewed as a functor of points. This functor assigns to each topological space Y the set of all continuous maps from Y to X. This generalizes the idea of a topological space as a set with a topology. */
/* Functor of points, a number field as a space of numbers. The functor of points view says, don't look at the numbers, look at all the maps into the space. A map from a field L to K is a field homomorphism. This is a "generalized" way of viewing the number field:  In arithmetic number theory, a number field K can be viewed as a functor of points. This functor assigns to each field L the set of all field homomorphisms from L to K. This generalizes the idea of a number field as a field extension of Q. */
/* Functor of points, a dynamical system as a flow on a manifold. The functor of points view says, don't look at the flow, look at all the maps that preserve the flow. A map from a dynamical system (Y,g) to (X,f) is a map that commutes with the dynamics. This is a "generalized" way of viewing the dynamical system:  In dynamics, a dynamical system (X,f) can be viewed as a functor of points. This functor assigns to each dynamical system (Y,g) the set of all maps that preserve the dynamics. This generalizes the idea of a dynamical system as a space with a map. */
/* Functor of points, projective space as a space of lines through the origin. The functor of points view says, don't look at the lines, look at all the maps into the space. A map from a scheme T to Pn is a line bundle on T. This is a "generalized" way of viewing projective space:  The functor of points for projective space Pn assigns to each ring R the set of all "line bundles with a basis" on Spec(R). This is a very abstract way of defining projective space. */
/* Functor of points, derived functor is a functor that is a "homological" version of a normal functor. The functor of points view is a way of "seeing" this:  The concept of a functor of points can be used to define derived functors. A derived functor is a functor that is "homological." The functor of points view is a way of "seeing" the derived functors. */
/* Functor of points, a module as a vector space with a ring action. The functor of points view says, don't look at the points, look at all the maps into the space. A map from a module N to M is a module homomorphism:  In non-commutative ring theory, a module M can be viewed as a functor of points. This functor assigns to each module N the set of all module homomorphisms from N to M. This generalizes the idea of a module as a vector space with a ring action. */
/* Functor of points, a module as a geometric object. The functor of points view says, don't look at the points, look at all the maps into the object. A map from a module N to M is a module homomorphism:  In modular representation theory, a module M over a group algebra kG can be viewed as a functor of points. This functor assigns to each kG-module N the set of all module homomorphisms from N to M. */
/* Stack, a way into automorphims by considering the moduli space of elliptic curves. An elliptic curve has a finite number of automorphisms (usually two). If we try to build a moduli space as a scheme, the points where the elliptic curve has more automorphisms will be singularities.A stack is a way of "smoothing out" these singularities. It is a space where the points are not just elliptic curves, but elliptic curves with their group of automorphisms. For example, a point in the moduli space of elliptic curves is not just a curve, it is a curve together with its group of automorphisms, which can be thought of as a "fiber" over the point: A stack is a generalization of a scheme or manifold that allows for the presence of non-trivial automorphisms of the objects being classified. Instead of classifying objects up to isomorphism (as a moduli space does), a stack classifies objects with their full group of automorphisms. */
/* Stack, a base space, like a manifold, and over each point, we have a "fiber" which is a groupoid. The groupoid over a point is the collection of all objects that correspond to that point, and the morphisms are the isomorphisms between them. A stack is a way of "gluing" these groupoids together in a consistent way. The stack of elliptic curves is a category fibered in groupoids over a moduli space. The fiber over a point is the groupoid of elliptic curves isomorphic to that point: A stack is a category fibered in groupoids over a base category, satisfying certain descent conditions. This means that for a given object in the base category, the fiber over it is a groupoid whose objects are the objects being classified and whose morphisms are the isomorphisms between them. */
/* Stack, the category of objects as a collection of points. The isomorphisms are arrows between these points. The automorphisms are loops from a point to itself. A stack is a way of "dividing out" these loops. For example, the stack of elliptic curves is the quotient of the category of all elliptic curves by the action of the isomorphisms between them. The resulting object is a stack, which "remembers" the automorphisms of each curve: A stack can be viewed as the quotient of a category by a groupoid. For a category of objects, we can form a groupoid where the objects are the objects of the category and the morphisms are the isomorphisms between them. The stack is the "quotient" of this groupoid by the action of the automorphisms. */
/* Stack, consider the affine line A1 and the multiplicative group Gm​ acting on it by multiplication. The quotient scheme A1/Gm ​is just a point. However, the quotient stack [A1/Gm​] is a more complex object. It has a point for the origin, and a point for every other point on the line. The automorphism group of the point for the origin is the entire group Gm​, and the automorphism group for every other point is trivial. The stack is a way of "remembering" these automorphisms: A quotient stack [X/G] is a stack that is the quotient of a scheme X by the action of an algebraic group G. The objects of the stack are the points of X, and the morphisms are the elements of G that act on them. The stack "remembers" the group action. */
/* Stack, a quiver, which is a directed graph. A representation is a collection of vector spaces and linear maps. We can form a moduli space of these representations. However, some representations have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms. It is a space where the points are representations together with their group of automorphisms:  In modular representation theory, we can use stacks to study the moduli space of representations of a quiver. The group of automorphisms of a representation is the group of all invertible matrices that commute with the action of the quiver. A stack is a way of "classifying" these representations with their automorphisms. */
/* Stack, the field of rational numbers Q. We can form the adelic ring, which is a product of all the completions of Q. We can use stacks to study the moduli space of elliptic curves over the adeles. This is a way of "gluing" the local moduli spaces together to get a global object. The stack remembers the automorphisms of the elliptic curves at each prime:  In arithmetic number theory, we can use stacks to study the moduli space of elliptic curves with a level structure. This is a stack that classifies elliptic curves with their automorphisms, which are "local" at each prime. */
/* Stack, a cone. A cone is an orbifold, but it has a singularity at the vertex. The group of rotations around the vertex is a finite group. A stack is a way of "remembering" this group action. The stack of the cone is a space that has a point for every point on the cone, but the vertex has a "fiber" which is the group of rotations:  An orbifold is a space that is locally the quotient of a Euclidean space by a finite group action. A stack is a generalization of an orbifold, where the group can be an algebraic group. A stack is a space that is locally the quotient of a scheme by a group action. */
/* Stack, the moduli space of elliptic curves is a geometric object with singularities. A stack is a way of "smoothing out" these singularities. The stack of elliptic curves is a space that has a point for every elliptic curve, but the points with non-trivial automorphisms have "fibers" that are the group of automorphisms: A moduli stack is a stack that "classifies" a family of geometric objects. It is a generalization of a moduli space, where the objects are classified with their automorphisms. For example, the moduli stack of elliptic curves M1,1​ is a stack that classifies elliptic curves with their automorphisms. */
/* Stack, scheme is like a geometric space that is built from rings. A stack is a geometric space that is built from categories. A scheme is a 0-stack. A stack is a way of generalizing the concept of a geometric space to include higher-dimensional information: A stack is a generalization of a scheme. A scheme is a space that is locally a ring. A stack is a space that is locally a category. This is a very deep generalization that allows us to study objects with non-trivial automorphisms. */
/* Stack, a non-commutative algebra as a space of "rules" for multiplication. A module is a vector space with an action of the algebra. We can form a moduli space of these modules. However, some modules have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms:  In non-commutative ring theory, we can use stacks to study the moduli space of modules over a non-commutative algebra. The group of automorphisms of a module is the group of all invertible endomorphisms. A stack is a way of "classifying" these modules with their automorphisms. */
/* Stack, a Galois group. A Galois representation is a way of "representing" the group as matrices. We can form a moduli space of these representations. However, some representations have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms:  In arithmetic number theory, we can use stacks to study the moduli space of Galois representations. A Galois representation is a group homomorphism from a Galois group to a group of matrices. The group of automorphisms of a Galois representation is the group of all invertible matrices that commute with the action of the Galois group. A stack is a way of "classifying" these representations with their automorphisms. */
/* Stack, the moduli space of curves of genus 0, which is just a point. A curve of genus 0 is a sphere. The group of automorphisms of a sphere is a very large group. A stack is a way of "remembering" this group. The stack of curves of genus 0 is a more complex object than just a point: A stack is a way of generalizing the concept of a moduli space. A moduli space is a geometric object that classifies a family of objects up to isomorphism. A stack classifies a family of objects with their full group of automorphisms. */
/* Stack, a topological space. The loop space of the space is a space of all loops. A stack is a way of "remembering" the automorphisms of these loops. It is a space where the points are loops together with their group of automorphisms:  in homotopy theory, a stack can be seen as a way of generalizing the concept of a loop space. A loop space is the space of all loops from a point to itself. A stack is a way of generalizing this concept to include automorphisms. */
/* Stack, a dynamical system with a group action. We can form a moduli space of these systems. However, some systems have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms. It is a space where the points are equivariant dynamical systems together with their group of automorphisms:  In dynamics, we can use stacks to study the moduli space of equivariant dynamical systems. An equivariant dynamical system is a dynamical system with a group action. The group of automorphisms is the group of homeomorphisms that commute with the dynamics and the group action. A stack is a way of "classifying" these systems with their automorphisms. */
/* Stack, two surfaces that intersect. The intersection is a curve. The points on the curve can have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms. The stack of the intersection is a more complex object than just the curve:  Stacks can be used to describe the intersection of two schemes. The intersection of two schemes can have non-trivial automorphisms. A stack is a way of "remembering" these automorphisms. */
/* Singularity, example y2=x3+x2 in the real plane. This curve has a node at the origin (0,0). . At this point, the curve intersects itself. As you approach the origin from different directions, the "tangent line" seems to have multiple possibilities. This non-uniqueness of the tangent line is a visual manifestation of the singularity: A singularity on an algebraic variety is a point where the variety fails to be a smooth manifold. This means that at this point, the tangent space is not well-defined or has a dimension different from the variety's dimension. Visual Intuition: Consider the algebraic variety defined by the equation y2=x3+x2 in the real plane. This curve has a node at the origin (0,0). At this point, the curve intersects itself. As you approach the origin from different directions, the "tangent line" seems to have multiple possibilities. This non-uniqueness of the tangent line is a visual manifestation of the singularity. */
/* Singularity, failure of analyticity example: f(z)=1/z. It is analytic everywhere except at z=0. As you approach the origin, the magnitude of the function, |f(z)|, blows up. The point z=0 is a pole, a type of singularity. This "blow-up" behavior is a key visual characteristic: A singularity of a complex function f(z) is a point z0​ where the function is not analytic (i.e., not complex differentiable). Such points can be isolated (removable, pole, essential) or non-isolated. */
/* Singularity, cone tip fails to resemble the Euclidean point:  Imagine the surface of a cone. The apex of the cone is the singular point. In a topological space, a singularity can be thought of as a point that locally resembles a cone. A cone has a "pointy" tip, which is a singularity, while the rest of the space is smooth. No matter how you zoom in on this point, it never flattens out to resemble a Euclidean plane. This "pointedness" is a hallmark of a singularity in this context. */
/* Singularity, failure of prime ideals to be regular, consider regular local ring corresponds to a "smooth" point on an algebraic variety. A non-regular local ring corresponds to a singular point. Think of the origin of the nodal curve y2=x3+x2. The local ring at this point, k[x,y](x,y)​/(y2−x3−x2), is not regular:  In the context of commutative ring theory, a prime ideal p of a Noetherian local ring (R,m) is singular if the ring is not a regular local ring. A regular local ring is one where the dimension of the ring is equal to the minimal number of generators of its maximal ideal. Visual Intuition: A regular local ring corresponds to a "smooth" point on an algebraic variety. A non-regular local ring corresponds to a singular point. Think of the origin of the nodal curve y2=x3+x2. The local ring at this point, k[x,y](x,y)​/(y2−x3−x2), is not regular. The "irregularity" of the local ring is a way of algebraically encoding the geometric irregularity of the point. */
/* Singularity, fixed points of flows, example of a pendulum swinging back and forth:  In a dynamical system defined by a vector field, a singularity is a point where the vector field is zero. These are also known as fixed points or equilibrium points. The flow of the system "stalls" at these points. Visual Intuition: Consider a pendulum swinging back and forth. The fixed points are when it is hanging straight down (stable equilibrium) and when it is balanced perfectly upright (unstable equilibrium). . At these points, the velocity of the pendulum is zero, and the "flow" of the system stops. */
/* Singularity, modular representation theory:  In modular representation theory, a module M for a finite group G is called singular if it is not a direct sum of projective modules. A projective module is a "nice" module that lifts homomorphisms. The singularity of a module reflects its inability to "behave nicely" in a complex. Visual Intuition: Think of the representation of a group as a collection of linear transformations. A non-projective representation is like a set of transformations that has a "defect" or "hole." When you try to extend a linear map from a submodule, the map cannot be extended smoothly, indicating the "singularity" or "non-smoothness" of the representation. */
/* Singularity, noninjectivity of differential df_p, singularity of a smooth map f: M to N between manifolds is a point p in M where the differential df_p​ is not injective (i.e., its rank is less than the dimension of M):  Consider the map f(x,y)=(x2,y) from R2 to R2. The differential at the origin is not injective. The origin is a singular point of the map because the local neighborhood is "folded" or "squashed" onto itself, causing a loss of dimension. */
/* Singularity, degenerate critical point for f(x) = x^3, x = 0, Hessian is not invertible in Morse theory:  In Morse theory, a critical point of a function is where its derivative is zero. A singularity is a degenerate critical point, where the Hessian matrix at that point is not invertible. Visual Intuition: Consider the function f(x) = x3. The point x=0 is a critical point where the derivative is zero. However, the second derivative is also zero, so it is a degenerate critical point. Unlike a local minimum or maximum, the function is "flat" at this point, and you can't classify it based on the second derivative. This "flatness" is a visual cue for the singularity. */
/* Singularity, extension of local sections. Example on a punctured disk cannot be extended to a section on the entire disk if the function has a pole at the center. The "hole" in the domain where the extension fails is the singular point:  In sheaf theory, a singularity of a sheaf can be thought of as a point where a section defined on a small open set cannot be extended to a larger open set. This is a local-to-global problem. Visual Intuition: Consider the sheaf of holomorphic functions on the complex plane. A section defined on a punctured disk cannot be extended to a section on the entire disk if the function has a pole at the center. The "hole" in the domain where the extension fails is the singular point. */
/* Singularity, D-module fails coherent, a singular point is where the solutions to the system exhibit "pathological" behavior, such as a logarithmic singularity. The failure of coherence is the algebraic manifestation of this pathological behavior:  In the theory of D-modules, which studies systems of linear partial differential equations, a singularity is a point where the module is not coherent, meaning it doesn't behave like a module over a polynomial ring. Visual Intuition: Think of a system of differential equations. A singular point is where the solutions to the system exhibit "pathological" behavior, such as a logarithmic singularity. The failure of coherence is the algebraic manifestation of this pathological behavior. */
/* Singularity, bad reduction modulo prime number to get a singular curve. Imagine the elliptic curve defined by y2 = x3 − x. When you reduce it modulo 2, the equation becomes y2 = x3 + x over the field with two elements. This curve has a singular point at (0,0), which corresponds to the "bad reduction" of the original curve:  In arithmetic geometry, a singularity of an elliptic curve over a number field is a point of bad reduction. This means that when you reduce the curve modulo a prime number, the resulting curve is singular. Visual Intuition: Imagine the elliptic curve defined by y2=x3−x. When you reduce it modulo 2, the equation becomes y2=x3+x over the field with two elements. This curve has a singular point at (0,0), which corresponds to the "bad reduction" of the original curve. */
/* Divisor, subvariety of codimension 1: divisor is a subvariety of codimension one. Visual intuition: A divisor is a "hypersurface" or a "wall" within a higher-dimensional space. In 3D space, a divisor is a 2D surface; on a surface, a divisor is a 1D curve. */
/* Divisor, principal divisor:  principal divisor is a divisor that is the zero set of a single function. Visual intuition: A principal divisor is a "wall" defined by one simple equation, like a plane in 3D space defined by x = 0. */
/* Divisor, Weil divisor:  Weil divisor on a normal scheme X is a formal sum of irreducible subvarieties of codimension 1. It’s like a combination of different walls, each with a specific "multiplicity" or weight. */
/* Divisor, Cartier:  Cartier divisor is a collection of functions on open sets that are compatible on their overlaps. This is a more refined notion than a Weil divisor. Visual intuition: It's a "wall" that is defined by local equations that are "glued" together consistently. This is a powerful idea that generalizes to non-normal varieties. */
/* Divisor, divisor class groups:  divisor class group of a ring is the group of Weil divisors modulo the group of principal divisors. Visual intuition: It's the set of all "walls" that can't be defined by a single global function. It measures how far the ring is from being a unique factorization domain (UFD). */
/* Divisor, unique factorisation domain:  unique factorization domain (UFD), every Weil divisor is principal (elements or codimension one are uniquely factorised). The divisor class group is trivial. Visual intuition: In a UFD, every wall can be defined by a single global function. There are no "exotic" walls. */
/* Divisor, invertible sheaf and Cartier divisors:  in algebraic geometry, a Cartier divisor is equivalent to a line bundle or an invertible sheaf. Visual intuition: An invertible sheaf is a "line bundle," a geometric object that looks like a product of the space and a line at every point. The sections of this bundle are the functions that define the divisor. Recall that a Cartier divisors are walls that are defined by local equations that are "glued" consistently. */
/* Divisor, intersection theory, classical example of two lines intersecting at a point of codimension 2: main objects of study in intersection theory, which is concerned with how subvarieties intersect. Visual intuition: Divisors are the fundamental geometric objects whose intersections can be counted. For example, two lines in a plane intersect at a point, which has codimension 2. */
/* Divisor, rational functions of positive and negative weight:  divisor of a rational function is a Weil divisor that measures the zeros and poles of the function. Visual intuition: It’s a "map" of where a function is zero (a positive weight) and where it blows up (a negative weight). Weil divisors are combination of different walls, there are zero walls, and blow up walls. */
/* Divisor, valuation ring:  valuation rings, which are local rings that have a unique maximal ideal. The divisor is related to the valuation on the field of fractions. Visual intuition: The valuation ring is a way of "measuring" the order of a zero or a pole of a function at a point. */
/* Divisor, derived divisor:  derived divisor is a generalization of a divisor to a derived scheme. Visual intuition: It’s a "wall" in a "homotopically fuzzy" space, where the wall itself might be "fuzzy" and defined up to homotopy. */
/* Divisor, sheaf cohomology:  deeply connected to sheaf cohomology. For a line bundle L, the first cohomology group H1(X,L) measures the "obstructions" to a section of the line bundle. */
/* Divisors, canonical divisor:  canonical divisor is a fundamental divisor on a smooth variety that is related to the differential forms. Visual intuition: It is the "wall" that encodes the geometry of the variety. */
/* Divisors, ideal sheaf visualisation of sheaves as identification as to where the sheaves are:  ideal sheaf of a divisor is a quasicoherent sheaf that locally is an invertible ideal. Visual intuition: The ideal sheaf is the "data" that tells you where the divisor is in the space. Sheaves are like consistently glued sticky notes. */
/* Divisors, principal divisors and rational functions:  one-to-one correspondence between principal divisors and rational functions up to a constant. Visual intuition: A single rational function defines a specific "wall" in the space, a place where it is zero or infinite. */
/* Divisors, effective divisors:  effective divisor is a Weil divisor where all the coefficients are non-negative. It's a "wall" that has a positive "weight." */
/* Monodromy, f(z) = root(z) . Let's start at z=1 with root(1) = 1. If we travel a full circle around the origin (a singularity) in the complex plane, we arrive back at z=1 but now the value is root(1) ​= −1. This "change" from 1 to −1 is the monodromy. It's like a spiral staircase where you end up on a different floor even though you've made a full circle:  In complex analysis, monodromy describes how a multi-valued function, like the complex logarithm, changes value when its argument is analytically continued along a closed path around a singularity. */
/* Monodromy, consider singular algebraic curve, such as y2=x3−x. This curve has a singular point. If we take a family of nearby smooth curves, and move around the singular curve in a loop, the local geometry of the fiber will "twist." This twisting is the monodromy. It's the action of a group on the fundamental group of the space:  In algebraic geometry, monodromy describes how the local data of a sheaf (e.g., the stalk) changes when transported around a singularity of a variety. For a flat connection, the monodromy is given by a group representation. */
/* Monodromy, helix E=R covering the circle B=S1 via the map p(t)=(cos(t),sin(t)). If you walk a full loop on the circle, starting at (1,0), your path in the helix lifts to one that starts at 0 and ends at 2 pi. The difference, 2 pi, is the monodromy. It's a way of counting how many times a path "spirals up" in the covering space:  In homotopy theory, monodromy is the action of the fundamental group pi_1​(B) of a base space B on the fibers of a covering space p: E to B. A path in B lifts to a unique path in E, and a closed loop in B maps to a path in E that ends on a different point in the fiber. */
/* Monodromy, roots of the polynomial x^2−2. The roots are +-2. We can visualize the Galois group as a permutation group that swaps the two roots. The monodromy is this "swapping" action as you move around a singularity. It is the action of a group that captures the symmetries of the roots:  In arithmetic number theory, monodromy can be seen as the action of the absolute Galois group of a number field on the roots of a polynomial. The "monodromy group" of a polynomial with coefficients in a number field is the Galois group of its splitting field. */
