/* Homotopy, equivalent under parameterization:  ontology in Homotopy Type Theory, the idea is the homotopy of a path and inverses covers areas and therefore is not exactly the identity, therefore one can invent homotopy to consider the entire area of paths and a path that covers no areas is equivalent, therefore this motivates homotopy as a higher dimensional operation. */
/* Homotopy, filling space for paths between paths:  consider family of paths with same end point then there are areas , so one can invent homotopy as a filling space of k+1 dimensions for k dimensional paths, inventing the notion of a k-morphism. */
/* Homotopy, continuous deformation:  "deformation" is a continuous family of maps parameterized by a "time" interval. */
/* Homotopy, path in function space:  continuous path in the space of continuous maps */
/* Homotopy, family of map:  continuous one parameter family of maps */
/* Homotopy, map from cylinder:  map from X * I into Y, I is unit interval, map restricted to the bottom face for the first map, top face for the second map */
/* Homotopy, equivalence relation:  Equivalence relation on set of continuous maps, partitioning into homotopy classes. */
/* Homotopy, weak isomorphism:  homotopy equivalent if pair of maps composition is homotopic to identity map, weaker than homemorphism (topological isomorphism) */
/* Homotopy, define homotopy category:  homotopy classes of maps are morphisms on the homotopy category, objects are topological spaces, homotopy is equivalence relation giving which morphisms are the same */
/* Homotopy, defining invariant of invariant functor:  Homotopy define invariant functors (fundamental group and homology groups), two maps are homotopic, induces same homomorphism */
/* Homotopy, factorisation of maps:  Factor maps through special objects and properties, example factor through cylinder objects with fibrations and cofibrations */
/* Homotopy, high dim morphisms:  homotopy between two 1-morphism is 2-morphism */
/* Homotopy, nullhomotopic:  map is nullhomotopic if homotopic to constant map, defines contractible spaces */
/* Homotopy, relative:  relative homotopy keep points in a subspace fixed, defining fundamental groups where loops have fixed base points */
/* Homotopy, simplicial maps:  defined combinatorially as elementary moves on simplicies of complex, giving discrete computational model */
/* Homotopy, equal in type theory:  Path between two points in space is proof that points are equal */
/* Homotopy, fibration category:  category with weak equivalences, it is an axiom */
/* Homotopy, infinity groupoid:  points are objects, paths are 1-morphisms, homotopies are 2-morphisms, and so on */
/* Homotopy type theory, proof system using homotopy:  define a point to be a (-2)-groupoid or a proposition, then consider symmetries of true statements, so types as points become infinitely groupoids considering from points to paths and so on. */
/* Covering space, example with spiral staircase on to a circle:  covering space of a topological space X is a space X~ with a continuous map p: X~ to X such that for every point x∈X, there is an open neighborhood U of x for which the preimage p−1(U) is a disjoint union of open sets in X, each of which is mapped homeomorphically onto U by p. Imagine a circle. A possible covering space is a "spiral staircase" that projects onto the circle. Each step of the staircase is a disjoint copy of a small arc of the circle. The projection map takes each point on the staircase to the corresponding point on the circle, wrapping around infinitely many times. */
/* Covering space, real line as universal cover onto a circle with group Z that unwraps to real line:  universal cover of a space X is a simply connected covering space, which "unwraps" all loops in X. For the circle, the universal cover is the real line. A path on the real line that starts at 0 and goes to 2π projects to a loop around the circle. The real line provides a way to "lift" any loop in the circle to a non-looping path. */
/* Covering space, deck transformations as integer translations on spiral covering space of the real line:  deck transformations are a group of homeomorphisms of a covering space X* that preserve the projection map p : X* to X is called the group of deck transformations. For the real line covering the circle, the deck transformations are the integer translations x to x + n for n in Z. These transformations move you from one "sheet" of the cover to another while still projecting to the same point on the circle. */
/* Covering spaces, etale cover as a locally projection resemblence from y^2 = x to the line is an etale cover with two sheets, point on line is two points on hyperbola, looks like projection of two lines onto one:  étale cover is a finite flat morphism of schemes that is unramified. It's a generalization of a covering space from topology to algebraic geometry. Imagine a complex algebraic curve with an étale cover. The cover is a new curve that projects onto the old one, locally looking like a product. For instance, the map from the hyperbola y2=x to the line is an étale cover (with two sheets). At a point on the line, there are two points on the hyperbola, which locally resembles a projection of two lines onto one. */
/* Covering spaces, Galois cover with deck cover of the complex line by the hyperbola y^2 = x^2−1. The deck transformations are the reflections (x,y) to (x,−y):  étale cover whose deck transformation group acts transitively on the fibers. This group is called the Galois group of the cover. Imagine a cover of the complex line by the hyperbola y^2 = x^2−1. The deck transformations are the reflections (x,y) to (x,−y). This group acts transitively on the fibers (the two points above each point on the line), which are the algebraic counterpart to the deck transformations of a topological cover. */
/* Covering, of categories like directed graph, local isomorphisms respect the direction of the morphisms:  covering of a category is a functor that, for each object, maps the morphisms in the covering category to the morphisms in the base category in a well-behaved way. Imagine a category as a directed graph. A cover is a new graph that projects onto the old one, such that the maps from a new vertex to any other vertex are locally isomorphic to the maps from the old vertex. This is a way to "unfold" the graph. */
/* Covering space, torus of 2D plane, dynamical systems of a torus is unwrapped to straight line on the plane:  dynamical systems, a map f: X → X is a covering map if it's a local homeomorphism. The inverse map is not necessarily a single function. Imagine a torus (a doughnut shape). A dynamical system on the torus can be studied by lifting it to its universal cover, which is the 2D plane. The dynamics on the torus (a point moving around) is "unwrapped" to a straight line on the plane. The covering map provides a way to simplify the dynamics by working in a simpler space. */
/* Covering space, induced covers from pullbacks of cover of codomain space X to domain space Y: concept of a covering can be induced by a map to another space. Visual Intuition: If we have a covering of a space X and a map from a space Y to X, we can "pull back" the cover to get a cover of Y. This is like taking a projection onto a screen, and then projecting the screen onto a new screen, which induces a new cover. */
/* Covering space, classified by the fundamental group of the space, symmetries and subgroups of the fundamental group serve as the possible covers of the space:  set of all covers of a space is classified by the fundamental group. The fundamental group acts as a "master list" for all possible covers of a space. Every possible cover corresponds to a subgroup of the fundamental group. */
/* Sheaf, stick notes intuition:  surface with sticky notes. A sheaf is a collection of "pieces of information" on each note. The sheaf conditions ensure that if you have a collection of pieces of information that "match up" on the overlapping parts of the notes, you can always glue them together to get a single, coherent piece of information on the whole surface. */
/* Stalk, visual intuition of microscope: a powerful microscope. You're looking at a single point, and the stalk is the "data" that the sheaf assigns to that point, ignoring all the global information. It's the "infinitesimal" information. */
/* Sheaf, locally free intuition with a surface and patches:  Think of a surface. A locally free sheaf is like a vector bundle over that surface. For each little patch on the surface, the information on the sheaf is just a copy of a vector space. */
/* Homology, measure of holes:  measures the "holes" in a topological space. */
/* Cocycle, cocycle condition measures circulation around a face:  cocycle is a cochain whose differential is zero. The differential of a 1-cochain is a 2-cochain that, roughly, measures the circulation around the boundary of a face. The cocycle condition means there is no circulation. */
/* Cocycle, visual intuition as set of arrows on the edges of a surface:  Imagine a 1-cochain as a set of arrows on the edges of a surface, each with a numerical value. The differential of this cochain measures the "flow" around the boundary of each face. If the sum of the flows on the boundary of every face is zero, it's a cocycle. */
/* Coboundary, cochain that is the differential of a previous cochain:  cochain that is the differential of a previous cochain. The differential of a 0-cochain assigns a value to each vertex. The differential of this is a 1-cochain that measures the difference in values on the two endpoints of an edge. */
/* Coboundary, visual intuition as assignment of heights along a surface by taking differences of heights:  1-coboundary is an assignment of values to edges that comes from taking differences of values at the vertices. Imagine a height function on a surface; the 1-coboundary is the set of changes in height along the edges. */
/* Cohomology, sheaf cohomology as obstructions on space attached to open sets:  space with "data" attached to each open set (a sheaf). Sheaf cohomology measures the "obstructions" to consistently gluing together local pieces of data to form a global object. */
/* Cohomology, singular cohomology for singular chains or continuous maps from standard simplices into the space:  type of cohomology for topological spaces, defined using singular chains (continuous maps from standard simplices into the space). It is a fundamental invariant of a topological space. */
/* Cohomology, de Rham as holes of the manifold:  smooth manifold, de Rham cohomology is the cohomology of the complex of differential forms. It measures the "holes" in the manifold using calculus. */
/* Cohomology, visual intuition in terms of vector fields closed 1-form with no curl, exact 1-form as gradient:  closed 1-form is a vector field whose curl is zero. It's like a fluid flow that has no local vortices. An exact 1-form is the gradient of a function. de Rham cohomology tells you when a "no-vortex" flow is not the gradient of any height function */
/* Cohomology, Betti numbers over real numbers as holes:  dimension of the n-th cohomology group over the real numbers is the n-th Betti number, which is a measure of the number of n-dimensional holes in a space. */
/* Spectral sequence, sequence of page:  page is bigraded modules, sequence of bigraded modules */
/* Spectral sequence, differentials:  differential dr​: E_r^{p,q}​→E_r^{p+r, q−r+1}​ such that dr​ * dr​ = 0. This differential gives the page a chain complex structure. */
/* Spectral sequence, homology of pages:  next page, E_{r+1}​, is the homology of the previous page with respect to the differential dr​. This is the core mechanism of a spectral sequence. */
/* Spectral sequence, convergence:  converges to a graded object, which is typically the homology of a given complex. This means that for a fixed total degree n = p+q, the terms E_r^{p,q}​ eventually become stable for large r. */
/* Spectral sequence, filtration:  filtration of a chain complex C∙​. A filtration is a sequence of subcomplexes into F_p ​C_* ​into F_{p+1} ​C_* ​into ... The terms of the first page of the spectral sequence are related to the homology of the successive quotients of this filtration. */
/* Spectral sequence, associated graded object:  spectral sequence computes the homology of the filtered complex by first computing the homology of its associated graded object, Gr(C)= ++_p​ F_p ​C /F_{p+1} ​C. The first page, E_1​, is often the homology of this graded object. ++ is direct sum in this case. */
/* Spectral sequence, edge homomorphisms:  "edges" of the spectral sequence, where p = 0 or q = 0, are often simple and provide a way to relate the spectral sequence to the homology of the original complex. */
/* Spectral sequence, first quadrant spectral sequence:  first quadrant spectral sequence if its non-zero terms are only in the first quadrant of the bigraded plane, i.e., p ≥ 0,q ≥ 0. */
/* Spectral sequence, exact couple:  system of two objects and three maps that form a diamond-shaped commutative diagram. */
/* Spectral sequence, homology of derived functors:  computing the homology of derived functors. For example, the Grothendieck spectral sequence relates the derived functors of a composition of two functors to the derived functors of each individual one. */
/* Spectral sequence, Hochschild-Serre Spectral Sequence:  This spectral sequence relates the group cohomology of a group G to the group cohomology of a normal subgroup N and the quotient group G/N. It's a key tool in group cohomology and number theory. */
/* Spectral sequence, homotopy theory:  spectral sequence that computes the homotopy groups of a space by filtering its universal covering space. The Serre spectral sequence is a prime example, relating the homology of a fiber bundle to the homology of its base and fiber. */
/* Spectral sequence, fibration:  deeply connected to a fibration in topology. It allows us to compute the homology of the total space from the homology of the base space and the fiber. */
/* Spectral sequence, Adams:  omputes the stable homotopy groups of a spectrum using the Ext groups of its mod p cohomology. */
/* Spectral sequence, Leray:  sheaf cohomology computes the sheaf cohomology of a space by using the cohomology of a cover of the space and the cohomology of the intersections of the cover. */
/* Cofibration, imagine a hollow sphere A=S2 and a solid ball X=D3. The inclusion map i: S2 to D3 is a cofibration. If we have a map from the ball to another space, and we start to deform the sphere (the boundary of the ball), we can always deform the whole ball in a consistent way. The boundary is "stuck" to the ball in a way that allows us to push any deformation from the boundary into the interior. This is the dual concept to a fibration, which allows us to "lift" homotopies from a base space: A cofibration is a continuous map i: Ato X between topological spaces that satisfies the homotopy extension property. This means that for any space Y, any map f: X to Y, and any homotopy H:A cross I to Y of the restricted map f∣A​, there exists a homotopy lift H~:X cross I to Y that extends H. In other words, any homotopy defined on the subspace A can be "extended" to a homotopy on the entire space X. */
/* Cofibration, a space A and two maps, f: A to B and g: A to C. The pushout of this diagram is a space P that "glues" B and C together along the image of A. If the map A to B is a cofibration, the pushout is well-behaved. For example, if we glue two disks together along a circle, the resulting space is a sphere. The inclusion of the circle into the disk is a cofibration, and this property ensures that the gluing is well-behaved:  The homotopy extension property can be formulated in terms of a pushout square. A cofibration is a map A to X such that a specific pushout square is a pullback square. */
/* Cofibration, the inclusion of the origin in the affine plane. This is a closed immersion. The map from Spec(k[x,y]/(x,y)) to Spec(k[x,y]) is a closed immersion. This is a geometric "cofibration," where a smaller space is "stuck" inside a larger one in a very rigid way. The embedding is a cofibration because any map from the origin to a scheme can be extended to the entire plane: A closed immersion of schemes f:X→Y is a morphism that is a homeomorphism onto its image, and the induced map on sheaves of rings is a surjective map. A closed immersion is a "cofibration" in the geometric sense, as it embeds one scheme as a closed subscheme of another. */
/* Cofibration, a free module F and a submodule N. The inclusion of N into F is a cofibration. A free module is a "cofibrant" object, and this is a key property in homological algebra. It means that the module can be "built" from a free module:  In the category of modules over a non-commutative ring, a cofibration is a module homomorphism that is an injective map with a projective cokernel. This is a "dual" concept to a fibration, which is a surjective map with an injective kernel. */
/* Cofibration, consider field F_p​ as a single point. The field F_{p^n}​ is a larger field with more points. The inclusion map is a cofibration. This is a way of "embedding" a smaller algebraic object into a larger one. This is a fundamental construction in arithmetic geometry:  In the context of number theory, a cofibration can be seen through the lens of a Frobenius map. The inclusion of a finite field into a larger finite field can be seen as a cofibration. */
/* Cofibration, the group algebra F_p ​_Cp​. The simple module F_p​ is not projective. However, we can find a projective module P and a map from P to F_p​. The kernel of this map is a submodule. The inclusion of the kernel into the projective module is a "cofibration." This is a way of "building" a simple module from a projective one:  In the category of modules over a group algebra, a cofibration is a module homomorphism that is an injective map with a projective cokernel. This is a key property for understanding the structure of modules and their relationships. */
/* Cofibration, building a 2-sphere by starting with a point, attaching two lines (a "figure eight"), and then attaching a disk. At each step, the inclusion of the subcomplex is a cofibration. This is a way of "building" a complex space from simpler pieces in a well-behaved way. The cofibration property guarantees that the attachment is "non-trivial.": A CW complex is a space built up by attaching cells of increasing dimension. The inclusion of a subcomplex into a CW complex is a cofibration. This is a powerful property that makes CW complexes well-behaved in homotopy theory. */
/* Cofibration, formal scheme is a "germ" of a scheme along a closed subscheme. The inclusion of the formal scheme of the origin in the formal scheme of the affine line is a cofibration. This is a way of "embedding" a local object into a larger one: A closed immersion of formal schemes is a cofibration in the category of formal schemes. This is a way of embedding a formal scheme as a closed subscheme of another. */
/* Cofibration, a ring of integers Z is a principal ideal domain, so every ideal is free, and thus projective. The inclusion of an ideal, say 2Z, into Z is a cofibration. This is a way of "embedding" a module into a larger one in a well-behaved way: A ring R is left hereditary if every left ideal is a projective module. This means that every inclusion of a left ideal into the ring is a cofibration. This is a very strong property that is a key to understanding the homological properties of the ring. */
/* Cofibration, inclusion of a compact manifold into a larger one is a proper morphism. For example, the inclusion of a sphere into R3 is a proper morphism. This is a way of "embedding" a compact object into a larger one: A proper morphism of schemes is a morphism that is separated, of finite type, and universally closed. A proper morphism is a "cofibration" in a strong sense. It is a map that is a closed embedding. */
/* Cofibration, the ring of integers Z. The inclusion of Z into the ring of rational numbers Q is a cofibration. This is a way of "embedding" a ring into a field:  The inclusion of a ring into its localization at a prime ideal is a cofibration in a sense. The localization process is a way of "embedding" a ring into a larger one. */
/* Characteristic, field of rational numbers Q. The characteristic is 0, since no matter how many times you add 1 to itself, you never get 0:  This can be visualized on a number line that extends infinitely in both directions. There is no finite number of steps that brings you back to the origin, which is a manifestation of characteristic 0. */
/* Characteristic, representation is related to the trace of the matrices in the representation. For example, for the cyclic group of order 3, C3​, a representation over C sends the generator g to the matrix (0 1​; -1 −1​). The trace of the characteristic is the sum of the eigenvalues. These eigenvalues give us information about the "behavior" of the representation:  In modular representation theory, the characteristic is an algebraic invariant of a representation of a group G over a field of characteristic p. It's a map from the group algebra to the field that captures the properties of the representation. */
/* Characteristic, Euler characteristic of a polyhedron is calculated as V−E+F, where V is the number of vertices, E is the number of edges, and F is the number of faces. For a tetrahedron, V=4, E=6, and F=4, so the Euler characteristic is 4−6+4=2. For a cube, V=8, E=12, and F=6, so the Euler characteristic is 8−12+6=2. Both can be continuously deformed into a sphere, which also has a characteristic of 2. The characteristic is a measure of the "holes" in the object:  In homotopy theory, the characteristic is a topological invariant, often called the Euler characteristic or Euler number. It's a number that describes the "shape" of a topological space. Visual Intuition: The Euler characteristic of a polyhedron is calculated as V−E+F, where V is the number of vertices, E is the number of edges, and F is the number of faces. For a tetrahedron, V=4, E=6, and F=4, so the Euler characteristic is 4−6+4=2. For a cube, V=8, E=12, and F=6, so the Euler characteristic is 8−12+6=2. Both can be continuously deformed into a sphere, which also has a characteristic of 2. The characteristic is a measure of the "holes" in the object. */
/* Characteristic, short exact sequence of vector spaces 0 to A to B to C to 0. This can be viewed as a chain complex with three non-zero modules. The Euler characteristic is dim(A)−dim(B)+dim(C)=0. This is a statement of the "conservation of dimension" in the complex:  In homological algebra, the Euler characteristic of a chain complex C∙​ is the alternating sum of the ranks of its modules, sum over i of ​(−1)^i rank(C_i​). It is related to the homology groups of the complex. Visual Intuition: Consider a short exact sequence of vector spaces 0 to A to B to C to 0. This can be viewed as a chain complex with three non-zero modules. The Euler characteristic is dim(A)−dim(B)+dim(C)=0. This is a statement of the "conservation of dimension" in the complex. */
/* Stacks, a 2D representation of the cyclic group C4​ (rotations of a square). The group acts on the plane by rotating it. A nontrivial automorphism is a transformation of the plane (like a scaling or a shear) that commutes with the rotations. This means if you first rotate the plane and then apply the transformation, it is the same as applying the transformation and then rotating: A nontrivial automorphism of a representation of a group is an invertible linear map that commutes with the action of the group. These are symmetries of the representation itself. By Schur's Lemma, if a representation is simple, its endomorphism ring is a division algebra, and its automorphisms are the invertible elements of this algebra. */
/* Stacks, sphere S2 has a vast group of automorphisms, given by rotations, reflections, and other more complex homeomorphisms. The rotation of the sphere about a fixed axis is a nontrivial automorphism. It is a symmetry of the sphere as a topological space: A nontrivial automorphism of a topological space X is a homeomorphism from X to itself that is not the identity. This is a topological symmetry of the space. The group of all such automorphisms is denoted Aut(X). */
/* Chain maps, simplicial map f: K to L from a tetrahedron K to a square L. The map f takes the vertices of K to the vertices of L and induces maps on the edges and faces. This simplicial map induces a chain map on the chain complexes of K and L:  Simplicial map f: K to L from a tetrahedron K to a square L. The map f takes the vertices of K to the vertices of L and induces maps on the edges and faces. This simplicial map induces a chain map on the chain complexes of K and L. The chain map is essentially a geometric map that preserves the "combinatorial structure" of the objects, and the commutativity of the diagram reflects this preservation. */
/* Chain maps, maps on singular chains, example of chain maps takes every singular simplex (a continuous map from a standard simplex into X) to a point, which is a degenerate singular simplex in Y: A continuous map f: X to Y between two topological spaces induces a chain map f∗​: S(X)  to S(Y) between their singular chain complexes. This chain map is constructed by applying f to the singular simplices in X. Imagine a continuous map that deforms a sphere X into a point Y. This map takes every singular simplex (a continuous map from a standard simplex into X) to a point, which is a degenerate singular simplex in Y. The chain map is the "point-wise" action of the continuous map on all the "triangulations" of the spaces, preserving their topological properties like "connectedness" or "holes." */
/* Chain maps, group cohomology and bar complexes:  in group cohomology, a chain map is a map between the homogeneous bar complexes of two groups (or of a group and its subgroup). The bar complex is a specific type of free resolution. Visual intuition: The bar complex of a group can be thought of as a structured way to "disassemble" the group into its fundamental pieces. A map between groups induces a chain map that "disassembles" the group homomorphism into a sequence of compatible maps on these pieces. */
/* Chain maps, relative chain map in relative homology on these complexes is a map that respects this "modding out" process. It's a map that "ignores" the interior of the subspaces and focuses on the relationship between the boundaries:  In relative homology, a chain map is a map between the relative chain complexes of two pairs of spaces (X,A) and (Y,B), where A and B are subspaces of X and Y respectively. Visual intuition: A relative chain complex is a way to study the homology of a space by "modding out" a subspace. A chain map on these complexes is a map that respects this "modding out" process. It's a map that "ignores" the interior of the subspaces and focuses on the relationship between the boundaries. */
/* Injective, subring embedding of matrices visual intuition:  An injective ring homomorphism is a way to embed one ring as a subring of another without any loss of information. Imagine a ring of 2×2 matrices. An injective map could embed this ring into a ring of 3×3 matrices by adding a row and a column of zeros and a single one at the bottom right. */
/* Injective, representations, visual example of cyclic group of order two acting on a line to be perfectly embedded into a plane:  An injective representation of a group G is an injective module over the group algebra kG. An injective representation is a space of symmetries that can perfectly contain any smaller space of symmetries without restriction. For example, if we have a group C2​ (the cyclic group of order 2) acting on a line, an injective representation is a larger space (like the plane) where this action can be perfectly embedded. */
/* Injective, actions on a sphere with no redundancy, definition of injective actions: A group action on a space is injective if different group elements act differently on the space. The group's action is perfectly faithful. Each group element corresponds to a unique transformation, and there's no redundancy. For example, the action of the group of rotations on the sphere is injective. */
/* Projective resolution, periodic projective resolution multiplication by 1 that approximates Z from the left:  projective resolution of a module M is an exact sequence of projective modules P2 to P1 to M to - from the left that "approximates" M from the left. Consider Z_2 acting on module Z by multiplication by 1, trivial representation has periodic projective resolution Z[Z_2] to Z[Z_2] to Z to 0 where Z[Z_2] is a group ring. */
/* Injective resolution, approximates module M from the right, example approximate to embed it into larger modules from Z to Q to Q/Z:  injective resolution of the Z-module Z is 0 to Z to Q to Q/Z to 0, where Q is the rational numbers and Q/Z are the rationals mod 1. The module Q is injective and divisible, capable of "absorbing" any homomorphism from a submodule of another module. Q/Z is also injective. This resolution visualizes how Z can be embedded into a sequence of larger, "nicer" modules that capture its structure without losing information. */
/* Resolution, minimal resolution is free resolution of minimal rank using example of poly ring k[x,y] / (x^2, xy, y^2):  In the ring k[x,y]/(x2,xy,y2), a minimal resolution of the module k is given by from k[x,y]^3 to k[x,y]^2 to k[x,y] to k to 0. The minimal resolution is the most compact and efficient "architectural blueprint" for a module, using the fewest possible free modules to describe its structure. */
/* Resolution, by means of simplicies onto a circle:  topological space of a circle can be resolved by a sequence of simplicial complexes, where the first is a single loop, the next is a 2-simplex with an edge glued to it, and so on. This provides a way to approximate a curved complex surface with flat triangles, making it easier to compute its properties. */
/* Classifying space, topological monoid of n by n matrices by Grassmannian:  monoid of n×n matrices, the classifying space is the Grassmannian manifold of n-planes in an infinite-dimensional space. The geometric properties of the Grassmannian are a reflection of the algebraic properties of the matrix monoid. */
/* Classifying space, cohomology group H^2(X, G) classifying principal G-bundles, or gerbes:  cohomology group H2(X,G) can be used to classify principal G-bundles, which are also known as gerbes. A gerbe is a "twisted" object. The classifying stack of a group G is a geometric object that captures all the possible "twists" for G-bundles, which is a geometric manifestation of the second cohomology group. */
/* Lawvere-Tierney topology, double negation: turns it into classical logic, this means statement is equivalent to double negation */
/* Boolean topos, double negation is identity: recall that if internal logic is classical and not intuitionistic. Intuitionistic logic is about local properties extending to global ones.
*/