/* Measure theory, linear combination of points:  paradoxes arise when one defines infinite linear combination of points, therefore measure theory motivates the conditions in which this is not a problem. */
/* Sigma ring, sets with finite measure:  It has sets of finite measure. */
/* Sigma ring, boundedness:  Sigma algebra must contain entire universe, sigma-ring is bounded as it contains subsets can be built from given collections */
/* Sigma ring, homomorphism domain:  Appropriate domain for a measure to the nonnegative reals */
/* Sigma ring, generalises Borel sets:  Borel sets on real form a sigma ring, and a sigma algebra */
/* Sigma ring, computation:  Closed system of sets, with algorithms for verifying closure */
/* Sigma ring, sigma subalgebra of power set:  Sigma subalgebra of power set without requirement of containing entire set */
/* Sigma ring, closure definition:  Closed under countable union and relative complementation */
/* Fatou's lemma, bars of histograms approximating an area under a curve. Even if some bars oscillate up and down, the “lowest horizon” formed pointwise (the lim inf) integrates to less than the lim inf of their total areas. Example: f_n(x) = χ[0,1/n](x) on [0,1]. Each integral = 1/n, but lim inf integral = 0, matching the integral of the lim inf function (0):  Integration is a map from integrals of lim infimum of f_n to the limit infimum of integrals of f_n. */
/* Fatou's lemma, gambling outcomes Xn​ as bars. The expectation is the center of mass of these outcomes. The “eventual guaranteed payoff floor” (lim inf) always has expected value below the “eventual lim inf of averages.” Concrete example: Xn = indicator of “first n coin tosses are all heads.” Expectation = 2^{−n}, so LHS = 0, RHS = 0:   */
/* Bounded convergence theorem, bars of histograms converging pointwise to the bars of f. Because the bars never grow beyond a fixed ceiling, their shaded areas converge exactly:  f_n : [0, 1] to R, with f_n(x) of norm less than equal to 1 and f_n(x) converges to f(x) pointwise, then limit as n tends to infinity of (Lebesgue integral) of f_n over 1 and 0 is integral of f from 1 to 9. */
/* Dominated convergence theorem, f_n​ sit inside a “tent roof” given by g. Their shaded areas converge because the roof prevents runaway spikes:  For f_n to f, and norm of f_n dominated by g not related to f_n in L_1 then limit of integral f_n converges to integral of f. */
/* Dominated convergence theorem, L_1, functions wiggle but never escape a fixed “envelope.” Their areas settle onto the limit curve:  DCT guarantees continuity of the integral functional on bounded sets in L1. */
