/* Grothendieck group, fundamental construction in K-theory: , consider a ring A, let F be the be the category of left A modules, the Grothendieck group of the category F is an abelian group with generators for each left A module and relations [E] = [E*] + [E**] associated with exact sequences such that 0 is to E is to E* is to E** is to 0. This group completion forming the Grothendieck group is a key part of the definition of K-theory. */
/* Homotopy, continuous deformation:  "deformation" is a continuous family of maps parameterized by a "time" interval. */
/* Homotopy, path in function space:  continuous path in the space of continuous maps */
/* Homotopy, family of map:  continuous one parameter family of maps */
/* Homotopy, map from cylinder:  map from X * I into Y, I is unit interval, map restricted to the bottom face for the first map, top face for the second map */
/* Homotopy, equivalence relation:  Equivalence relation on set of continuous maps, partitioning into homotopy classes. */
/* Homotopy, weak isomorphism:  homotopy equivalent if pair of maps composition is homotopic to identity map, weaker than homemorphism (topological isomorphism) */
/* Homotopy, define homotopy category:  homotopy classes of maps are morphisms on the homotopy category, objects are topological spaces, homotopy is equivalence relation giving which morphisms are the same */
/* Homotopy, defining invariant of invariant functor:  Homotopy define invariant functors (fundamental group and homology groups), two maps are homotopic, induces same homomorphism */
/* Homotopy, factorisation of maps:  Factor maps through special objects and properties, example factor through cylinder objects with fibrations and cofibrations */
/* Homotopy, high dim morphisms:  homotopy between two 1-morphism is 2-morphism */
/* Homotopy, nullhomotopic:  map is nullhomotopic if homotopic to constant map, defines contractible spaces */
/* Homotopy, relative:  relative homotopy keep points in a subspace fixed, defining fundamental groups where loops have fixed base points */
/* Homotopy, simplicial maps:  defined combinatorially as elementary moves on simplicies of complex, giving discrete computational model */
/* Homotopy, equal in type theory:  Path between two points in space is proof that points are equal */
/* Homotopy, fibration category:  category with weak equivalences, it is an axiom */
/* Homotopy, infinity groupoid:  points are objects, paths are 1-morphisms, homotopies are 2-morphisms, and so on */
/* Projective module, direct summand of free module:  direct sum of projective module and another module forming a free module */
/* Projective module, lifting property:  lifts surjective module homomorphism module M to module N and any homomorphism projective module P to module N using ring homomorphism from projective P to module M. Very similar to direct sum definition. */
/* Projective module, split short exact sequence:  projective if every 0 -> K -> M -> P -> 0, is split exact aka M is isomorphic to direct sum of K and P */
/* Projective module, exactness of Hom functor:  TFAE: (1) projective; (2) Hom(P, - ) is exact. */
/* Projective module, projective resolution:  Projective resolution of length 0, -> P_1 -> P_0 -> M -> 0, all P_i are projective */
/* Projective module, dual basis:  for a projective module, a dual basis exists, linear forms in Hom(P, R) for coefficients x_i in projective module P, ring R. */
/* Projective modules, flat:  All projective modules are flat modules, flat modules preserve injectivity under tensor product */
/* Projective modules, condition via localisation at each prime ideal to get a free R_p module:  TFAE: (1) for each and every prime ideal p in ring R, localised P_p is a free R_p module; (2) P is projective. */
/* Projective module, idempotent endomorphism:  TFAE: (1) P is finitely generated projective module; (2) P is the image of idempotent endomorphism of a free module. Idempotent endomorphism is map p from F to F, such that p^2 = p. */
/* Projective module, 0 Ext group:  TFAE: (1) module projective; (2) Ext^1_R(P, M). Vanishing of first Ext group means it is acyclic in some sense */
/* Projective module, locally free sheaf:  TFAE (1) finitely generated projective module over commutative ring R; (2) locally free sheaf on affine scheme Spec(R) */
/* Projective module, vector bundles:  Projective modules are to free modules (take resolutions of free modules) as vector spaces are to trivial bundles (use many trivial bundles to get vector space, no need to consider global twisting) */
/* Projective module, flat and finitely presented:  For finitely generated modules, being projective is equivalent to being flat (tensor product is exact, resolution of free modules gives flat module) and finitely presented (generators and relations) */
/* Projective module, over local ring and locally free: A projective module over a local ring is always free. */
/* Projective module, unimodular row:  fg projective module of rank 1 is a unimodular row that can be completed to an invertible matrix. */
/* Projective module, monoid:  isomorphism classes of finitely generated modules form a commutative monoid under direct sum, construction of K-group K_0(R) */
/* Projective module, projective cover:  projective cover is minimal surjection of projective module, TFAE: (1) projective module; (2) projective cover of every homomorphic module */
/* Projective module, faithfully flat module can generate entire module category:  TFAE: (1) finitely generated projective module generating entire module category; (2) faithfully flat module */
/* Projective module, torsion free comparison in Dedekind domains:  TFAE: (1) projective over Dedekind domain; (2) torsionfree over Dedekind domain. Show that a module is direct sum of finitely generated free module and fractional ideal, in a Dedekind domain, finitely generated module is isomorphic to direct sum of free module and an ideal. */
/* Projective module, sections of vector bundle like object:  modules whose elements are "sections" of a vector bundle like object */
/* Injective module, categorical dual to projective module:  Reverse arrows in commutative diagram for projective module gives injective module diagram */
/* Injective module, Hom-tensor adjunction:  Contravariant hom functor, so becomes hom-tensor duality */
/* Injective module, cogenerator:  TFAE: (1) module C is injective cogenerator; (2) injective and for all nonzero module M, nonzero homomorphism from M to C */
/* Injective module, Matlis theorem, local structure:  Matlis theorem is for a commutative Noetherian ring, every injective module is uniquely a direct sum of indecomposable injective modules. */
/* Injective module, injective hull of quotient:  every indecomposable injective module over a commutative Noetherian ring R is isomorphic to the injective hull of a module of the form R/p for some prime ideal p of R. This establishes a powerful correspondence between indecomposable injective modules and prime ideals. */
/* Injective module, flabby sheaf:  flabby sheaf, any section over open subset can be extended as a section over the full space. Geometric parallel to homomorphism extension property of injective modules */
/* Injective modules, divisibility has no holes:  divisible module, all elements can be divided by any nonzero ring element, module has no holes that prevent division */
/* Injective module, space of functions:  space of functions with no constraint on domain extension, corresponds to sections over opens becoming sections over the whole space */
/* Injective module, definition via corepresenting object: Q is injective object if corepresenting Hom(-, Q) maps monomorphisms to epimorphisms, formally dual for projective modules */
/* Injective module, direct products:  direct product of any family of injective modules is an injective module. The corresponding property for direct sums holds only for Noetherian rings. */
/* Injective module, no proper essential extensions:  module Q is injective if and only if it has no proper essential extensions. An essential extension of a module M is a module N containing M as a submodule, such that every nonzero submodule of N has a nonzero intersection with M. */
/* Injective module, injective hull of any module:  module M has a minimal injective module containing it, called its injective hull, denoted E(M). A module Q is injective if and only if it is its own injective hull. The injective hull is an essential extension, meaning Q is an essential submodule of E(Q). */
/* Injective module, divisible module:  integral domain R, a module Q is injective if and only if it is divisible. A module M is divisible if for every nonzero element r in R and every m in M, there exists n in M such that rn in m. For example, the rational numbers Q are an injective Z-module. */
/* Injective module, injective resolution: 0 to M to I_0 to I_1, I_i all injective modules */
/* Injective module, splitting of short exact sequence: 0 -> Q -> M -> N -> 0 is split exact, M is isomorphic to direct sum of Q and N, Q is injective module, N is projective module */
/* Injective module, homomorphism extension:  TFAE: (1) Q is injective module; (2) injective if for any submodule A of an R-module B, and any homomorphism f : A to Q, there exists an extension homomorphism g: B to Q such that g restricted to A is homomorphism f. */
/* Swan's theorem, definition of finitely generated projective module:  concrete definition of a finitely generated projective module over the ring of continuous functions as being a topological vector bundle. */
/* Swan's theorem, ring of continuous functions:  base ring for the theorem is a commutative ring C(X) of real-valued, continuous functions on a compact Hausdorff space X */
/* Swan's theorem, topological vector bundle:  topological vector bundle is a topological space E together with a continuous projection map p: E to X, such that each fiber p−1(x) has the structure of a real vector space, and the structure is locally trivial. */
/* Swan's theorem, local triviality:  "local triviality" of a vector bundle is precisely the topological analog of a finitely generated projective module being locally free, a key component of the algebraic definition. */
/* Swan's theorem, equivalence of categories:  functor F from the category of vector bundles to the category of finitely generated projective modules, and a functor G in the other direction, such that FG and GF are naturally isomorphic to the identity functors. */
/* Swan's theorem, functorial correspondence:  functor F maps a vector bundle E to the module of its continuous sections, denoted Γ(X,E). This is a module over the ring of continuous functions C(X). */
/* Swan's theorem, module from sections:  module Γ(X,E) is finitely generated and projective because the vector bundle is locally trivial. A partition of unity is used to piece together local trivializations to construct a global set of generators. */
/* Swan's theorem, sheaf of modules:  functorial correspondence can be viewed as an equivalence between the category of finitely generated projective modules and the category of locally free sheaves of finite rank. */
/* Swan's theorems, analytic interpretation:  algebraic structure of a finitely generated projective module is sufficient to capture all the topological information of a vector bundle. */
/* Swan's theorems, generalisation of trivial bundles:  Swan's theorem shows that trivial bundles correspond to free modules, and non-trivial bundles correspond to non-free projective modules. For instance, the tangent bundle of the 2-sphere is a non-trivial vector bundle, and its corresponding module is a non-free projective module. */
/* Swan's theorems, Serre-Swan theorem:  similar equivalence for smooth manifolds and the ring of smooth functions. This connects differential geometry to algebra. */
/* Swan's theorem, perfect complex:  perfect complex is a chain complex of modules that is locally quasi-isomorphic to a finite complex of free modules. It is the correct homotopical generalization of a finitely generated projective module. */
/* Swan's theorem, higher category:  stable ∞-category of vector bundles to the stable ∞-category of perfect complexes. */
/* Swan's theorem, homotopy theory of vector bundles:  vector bundles are objects that classify maps into Grassmannians. Swan's theorem can be viewed as an algebraic interpretation of the homotopy theory of these classifying spaces. */
/* Swan's theorem, topological K-theory:  starting point for topological K-theory, which is a cohomology theory built from vector bundles. The algebraic counterpart is algebraic K-theory, built from finitely generated projective modules. */
/* Vector bundle, vector space fibres:  vector bundle is a specific type of fiber bundle where the fibers are vector spaces. It consists of a total space E, a base space X, and a projection map p: E to X */
/* Vector bundle, locally trivial, visual intuition is open subset is Cartesian producted with a copy of the R^n (example for visual imagination is R^1):  for every point x in the base space X, there is a neighborhood U and an isomorphism fibres over U to be isomorphic U × R^n, which is a local trivialization. */
/* Vector bundle, transition functions:  local trivializations on overlapping neighborhoods are related by transition functions, which are continuous maps from the overlap to the general linear group GLn​(R) */
/* Vector bundle, continuous sections:  continuous section of a vector bundle is a continuous map s: X to E such that p * s is the identity map on X. The set of all continuous sections forms a module over the ring of continuous functions on X. */
/* Vector bundle, rank:  rank of a vector bundle is the dimension n of the vector space fibers. A rank 1 bundle is a line bundle. Recall that rank is output of linear map is dimensional 1. */
/* Vector bundle, trivial:  trivial if it is globally isomorphic to a product space X × R^n. This is the simplest type of vector bundle, and its continuous sections correspond to a free module. */
/* Vector bundle, subbundle:  sub-space of a vector bundle that is itself a vector bundle. Its continuous sections form a submodule. */
/* Vector bundle, pullback bundle:  pullback of a vector bundle along a map f: Y → X is a new vector bundle over the space Y, which gives a way to "transport" the bundle's structure. */
/* Vector bundle, Whitney sum:  two vector bundles E1​ and E2​ over the same base space X is a new vector bundle E1​ ⊕ E2​ whose fibers are the direct sums of the fibers of the original bundles. */
/* Vector bundle, classification:  Vector bundles of rank n on a space X are classified by homotopy classes of maps from X to the Grassmannian manifold G_n​(R^∞). */
/* Vector bundle, locally free sheaf:  algebraic analog of a vector bundle is a locally free sheaf. A sheaf of modules is locally free if every point in the scheme has a neighborhood where the sheaf is isomorphic to a free sheaf of finite rank. */
/* Vector bundle, Serre-Swan:  compact topological space X, the category of continuous vector bundles on X is equivalent to the category of finitely generated projective modules over the ring of continuous functions C(X). */
/* Vector bundle, projective module:  Swan's theorem provides an algebraic definition of a vector bundle: it's a finitely generated projective module. This allows us to use the tools of commutative algebra to study geometric objects. */
/* Vector bundle, flat modules:  vector bundle corresponds to a finitely presented flat module. This is a weaker condition than projective, and it is the correct algebraic counterpart for schemes that are not regular. */
/* Vector bundle, on schemes:  vector bundle over a scheme is defined as a locally free sheaf of modules of constant finite rank. This directly translates the topological definition into the language of algebraic geometry. */
/* Vector bundle, perfect complex:  chain complex of modules that is locally quasi-isomorphic to a finite complex of free modules. This object captures the "homotopical" nature of vector bundles. */
/* Vector bundle, line bundle:  vector bundle of rank 1 is a line bundle. In algebraic geometry, these correspond to invertible sheaves, which are key to studying divisors and rational maps. */
/* Vector bundle, torsor:  vector bundle is a torsor under a group scheme. For a line bundle, this is an algebraic version of a principal bundle. */
/* Vector bundle, algebraic:  algebraic vector bundle on a scheme is a coherent sheaf that is locally free. */
/* Vector bundle, Grothendieck group:  set of isomorphism classes of vector bundles over a topological space X forms an abelian group called the topological K-theory group K_0​(X) under the Whitney sum operation. The algebraic counterpart is the Grothendieck group K_0​(R) of a ring, which is generated by finitely generated projective modules. */
/* Bundle, Grothendieck fibration:  Grothendieck fibration is a functor p: E → B that has a lifting property for morphisms, analogous to lifting paths in a topological space. The category E is the total category, and B is the base category. */
/* Bundle, fiber of fibration:  object B in the base category B, the fiber is the subcategory of the total category E whose objects map to B and whose morphisms map to the identity morphism of B. */
/* Bundle, local triviality:  categorical bundle is locally trivial if it can be "trivialized" by pulling back to a simpler form over a "local" part of the base category. This corresponds to the existence of cartesian sections. */
/* Bundle, section of fibration:  section of a fibration p: E → B is a functor s: B → E such that p∘s is the identity functor on B. Sections are the categorical analogs of continuous sections of a vector bundle. */
/* Bundle, classifying space:  base category of a categorical bundle can be seen as a kind of classifying space for the fibers. This generalizes the concept of a classifying space for a topological group. */
/* Bundle, category of elements:  category of elements is a category whose objects are pairs (B,X), where B is an object of B and X is an object of the category F(B). This construction provides a standard way to form a fibration. */
/* Bundle, right fibration:  functor is a right-fibration if it has a specific lifting property for all morphisms in the base category, in a "right" direction. This is a common type of categorical bundle. */
/* Bundle, modules:  module M over a ring R can be seen as a categorical bundle over the base category with a single object and one morphism, which represents the ring. The "fibers" are the elements of the module. */
/* Bundle, sheaves:  sheaf of modules on a topological space or a scheme can be interpreted as a categorical bundle over the category of open sets of the space. The fibers are the stalks of the sheaf. */
/* Bundle, fibre functor:  functor that sends a vector bundle to the module of its sections can be seen as a fiber functor that generalizes the idea of a fiber in a topological bundle. */
/* Quasicoherent sheaf, sheaf of OX modules that is locally isomorphic to R-module:  quasicoherent sheaf on a scheme X is a sheaf of OX​-modules that is locally isomorphic to the sheaf associated with an R-module. It's the correct way to transport module theory to a geometric setting. */
/* Quasicoherent sheaf, sheaf from a module:  ring R, every R-module M gives rise to a quasicoherent sheaf M on the affine scheme Spec(R). */
/* Quasicoherent sheaf, module functor:  associating a sheaf to a module, the quasicoherent sheaf M~, defines a functor from the category of R-modules to the category of quasicoherent sheaves on Spec(R). This functor is an equivalence of categories. */
/* Quasicoherent sheaf, local isomorphism on the level of stalks:  sheaf F is quasicoherent if for every point x in scheme X, there exists an affine open neighborhood U = Spec(R) of x and an R-module M such that the section on the open neighbourhood F_U is locally isomorphic to the quasicoherent sheaf M-. */
/* Quasicoherent sheaf, global module patching modules over local rings:  "global module" that is constructed by patching together modules over local rings. */
/* Quasicoherent sheaf, compared to coherent sheaf:  quasicoherent sheaf is coherent if it is locally isomorphic to a sheaf associated with a finitely presented module. Coherent sheaves are the geometric counterparts of finitely presented modules, whereas quasicoherent sheaves correspond to all modules. */
/* Quasicoherent sheaf, pushforward of a module using structural morphism of affine scheme:  quasicoherent sheaf on a scheme can be defined by the pushforward of an R-module under the structural morphism from an affine scheme to the given scheme. */
/* Quasicoherent sheaf, visual analogy as space of functions:  quasicoherent sheaf can be visualized as a "space of functions" on a scheme, where the "functions" are sections that are defined locally and glued together. */
/* Quasicoherent sheaf, on the level of stalks:  stalk: localisation of module M at prime ideal p which is a local ring; section over U is isomorphic to quasicoherent sheaf M-; stalk of quasicoherent sheaf at a prime ideal p is localisation of module M at prime ideal p, which is a local ring */
/* Quasicoherent sheaf, homotopical derived quasicoherent sheaf:  sheaf whose stalk at every point is a complex of modules that is "homotopically quasicoherent," meaning it satisfies a local property in the stable homotopy category. */
/* Quasicoherent sheaf, derived quasicoherent sheaves that is locally quasi-isomorphic:  sheaf of complexes of modules that is locally quasi-isomorphic to a complex of modules over a ring. */
/* Quasicoherent sheaves, derived functors:  forming a derived quasicoherent sheaf from a module can be seen as a derived functor of the classical functor. */
/* Quasicoherent sheaf, stacks:  quasicoherent sheaves generalizes to stacks, where a quasicoherent sheaf on a stack is a more general type of a bundle that has symmetries. */
/* Locally free module, locally free object is analogous to product of base space and fibre, or fibration with contractible:  locally free object is analogous to a space that is a product of its base space and a fiber, locally. A fibration with a contractible fiber is analogous to a locally trivial bundle. */
/* Locally free module, classification leads to algebraic K-theory to measure farness from all modules being locally free:  classification of locally free modules (vector bundles) leads to algebraic K-theory. This is an ontology where we "measure" how far a ring is from having all its locally free modules be free. The Grothendieck group K0​(R) is a way to make the set of isomorphism classes of locally free modules into a group. */
/* Locally free modules, projective resolutions as generalisation of locally free module:  in homological algebra, we use projective resolutions to "resolve" (approximate) a module with a sequence of projective (or free) modules. This is a generalization of the idea that locally free modules are "like" free modules. */
/* Locally free modules, line bundles as locally free sheaf of rank 1: line bundle is a locally free sheaf of rank 1. Geometrically, it's a vector bundle where each fiber is a one-dimensional vector space. Think of the tangent bundle of a circle, which is a line bundle. */
/* Locally free module, tangent sheaf as locally free sheaf:  tangent sheaf of a scheme is a locally free sheaf that captures the infinitesimal behavior of the scheme. Its fibers are the tangent spaces at each point. This is a direct generalization of the tangent bundle of a manifold */
/* Rank, group of integers Z has a rank of 1, as it can be generated by the single element 1. You can visualize this on the number line, where every point can be reached by adding or subtracting 1. The rank tells you the "dimensionality" of the group in terms of its generating elements:  The rank of a group (or, more generally, an algebraic structure) is the minimum cardinality of a generating set. Visual intuition: The group of integers Z has a rank of 1, as it can be generated by the single element 1. You can visualize this on the number line, where every point can be reached by adding or subtracting 1. . The rank tells you the "dimensionality" of the group in terms of its generating elements. */
/* Rank, a matrix that transforms a space. For example, a 3×2 matrix A transforming R2 to R3. If the rank is 2, the two column vectors are linearly independent, and their span forms a 2-dimensional plane in R3. The rank tells you the dimension of the subspace that the matrix "lands" on. A rank-1 matrix would squash the entire space onto a line:  In linear algebra, the rank of a matrix is the dimension of its column space (or, equivalently, its row space). It's the maximum number of linearly independent columns. */
/* Rank, free module Z2 over the ring Z. Its basis is {(1,0),(0,1)}, so its rank is 2. This can be visualized as the integer grid in a 2D plane. . The rank tells you the "size" of the grid:  In homological algebra, the rank of a free module over a commutative ring is the size of its basis. Visual intuition: Consider the free module Z2 over the ring Z. Its basis is {(1,0),(0,1)}, so its rank is 2. This can be visualized as the integer grid in a 2D plane. . The rank tells you the "size" of the grid. */
/* Rank, L-function and the Birch and Swinnerton-Dyer conjecture relates the rank of an elliptic curve to the order of the zero of its L-function at s=1. We can visualize the L-function as a complex function and the rank as the number of times it "touches" zero at a specific point:  In arithmetic number theory, the rank of an L-function at a point is the order of the zero of the function at that point. Visual intuition: The Birch and Swinnerton-Dyer conjecture relates the rank of an elliptic curve to the order of the zero of its L-function at s=1. We can visualize the L-function as a complex function and the rank as the number of times it "touches" zero at a specific point. */
/* Rank, sheaf of regular functions on an affine variety. The stalk at a point P is the set of all regular functions defined in a neighborhood of P. The rank of this sheaf is 1 at every point:  In algebraic geometry, the rank of a sheaf is the dimension of the stalk of the sheaf at each point. Visual intuition: Consider the sheaf of regular functions on an affine variety. The stalk at a point P is the set of all regular functions defined in a neighborhood of P. The rank of this sheaf is 1 at every point. */
/* Rank, dimension of homology example, simplicial complex, like a hollow sphere. The homology group H2​ has rank 1, corresponding to the single "hollow" region. The rank tells you the number of independent "holes" of a given dimension:  In homological algebra, the rank of a chain complex is the dimension of its homology groups. Visual intuition: Consider a simplicial complex, like a hollow sphere. The homology group H2​ has rank 1, corresponding to the single "hollow" region. The rank tells you the number of independent "holes" of a given dimension. */
/* Rank, group algebra F2​[C3​] of the cyclic group of order 3. It has a basis {e,g,g2}, so its rank is 3. This is a vector space over a finite field. The rank is the number of elements in the basis:  In modular representation theory, the rank of the group algebra Fp​[G] is the dimension of the algebra as a vector space over Fp​, which is equal to the order of the group. Visual intuition: Consider the group algebra F2​[C3​] of the cyclic group of order 3. It has a basis {e,g,g2}, so its rank is 3. This is a vector space over a finite field. The rank is the number of elements in the basis. */
/* Rank, double pendulum. It has two degrees of freedom, the angles of the two pendulums. So its rank is 2. . The rank tells you the "number of dimensions" of the system's phase space:  In dynamical systems, the rank can refer to the number of independent "degrees of freedom" or "modes" of the system. Visual intuition: Consider a double pendulum. It has two degrees of freedom, the angles of the two pendulums. So its rank is 2. . The rank tells you the "number of dimensions" of the system's phase space. */
/* Rank, elliptic curve infinite number of rational points. The rank is the number of "independent" points that can generate all other points. For example, a rank-1 curve has a single point that, through the group law, can generate an infinite number of other points:  In arithmetic number theory, the rank of an elliptic curve E over Q is the rank of the group of rational points E(Q). It's the number of generators of the group modulo torsion. Visual intuition: Consider an elliptic curve with an infinite number of rational points. The rank is the number of "independent" points that can generate all other points. For example, a rank-1 curve has a single point that, through the group law, can generate an infinite number of other points. */
/* Rank, tangent bundle of a sphere. At each point on the sphere, there's a tangent plane. The dimension of this plane is 2, so the rank of the tangent bundle is 2. The rank tells you the dimension of the "fiber" over each point:  In algebraic geometry, the rank of a vector bundle is the dimension of the vector space associated with each point of the variety. Visual intuition: Consider the tangent bundle of a sphere. At each point on the sphere, there's a tangent plane. The dimension of this plane is 2, so the rank of the tangent bundle is 2. . The rank tells you the dimension of the "fiber" over each point. */
/* Rank, for 2×2 matrices with entries in Z, M2​(Z). The rank of the projective module M2​(Z) is the dimension of the space over the field of fractions of the ring, which is 4. This corresponds to the "dimension" of the matrix algebra:  in non-commutative ring theory, the rank of a finitely generated projective module P is a function that assigns a dimension to each prime ideal of the ring. Visual intuition: Consider the ring of 2×2 matrices with entries in Z, M2​(Z). The rank of the projective module M2​(Z) is the dimension of the space over the field of fractions of the ring, which is 4. This corresponds to the "dimension" of the matrix algebra. */
/* Rank, coboundary is a function that can be written as a difference of two other functions. The rank of the coboundary tells you the number of dimensions of the "space of differences":  In dynamics, the rank of a coboundary can be the dimension of the space of functions that are coboundaries. Visual intuition: A coboundary is a function that can be written as a difference of two other functions. The rank of the coboundary tells you the number of dimensions of the "space of differences". */
/* Rank, first homology group of a figure-eight space is Z⊕Z, which has a rank of 2. This corresponds to the two independent loops in the space. The rank is the number of loops:  In homotopy theory, the rank of a homology group Hn​(X) is the rank of its free part. Visual intuition: The first homology group of a figure-eight space is Z⊕Z, which has a rank of 2. This corresponds to the two independent loops in the space. . The rank is the number of loops. */
/* Rank, Lorenz attractor has a fractal dimension of approximately 2.06. This tells us how "space-filling" the attractor is. It's not a line (dimension 1) and not a plane (dimension 2), but something in between:  In dynamical systems, the rank of a strange attractor is its fractal dimension. Visual intuition: The Lorenz attractor has a fractal dimension of approximately 2.06. This tells us how "space-filling" the attractor is. It's not a line (dimension 1) and not a plane (dimension 2), but something in between. */
/* Automorphisms, Imagine the cyclic group Z6​ as a hexagon with vertices labeled 0,1,2,3,4,5. An automorphism is a permutation of the vertices that preserves the group operation of addition modulo 6. The identity map is a trivial automorphism. A nontrivial automorphism maps x→ − x (mod6), which corresponds to a reflection of the hexagon through a vertical axis. This reflection is a symmetry of the geometric shape that represents the group: A nontrivial automorphism of a group G is an isomorphism from G to itself that is not the identity map. It's a symmetry of the group's structure that shuffles its elements. For example, the group Z8​ of integers modulo 8 has an automorphism that maps every element to its opposite, x to −x, which is not the identity. */
/* Automorphisms, projective line P1. Its automorphisms are given by fractional linear transformations. These are transformations of the line that are not the identity. For example, the map z↦1/z is a nontrivial automorphism. This corresponds to a geometric transformation that takes the point at infinity to zero and vice versa, and permutes other points. This is a symmetry of the projective line itself: A nontrivial automorphism of an algebraic variety X is an isomorphism from X to itself that is not the identity map. This is a geometric symmetry of the variety. The group of all automorphisms is denoted Aut(X). For example, a smooth cubic curve in the projective plane has a group of automorphisms. */
