/* Additive / abelian categories, nice properties on monomorphisms:  on monomorphisms, very nice to have kernels, monomorphisms and monics be basically the same on some level in additive / abelian categories, see Weibel's Homological Algebra. Furthermore, the existence of zero object very important, Hom functor is right adjoint, preserving limits, need something like AB4 i.e. cocompleteness to have direct sums preserved as well. */
/* Additive / abelian categories, nice exactness correspondence:  let C and D be abelian categories, F be functor from C to D, G be functor from D to C, additive functor given isomorphism of bifunctors, Hom_D(FX, Y) = Hom_C(X, GY), F is left adjoint to G, G is right adjoint of F, then F is right exact and G is left exact (see Gelfand and Manin's Homological Algebra). I am not sure if you need abelian categories to establish this. */
/* Adjoints, clarifying relationship between right shift and left shift operators:  adjunction of right shift operator gives left shift operator, suppose we have s_r x = (0, x1, x2, ...) and maps s_r from l^2 to l^2 discretised Hilbert spaces, then we have s_r^* = s_l since we can see that s_r^* y = (y2, y3, y4, ...). We have that (s_r x, y) = (x, s_r^* y) or that the the right shift operator x is left adjoint to the left shift operator on y. */
/* Adjoints, limit preservations:  the proof is from nlab, start with the natural isomorphism of adjoint functors (intuition comes from integration, Riesz representation, but with homs). Use the definition of adjunction, we have for a category C and D, a functor L and R (left and right adjoint functors), and objects c and d, HomC(L(d), c) is naturally isomorphic to HomD(d, R(c)) by definition. You will want to show c to be the limit, since R is the right adjoint. The second thing is that Hom functors preserve limits. Lastly, apply Yoneda's lemma, the natural isomorphism of Hom sets of objects give isomorphism of objects. Apply the first definition of natural isomorphism, to second to somehow take out the limit c as a representing object. Apply Yoneda's lemma in reverse, the limits are preserved and are naturally isomorphic under action of right adjoints. This theorem is formally dual for colimits, so left adjoints must preserve colimits. Note that due to much thought devoted to the Yoneda embedding, it is more customary to see the right adjoint version due to the application (and then reversal) of Yoneda's lemma here. */
/* Kernel, inverse image of identity in group:  inverse image of identity element */
/* Kernel, equivalence class of zero:  Kernel is set of all elements mapped to 0 in codomain */
/* Kernel, as a fibre:  Kernel is fibre of identity element */
/* Kernel, normal subgroup:  Only subgroup that is the kernel of a group homomorphism */
/* Kernel, set of trivial elements:  Set of elements trivial with respect to the given group homomorphism, losing distinctiveness mapping to identity */
/* Kernel, basis of partition:  Cosets of kernel form a partition of the domain group, each coset is fibre of homomorphism */
/* Kernel, quotient group generator:  Quotient group G/ ker(f) is isomorphic to image of homomorphism */
/* Kernel, morphism induced subgroup:  Kernel is subgroup induced solely by a group homomorphism */
/* Kernel, object in category:  Captures the difference between a morphism and identity morphism */
/* Kernel, for a free group:  Kernel of a homomorphism from a free group is a set of all relations that must be satisfied by its generators */
/* Kernel, information loss:  Measure of information loss from domain to image group, larger the kernel, the more information is lost. */
/* Cokernel, unreachable elements:  represents the set of elements in the codomain that cannot be expressed as the image of any element in the domain. */
/* Cokernel, codomain partition:  cokernel, partition of codomain W into disjoint affine subspaces, cosets of the image subspace Im(f) */
/* Cokernel, equivalence class:  Equivalence classes of elements where elements are equivalent if their difference is in the image of the map */
/* Cokernel, fibre for space of fibres of projection map W to W/Im(f):  consider the space of fibres of the projection map W to W/Im(f) we have each element of the cokernel is a fibre (a coset) */
/* Cokernel, quotient space:  Quotient space measures how far the map is from being surjective */
/* Cokernel, final object:  Final object in a commutative diagram */
/* Cokernel, codomain of canonical projection:  codomain of canonical projection map p: W -> coker(f) */
/* Cokernel, information gain:  Kernel measures info loss from domain, cokernel measures information gain in domain that is not explained by the group homomorphism */
/* Cokernel, homomorphic collapse:  Collapse image to single point (zero vector), residue of codomain is cokernel */
/* Colimit, generative ontology:  colimit is the most general object that can be constructed from a given diagram. It contains all the information from the diagram without adding any new relations. */
/* Colimit, free object:  colimit is a free object subject to a set of relations. It is the most general solution to a given set of constraints. */
/* Colimit, disjunction:  colimit models a logical disjunction or "or" condition. For example, a coproduct of two objects can be thought of as a way to "either have this or that." */
/* Colimit, opposite category:  colimit in a category C is a limit in the opposite category Cop. This powerful duality allows you to use intuition about limits (like products and equalizers) to understand colimits. */
/* Colimit, sum or union:  colimit is a generalization of the disjoint union of sets or the direct sum of abelian groups. The colimit "ignores" the shared structure and puts everything together. */
/* Colimit, quotient:  Generalisation for quotient, example coequalisers models a quotient. */
/* Colimit, final object: A colimit is a final object in the category of all cocones over a given diagram. */
/* Colimit, glue:  colimit is the formal way to "glue" together a collection of objects and the maps between them into a single, cohesive object. */
/* Limit, intersection of sets:  limit is a generalization of the intersection of sets. For example, a product is a kind of limit that acts like a Cartesian product, and a pullback acts like an intersection. */
/* Limit, generalisation of product:  limit is a generalization of the Cartesian product of sets, the direct product of groups, or the product of topological spaces. */
/* Limit, conjunction:  limit models a logical conjunction or "and" condition. For example, a product of two objects can be thought of as a way to have "this and that" simultaneously. */
/* Limit, fixed point:  limit can be seen as a kind of fixed point for an iterative process of converging to a final, stable object. */
/* Limit, abstraction:  limit is the ultimate tool for abstraction. It allows us to forget the internal structure of objects and diagrams and focus only on the universal relationship to the limit object. */
/* Limit, projective property:  limit is an object that has a projective property with respect to the diagram. Every object that has a map to all the objects in the diagram must have a unique map that factors through the limit. */
/* Limit, canonical representative object:  limit is the canonical object that represents a family of objects and morphisms. Any two limits of the same diagram are uniquely isomorphic, highlighting its canonicity. */
/* Limit, representable cone functor:  limit can be understood as an object that represents a functor (the cone functor) from the category of diagrams to the category of sets. This perspective is foundational in higher category theory. */
/* Internal hom, object in category:  set of morphisms from A to B */
/* Internal hom, universal property of relevant adjunction:  Tensor hom adjunction is universal property */
/* Internal hom, representable functor:  Functor Hom(A * -, B) is represented by Hom(A, B), natural isomorphism between object C to Hom(A,B) and the set of morphisms from A * C to B, */
/* Internal hom, exponential object in Cartesian closed category:  exponential object, denoted B^A */
/* Internal hom, function object:  object of functions from A to B within the category */
/* Internal hom, hom module over a ring R: the hom module Hom_R(M,N) set of R-linear maps from module M to module N */
/* Internal hom, as module of homomorphisms over a ring R: Hom_R(M,N) is an R-module, defined by (rf)(m) = r(f(m)) */
/* Internal hom, functorial hom:  Bifunctor Hom_R(-,-) is product category of R-modules to category of R-modules, contravariant in the first variable, covariant in second */
/* Internal hom, enriched category theory:  an internal hom value of hom functor in an enriched category, it is a hom object */
/* Internal hom, morphism space:  space of morphism between two objects in a category */
/* Internal hom, local hom-functor:  sheaf of hom-modules for sheaves of modules on a scheme */
/* Internal hom, local Hom-functor: a local Hom-functor is a sheaf of Hom-modules for sheaves of modules on a scheme, local version of global internal hom */
/* Internal hom, exponential law:  (B^C)^A is isomorphic to (B^{C tensor A}}, holds for internal hom */
/* Internal hom, closed:  category is closed if it has an internal hom */
/* Internal hom, dual of hom module:  dual of module M is Hom_R(M, R) */
/* Internal hom, inner product:  Hom can be treated like an inner product Hom_R(R, M) = M is dual to Hom_R(M, R) */
/* Internal hom, corepresenting object:  Hom(A-B) corepresents functor Hom(A * -, B) */
/* Pushout, gluing roads at starting point:  pushout of two morphisms f:S→X and g:S→Y is an object P together with morphisms p1​:X→P and p2​:Y→P that satisfy a universal property. Imagine two roads, X and Y, both starting from a common point, S. The pushout is the space you get by gluing the two roads together at their starting point. */
/* Pushout, gluing of disjoint unions in the category of Set:  category of sets, the pushout is the quotient of the disjoint union of X and Y by the equivalence relation generated by f(s)∼g(s). Visual Intuition: You're taking two sets and "gluing" them together at a common sub-set. */
/* Pushout, gluing of common boundary:  pushout is a quotient of the disjoint union space. Visual Intuition: You're taking two spaces and "gluing" them together along a common boundary. */
/* Pushout, pushforward local data:  pushout of a sheaf is a way to "push forward" the local data of a sheaf from one space to another. Visual Intuition: You're taking a sheaf on one space and creating a new sheaf on another space that is compatible with the original one. */
/* Pullback, addresses in third subspace for topology given a product space in category of topological space:  category of topological spaces, a pullback is a subspace of the product space, with the subspace topology. */
/* Pullback, fibre product of two roads:  pullback (or fiber product) of two morphisms f:  X →  S and g: Y → S is an object P together with morphisms p1​: P → X and p2​: P → Y that satisfy a universal property. Visual Intuition: Imagine two roads, X and Y, both leading to a city, S. The pullback is the intersection of these roads. It's the set of all pairs of points (x,y) such that f(x)=g(y). */
/* Pullback, transportation of bundles pullback of vector bundles:  pullback of a vector bundle is a way to "transport" a bundle from one space to another. Imagine a bundle of lines on a surface. If you have a map from a circle to the surface, the pullback bundle is a bundle of lines on the circle. You're pulling the geometry of the bundle back to the circle. */
/* Pullback, restriction and pulling back to scalar multiplication of R via a ring homomorphism:  ring homomorphism ϕ: R → S, the pullback of an S-module M is an R-module. Visual Intuition: You're taking an S-module and making it an R-module by "restricting" the scalar multiplication to R. */
/* Filtered colimit, limit over directed set, sequence of nested intervals on the real line: I1​=[0,1], I2​=[0,1.5], I3​=[0,1.75], and so on, with the maps being the inclusion maps. The filtered colimit of this system is the interval [0,2]:  In category theory, a filtered colimit (or direct limit) is a construction that takes a "directed system" of objects and maps and produces a single object that is, in a sense, the "union" of all the objects in the system. The index set of the system must be a filtered category, meaning for any two objects, there is a third object that can be reached from both via a map. Visual Intuition: Consider a sequence of nested intervals on the real line: I1​=[0,1], I2​=[0,1.5], I3​=[0,1.75], and so on, with the maps being the inclusion maps. The filtered colimit of this system is the interval [0,2]. . The filtered colimit is the object that "contains" all the objects in the sequence, just like the interval [0,2] contains all the In​. It's the "ultimate" object that everything in the system maps into. */
/* Filtered colimit, system of spheres S0 in S1 in S2 in … where the inclusions are defined by mapping the sphere of dimension n to the "equator" of the sphere of dimension n+1. The filtered colimit of this system is the infinite-dimensional sphere Sinfty:  In topology, a filtered colimit of a filtered system of topological spaces is a topological space whose points are the equivalence classes of the disjoint union of the spaces, and whose topology is the final topology. Visual Intuition: Consider the system of spheres S0 in S1 in S2 in… where the inclusions are defined by mapping the sphere of dimension n to the "equator" of the sphere of dimension n+1. The filtered colimit of this system is the infinite-dimensional sphere Sinfty. . The infinite sphere is a space that is "built up" by taking the union of all finite-dimensional spheres. */
/* Filtered colimit, sequence of affine schemes Xn​=Spec(k[x]/x^n), which are "thickenings" of the origin in the affine line. The maps are the natural inclusions. The filtered colimit of this system is the formal scheme Spec(k[[x]]):  In algebraic geometry, a filtered colimit of a filtered system of schemes is a new scheme whose coordinate ring is the filtered colimit of the coordinate rings of the schemes in the system. Visual Intuition: Consider a sequence of affine schemes X^n​=Spec(k[x]/x^n), which are "thickenings" of the origin in the affine line. The maps are the natural inclusions. The filtered colimit of this system is the formal scheme Spec(k[[x]]). . The formal scheme is a "microscopic" neighborhood of the origin that is "built up" by taking the limit of all its finite thickenings. */
/* Filtered colimit, system of modules Z/2Z→Z/4Z→Z/8Z→… where the maps are the natural inclusions. The filtered colimit of this system is the group of 2-adic integers Z2​:  In homological algebra, a filtered colimit of a filtered system of modules is a new module whose elements are equivalence classes of elements from the original modules. Visual Intuition: Consider the system of modules Z/2Z→Z/4Z→Z/8Z→… where the maps are the natural inclusions. The filtered colimit of this system is the group of 2-adic integers Z2​. . The 2-adic integers can be seen as the "ultimate" object that "absorbs" all the Z/2nZ. It is a way of "completing" the system. */
/* Filtered colimit, system of matrix rings M2​(C) to M4​(C) to M8​(C) to … where the maps are block-diagonal inclusions. The filtered colimit of this system is the infinite-dimensional matrix algebra:  In non-commutative ring theory, a filtered colimit of a filtered system of rings is a new ring whose elements are equivalence classes of elements from the original rings. Visual Intuition: Consider the system of matrix rings M2​(C) to M4​(C) to M8​(C) to … where the maps are block-diagonal inclusions. The filtered colimit of this system is the infinite-dimensional matrix algebra. This infinite matrix algebra is the "ultimate" object that contains all finite-dimensional matrix algebras as a subalgebra. */
/* Filtered colimit, sequence of modules M1​ in M2​ in M3​ in … over a group algebra Fp​[G]:  In modular representation theory, a filtered colimit can be a way to describe the "ultimate" module that is a direct limit of a system of modules over a group ring. Visual Intuition: Consider a sequence of modules M1​ in M2​ in M3​⊂… over a group algebra Fp​[G]. The filtered colimit is a new module M∞​ that is the union of all the modules in the sequence. This is a way of "building up" a large, complicated module from smaller, simpler ones. */
/* Filtered colimit, system of polynomial rings k[x] to k[x,y] to k[x,y,z] to …. The filtered colimit of this system is the polynomial ring in infinitely many variables k[x1​,x2​,…]:  In commutative algebra, a filtered colimit of a filtered system of commutative rings is a new ring whose elements are equivalence classes of elements from the original rings. Visual Intuition: Consider the system of polynomial rings k[x] to k[x,y] to k[x,y,z] to …. The filtered colimit of this system is the polynomial ring in infinitely many variables k[x1​,x2​,…]. This is a way of "building up" a huge ring from a sequence of smaller ones. */
/* Cofiltered limit, sequence of nested intervals on the real line: I1​=[0,1], I2​=[0,1/2], I3​=[0,1/4], and so on, with the maps being the inclusion maps. The cofiltered limit of this system is the single point {0}:  In category theory, a cofiltered limit (or inverse limit) is a construction that takes a "directed system" of objects and maps and produces a single object that is, in a sense, the "intersection" of all the objects in the system. The index set of the system must be a cofiltered category, meaning for any two objects, there is a third object that has a map to both. Visual Intuition: Consider a sequence of nested intervals on the real line: I1​=[0,1], I2​=[0,1/2], I3​=[0,1/4], and so on, with the maps being the inclusion maps. The cofiltered limit of this system is the single point {0}. The cofiltered limit is the object that is "contained" within all the objects in the sequence, just like the point {0} is contained in all the In​. It's the "ultimate" object that everything in the system maps from. */
/* Cofiltered limit, system of spheres with a fixed point Sn where the maps are the constant maps from Sn+1 to Sn. The cofiltered limit of this system is the infinite-dimensional sphere S∞ with a fixed point:  In topology, a cofiltered limit of a cofiltered system of topological spaces is a topological space whose points are coherent sequences of points from the original spaces. Visual Intuition: Consider the system of spheres with a fixed point Sn where the maps are the constant maps from Sn+1to Sn. The cofiltered limit of this system is the infinite-dimensional sphere S∞ with a fixed point. This is a way of "building up" a space by taking the intersection of all the spheres. It's the "ultimate" object that everything in the system maps into. */
/* Functor of points, imagine the affine line A1 as a set of points. The functor of points view says, don't look at the points, look at all the maps into the line. A map from a scheme T to A1 is just a function on T. The functor of points for A1 is the rule that says, for any ring R, give me the set of all polynomials with coefficients in R. This is a "generalized" way of viewing the line:  The functor of points perspective views a scheme X not as a set of points, but as a rule that assigns a set of maps to X from any other scheme T. This rule is a functor from the category of schemes to the category of sets, denoted as Hom(−,X). This allows one to study a scheme by studying its relationship with all other schemes, providing a more robust and flexible definition of a "geometric object." For example, the affine line A1 is the functor that assigns to each ring R the set of its elements. */
/* Functor of points, group Z as a number line. The functor of points view says, don't look at the numbers, look at all the maps into the number line. A map from a group H to Z is a homomorphism. This is a "generalized" way of viewing the group:  In group theory, a group G can be viewed as a functor of points. This functor assigns to each group H the set of all group homomorphisms from H to G. This generalizes the idea of a group as a set with a multiplication rule. It is a more abstract way of thinking about groups. For example, the group Z is the functor that assigns to each group H the set of its elements. */
/* Functor of points, a chain complex as a tower of vector spaces. The functor of points view says, don't look at the spaces, look at all the maps into the tower. A map from a chain complex D*​ to C*​ is a chain map. This is a "generalized" way of viewing the chain complex:  In homological algebra, a chain complex C*​ can be viewed as a functor of points. This functor assigns to each chain complex D*​ the set of all chain maps from D*​ to C*​. This generalizes the idea of a chain complex as a sequence of modules with maps between them. */
/* Functor of points, ring as a space with a non-commutative multiplication rule. The functor of points view says, don't look at the points, look at all the maps into the space. A map from a ring S to R is a ring homomorphism. This is a "generalized" way of viewing the ring:  In non-commutative ring theory, a ring R can be viewed as a functor of points. This functor assigns to each ring S the set of all ring homomorphisms from S to R. This generalizes the idea of a ring as a set with two operations. */
/* Functor of points, a group algebra as a geometric object. The functor of points view says, don't look at the points, look at all the maps into the object. A map from an algebra A to kG is an algebra homomorphism:  In modular representation theory, a group algebra kG can be viewed as a functor of points. This functor assigns to each algebra A the set of all algebra homomorphisms from A to kG. This generalizes the idea of a group algebra as a ring with an action of a group. */
/* Functor of points, sphere. The functor of points view says, don't look at the points, look at all the maps into the sphere. A map from a space Y to the sphere is a continuous map. This is a "generalized" way of viewing the sphere:  In homotopy theory, a topological space X can be viewed as a functor of points. This functor assigns to each topological space Y the set of all continuous maps from Y to X. This generalizes the idea of a topological space as a set with a topology. */
/* Functor of points, a number field as a space of numbers. The functor of points view says, don't look at the numbers, look at all the maps into the space. A map from a field L to K is a field homomorphism. This is a "generalized" way of viewing the number field:  In arithmetic number theory, a number field K can be viewed as a functor of points. This functor assigns to each field L the set of all field homomorphisms from L to K. This generalizes the idea of a number field as a field extension of Q. */
/* Functor of points, a dynamical system as a flow on a manifold. The functor of points view says, don't look at the flow, look at all the maps that preserve the flow. A map from a dynamical system (Y,g) to (X,f) is a map that commutes with the dynamics. This is a "generalized" way of viewing the dynamical system:  In dynamics, a dynamical system (X,f) can be viewed as a functor of points. This functor assigns to each dynamical system (Y,g) the set of all maps that preserve the dynamics. This generalizes the idea of a dynamical system as a space with a map. */
/* Functor of points, projective space as a space of lines through the origin. The functor of points view says, don't look at the lines, look at all the maps into the space. A map from a scheme T to Pn is a line bundle on T. This is a "generalized" way of viewing projective space:  The functor of points for projective space Pn assigns to each ring R the set of all "line bundles with a basis" on Spec(R). This is a very abstract way of defining projective space. */
/* Functor of points, derived functor is a functor that is a "homological" version of a normal functor. The functor of points view is a way of "seeing" this:  The concept of a functor of points can be used to define derived functors. A derived functor is a functor that is "homological." The functor of points view is a way of "seeing" the derived functors. */
/* Functor of points, a module as a vector space with a ring action. The functor of points view says, don't look at the points, look at all the maps into the space. A map from a module N to M is a module homomorphism:  In non-commutative ring theory, a module M can be viewed as a functor of points. This functor assigns to each module N the set of all module homomorphisms from N to M. This generalizes the idea of a module as a vector space with a ring action. */
/* Functor of points, a module as a geometric object. The functor of points view says, don't look at the points, look at all the maps into the object. A map from a module N to M is a module homomorphism:  In modular representation theory, a module M over a group algebra kG can be viewed as a functor of points. This functor assigns to each kG-module N the set of all module homomorphisms from N to M. */
