/* Brauer group, twisted field:  Twisting of multiplication that prevents an algebra from being a matrix ring over 1 */
/* Brauer group, equivalence class:  The Brauer group is a set of equivalence classes of central simple algebras. The ontology is not about individual algebras, but about their collective properties, specifically their similarity to a matrix algebra. */
/* Brauer group, operation is tensor product:  Addition is tensor product of algebras, elements are Morita equivalence classes of simple algebras over K. Classify division algebras over a field, and build them with tensor products. */
/* Brauer group, divsion algebra group:  Group of division algebras up to matrix equivalence */
/* Brauer group, cohomology group:  H^2(G, F^x) for Galois group X, field under multiplication F */
/* Brauer group, matrices:  Brauer group classifies algebras that become matrix algebra after field extensions */
/* Brauer group, number theory:  Classify algebra over number fields by looking at completions */
/* Brauer group, Azumaya algebras:  set of all possible ways to define a sheaf of Azumaya algebras on an algebraic variety, or the isomorphism classes of Azumaya algebras under Morita equivalence */
/* Brauer group, dimension:  Classifies algebras based on dimension over the field */
/* Brauer group, meaning of central simple:  simple means no non-trivial two sided ideals, central means center is base field */
/* Brauer group, splitting field:  splitting field is field extension that turns central simple algebra into matrix algebras */
/* Brauer group, obstruction to commutativity:  measures obstruction to commutative rings. An element is in the trivial class if and only if its corresponding algebra is a matrix ring over the base field, a commutative object. */
/* Brauer group, cohomological Galois extensions:  encodes Galois extension information using cocycle conditions */
/* Brauer group, group of 2-cocycles:  H^2(G, F^x) means group of 2 cocycles of Galois group of separable closure *//* Artin reciprocity, Consider the extension Q(i)/Q with Galois group Gal(Q(i)/Q) isomorphic to C^2​={1,σ}, where σ is complex conjugation. The prime ideals in Z[i] are defined by their norms. Primes p in Z that are congruent to 1(mod4) split, like 5=(2+i)(2−i). The Artin map sends the ideal (2+i) to the identity element. Primes congruent to 3(mod4) remain inert, like 3. The Artin map sends the ideal (3) to the non-trivial element σ. This can be visualized on a "number lattice" in the complex plane,where the primes are points. The Artin map acts like a filter, sending some points (the split primes) to "do nothing" (identity) and others (the inert primes) to "flip" the lattice (complex conjugation):  The Artin map is a homomorphism from the group of fractional ideals of a number field K to the Galois group of an abelian extension L/K. It's a central object in class field theory that connects the arithmetic of K (ideals) with the Galois theory of L. It sends a prime ideal p to its corresponding Frobenius element in the Galois group. */
/* Artin reciprocity, consider an algebraic curve defined over Fq​. The geometric points of this curve can be thought of as a graph, where the edges connect points that are conjugates under the Frobenius map. The étale fundamental group, π1et​(X), can be imagined as the group of all loops on this graph, allowing for "jumping" between fields. The Frobenius automorphism acts on this graph, moving points around. Artin reciprocity says that the action of the Frobenius element on these loops is the same as the action of the Galois group of the function field:  In algebraic geometry, for a smooth, connected, and proper curve X over a finite field Fq​, the geometric Frobenius automorphism acts on the geometric points of X. The Artin reciprocity law is a statement about how the action of this Frobenius element on the étale fundamental group of X relates to the action of the Galois group of the function field of Xon the field of functions. */
/* Artin reciprocity, think of the circle S1. Its universal cover is the real line R. The group of deck transformations is Z, which is the fundamental group of S^1. Now, consider the "arithmetic circle" Spec(Z). It has a single "point at infinity" and a point for each prime number. The maximal abelian extension of Q is the cyclotomic field Q(μ∞​), whose Galois group is Gal(Q(μ∞​)/Q)≅Z× or the ring of integers under multipication. This group is the "fundamental group" of this arithmetic space, and the extension is the "universal abelian covering." Artin reciprocity says that the action of this Galois group corresponds to the geometry of this space:  Artin reciprocity can be seen as an arithmetic analogue of the geometric theory of covering spaces. In topology, for a manifold M, the fundamental group π1​(M) classifies all covering spaces of M. For an abelian covering, the Galois group of the covering space is isomorphic to the fundamental group mod its commutator subgroup. Artin reciprocity provides an arithmetic analogue where the Galois group of an abelian extension of a number field K is the "fundamental group"of some geometric object associated to K, specifically the "space of primes" or Spec(O_K​). */
/* Artin reciprocity, A central simple algebra can be thought of as a generalized matrix algebra. The Brauer group is a collection of these algebras, where multiplication is tensor product. The elements of the Brauer group are "twists" of matrix algebras. Artin reciprocity provides a complete picture of how these "twists" behave over a number field. It tells us that an element of the global Brauer group is uniquely determined by its local components, which are in the Brauer groups of the local fields. This is like having a set of locally-defined blueprints for a structure that perfectly fit together to form a unique global structure:  Brauer group of a field K, Br(K), is a group of equivalence classes of central simple algebras over K. The Brauer group of a number field is a cornerstone of class field theory. Artin reciprocity gives a powerful description of this group, providing an exact sequence that relates it to the local Brauer groups. */
/* Artin induction theorem, character table of a group G. The characters of G are vectors in a vector space. Artin's induction theorem says that the "building blocks" for all these character vectors are the vectors from the cyclic subgroups. Artin reciprocity is a parallel statement for field theory: the "building blocks" for all abelian extensions are the cyclic extensions. This can be visualized as a tree of field extensions, where the root is the base field, and the branches are extensions. The reciprocity law tells us how to build the entire tree just from knowing the simplest, cyclic branches:  Artin's induction theorem in representation theory states that any rational-valued character of a finite group G can be written as a rational linear combination of characters induced from cyclic subgroups. Artin reciprocity can be seen as a generalization of this theorem from characters to field extensions. It shows that the structure of an abelian extension is controlled by the structure of its cyclic sub-extensions. */
/* Artin reciprocity, think of the "space" Spec(K) as having a group of "loops" on it, which is the fundamental group. Unlike in topology, these loops are built from prime ideals. Artin reciprocity says that if you take all these loops and "unwind" them into their abelian part (i.e., you forget the order in which you trace the loops), the resulting abelian group is exactly the Galois group of the maximal abelian extension:  Anabelian geometry is the study of schemes and their fundamental groups, with the goal of reconstructing the scheme from its fundamental group. In this context, the Artin reciprocity law for a field K is the statement that the Galois group of its maximal abelian extension is the abelianization of its profinite fundamental group, π1pro​(Spec(K)). */
/* Artin reciprocity, set of all prime ideals of a number field as a set of points, like a discrete number line. The ideal class group is the group that "shifts" these points, for instance, by multiplication with non-principal ideals. The Artin map is a rule for translating this "shifting" action into an action on a finite set of points (the elements of the Galois group):  In class field theory, the ideal class group of a number field K acts as the group of covering transformations for the "arithmetic covering" of K's spectrum by its Hilbert class field. Artin reciprocity says this group is isomorphic to the Galois group of the Hilbert class field, thereby providing a concrete realization of the abstract Galois group. */
