/* Bundle, Grothendieck fibration:  Grothendieck fibration is a functor p: E → B that has a lifting property for morphisms, analogous to lifting paths in a topological space. The category E is the total category, and B is the base category. */
/* Bundle, fiber of fibration:  object B in the base category B, the fiber is the subcategory of the total category E whose objects map to B and whose morphisms map to the identity morphism of B. */
/* Bundle, local triviality:  categorical bundle is locally trivial if it can be "trivialized" by pulling back to a simpler form over a "local" part of the base category. This corresponds to the existence of cartesian sections. */
/* Bundle, section of fibration:  section of a fibration p: E → B is a functor s: B → E such that p∘s is the identity functor on B. Sections are the categorical analogs of continuous sections of a vector bundle. */
/* Bundle, classifying space:  base category of a categorical bundle can be seen as a kind of classifying space for the fibers. This generalizes the concept of a classifying space for a topological group. */
/* Bundle, category of elements:  category of elements is a category whose objects are pairs (B,X), where B is an object of B and X is an object of the category F(B). This construction provides a standard way to form a fibration. */
/* Bundle, right fibration:  functor is a right-fibration if it has a specific lifting property for all morphisms in the base category, in a "right" direction. This is a common type of categorical bundle. */
/* Bundle, modules:  module M over a ring R can be seen as a categorical bundle over the base category with a single object and one morphism, which represents the ring. The "fibers" are the elements of the module. */
/* Bundle, sheaves:  sheaf of modules on a topological space or a scheme can be interpreted as a categorical bundle over the category of open sets of the space. The fibers are the stalks of the sheaf. */
/* Bundle, fibre functor:  functor that sends a vector bundle to the module of its sections can be seen as a fiber functor that generalizes the idea of a fiber in a topological bundle. */
/* Torsor, formalisation of twisting of Mobius strip: A vector bundle can be seen as a deformation of a trivial bundle. The transition functions measure how the bundle is "twisted" away from being a product. Imagine a perfectly straight, product bundle. A non-trivial vector bundle is like a Möbius strip, which is locally trivial but globally twisted. The torsor perspective formalizes this twisting. */
/* Torsor, classifying space as a master list changing objects into morphisms from a master list:  For a topological group G, there is a classifying space BG whose points classify the isomorphism classes of G-torsors. A classifying space is a "master list" of all possible torsors for a given group. Any torsor can be represented by a continuous map from the base space into the classifying space. */
/* Torsor, phase space of the dynamical system, ergodicity: A torsor can be used to model a dynamical system where a group acts freely and transitively on a phase space. The phase space of the dynamical system is a torsor. Any state can be reached from any other state by a unique group action. The system is therefore perfectly predictable and has no "fixed points" or "cycles." */
/* Group cohomology, extension of group G by abelian group A as torsor classified by second cohomology of group:  second cohomology group H2(G,A) classifies extensions of a group G by an abelian group A. Visual Intuition: A group extension is a "twisted" product of two groups. The torsor structure captures the "twisting" of these extensions. */
/* Principal bundle, naked torsor while vector bundle is dressed torsor: A vector bundle is associated with a principal bundle, which is a torsor for the general linear group. A vector bundle is constructed by "inflating" a principal bundle by the standard representation of GLn​. A principal bundle is a "naked" torsor, a space that is just a collection of group-acting points. The vector bundle is a "dressed" torsor, where each point is given a vector space, which is then acted upon by the group. */
/* Principal bundle, definition via schemes of right actions of group schemes of principal Z_2 bundle over circle as double cover of the circle, Z_2 acts  as right action by swapping two points, either get Mobius strip or trivial bundle:  principal bundle is a scheme P with a right action of a group scheme G such that the map P × G to P × P given by (p,g) to (p,pg) is an isomorphism. The projection map P to P/G is a faithfully flat morphism of schemes. Consider a principal Z2​-bundle over the circle S1, which is a double cover of the circle. The total space is a circle, and the fibers are two points. The group Z2​ acts on the fibers by swapping the two points. This can be visualized as a Möbius strip, which is locally two sheets but globally has a twist. */
/* Principal bundle, torsor as principal bundle with a single fibre, a vector in a vector space is a torsor since it can reach any point with the vector as a group action, similar to torsors with dates: A torsor is a principal bundle with a single fiber. The group acts freely and transitively on the fiber. Consider a vector space V. Any two vectors in V are related by a unique vector addition, so V is a torsor for the vector space itself. The visual intuition is that a torsor is a space with a perfect, uniform tiling by a group, so that from any point, you can reach any other point with a unique group action. Similarly, you can reach any date using the group action of a day. */
/* Principal bundle, covering map exp(2 pi i x) spiral staircase where G = Z and total space R as principal Z-bundle over S1, acting by translation, orbits are the fibres:  principal bundle in topology is a fiber bundle P over a base space X with a topological group G acting on the fibers from the right, and the action is free and transitive. Consider the group G=Z acting on the real line R. The map e2πix from R to the circle S1 is a covering map. The total space R is a principal Z-bundle over S1. The group Z acts by translation, x to x + n, and the orbits are the fibers. This can be visualized as a spiral staircase over a circle. */
/* Principal bundles, set of isomorphism classes is classified by Galois cohomology group measuring obstructions to principal bundle from being a trivial bundle, example of H1(Z, Z/2):  set of isomorphism classes of principal G-bundles over a scheme X is classified by the Galois cohomology group H1(X,G). The first cohomology group measures the obstructions to a principal bundle being a trivial bundle. For the ring Z, the obstructions for a principal Z2​-bundle are the number of ways it can be a non-trivial double cover. */
/* Principal bundle, homogenous space as principal bundle with a single fibre (torsor) example orthogonal O(3) acts as torsor over sphere S^2, sphere S^2 is homogenous space for orthogonal group O(3):  homogeneous space is a manifold on which a Lie group acts transitively. A homogeneous space is a principal bundle with a single fibre. It's a space that is perfectly tiled by a group action. For example, the sphere S2 is a homogeneous space for the orthogonal group O(3) */
/* Moduli space, set of all lines passing through origin parameterised by angle, projective line is moduli space for set of lines through origin: A moduli space is a geometric space whose points represent isomorphism classes of some type of geometric object, such as elliptic curves, vector bundles, or Riemann surfaces. Visual Intuition: Consider the set of all lines in the plane passing through the origin. This set can be parameterized by the angle a line makes with the x-axis, but with a slight subtlety: angles θ and θ+π correspond to the same line. The space of all such lines is the projective line, P1. This is a moduli space for the set of lines through the origin. */
/* Moduli space, moduli space of representations for commuting matrices using ring of two variables:  The moduli space of representations of the ring of polynomials in two variables, k[x,y], is a space whose points correspond to pairs of commuting matrices. The geometry of this space is a reflection of the algebraic properties of the ring. */
/* Principal bundle, visualisation of a frame of a vector space, with the general linear group acting on the frame of reference via the change of basis. Frame bundles lack a canonical choice of identity:  Consider the Cartesian product X * G, for a space X and group G. Typical example is vector space X, and vector bundle E, with a group GLn(X), then F(E) is a frame bundle which is an example of a principal bundle. The general linear group acting on the frame of reference via the change of basis. Frame bundles lack a canonical choice of identity. */
