/* Mellin transform, analyses the power law (moments, generalisation of moment generating function) content of a function rather than frequency: A Mellin transform maps a function f(x) on the positive real axis to a new function F(s) in the complex plane, where F(s)= integral over positive real axis of x^{s-1} f(x) dx. Note that the annoying -1 comes from considerations of dx/x, see lecture on Haar measure by Borcherds. */
/* Mellin transform, generalised moment:  The Mellin transform of a density function is E[X^{s - 1}]. Useful in probability as a generalised moment. */
/* Mellin transform, handles singularities with distributions (key example: Dirac delta at x = 1 is constant):  The Mellin transform extends to distributions, especially those with power-law singularities. The Mellin transform of the Dirac delta at x = 1 is simply a constant, which is a testament to its power to handle singularities. Imagine a function with a sharp spike at x = 1. The Mellin transform "smooths out" this spike and represents it as a simple function in the complex plane. */
/* Mellin transform, relates Dirichlet series to Riemann zet function:  Riemann zeta function is defined as a Dirichlet series, and its properties are deeply linked to number theory. The Mellin transform provides a way to express the zeta function as an integral, making it possible to use the tools of complex analysis to study it */
/* Integral transform, linear operator, its eigenfunctions are the functions that are only scaled by the operator. The integral transform is the "change of coordinates" that takes a function and represents it as a linear combination of these eigenfunctions. For example, the Fourier transform takes a function and represents it as a sum of sines and cosines, which are the eigenfunctions of the Laplacian operator on a periodic domain:  An integral transform is a change of basis from the position basis to the eigenbasis of an operator. */
/* Integral transform, measure can be thought of as a distribution of "mass" or "charge." An integral transform takes this distribution and creates a new one. For example, the Fourier transform of a measure of point masses is a sum of oscillating functions. The transform maps the discrete mass points to a continuous function, revealing its periodic structure:  An integral transform is a linear map between spaces of measures. */
/* Integral transform, probability density function describes the likelihood of a random variable taking a certain value. The characteristic function is its Fourier transform. It's a complex-valued function that encodes all the statistical moments of the distribution, such as the mean, variance, etc. . The transform is a tool that "compresses" all the statistical information into a single function:  An integral transform of a probability density function is a moment-generating function or characteristic function. */
/* Integral transform, Distributions are generalized functions, like the Dirac delta. The Fourier transform of a Dirac delta function is a constant function. The transform takes a "point-like" object in one domain and transforms it into a "flat" object in the other. It's a way of representing a singular object in a more well-behaved form:  An integral transform maps a distribution to another distribution. */
/* Integral transform, a curved manifold, the heat equation describes how heat diffuses. The heat kernel is an integral transform kernel that maps an initial temperature distribution to the temperature distribution at a later time. The kernel, often a Gaussian-like function, encapsulates how heat "spreads" over the curved space:  An integral transform is a heat kernel or propagator on a manifold. */
/* Integral transform, Fourier and Laplace transforms are particularly useful for this. They convert a PDE into a simpler algebraic equation in the transform domain. For example, the heat equation dt/du = k d^2u / dx^2​ transforms into a simple first-order ODE in the frequency domain, which is easily solved:  An integral transform is a tool for solving certain PDEs, especially those with constant coefficients. */
/* Integral transform, semigroup describes the evolution of a system over time. The Laplace transform maps the time-domain evolution to a frequency-domain representation. The transform is a "snapshot" of the system's dynamics at a given "frequency.":  The integral transform is the Laplace transform, which is used to analyze semigroups of operators. */
/* Integral transform, harmonic analysis, an integral transform (like the Fourier transform) acts as a "decomposition" tool for a function on a group. It breaks down the function into its "building blocks," which are the characters of the group. It's a way of understanding a complex object by looking at its simpler components:  An integral transform is the process of decomposing a representation of a group into its irreducible representations. */
/* Integral transform, system's stability is determined by the poles of its transfer function in the Laplace domain. The transform maps the system's behavior over time to a complex plane. By looking at the location of the poles in this plane, one can determine if the system will be stable or unstable:  The Laplace transform is used to analyze the stability of control systems. */
/* Kernel, image processing filter. The kernel is a small matrix of numbers, like a 3×3 grid, that slides over the image. The value of the new pixel at position (i,j) is a weighted sum of the old pixel values in the neighborhood, where the weights are given by the kernel. The kernel dictates how the image is transformed, whether it's blurred, sharpened, or edge-detected:  In integral transforms, the kernel K(s,x) is the weighting function that defines the transformation. */
/* Kernel, two-dimensional plot. The kernel can be a measure, which is a distribution of "mass" over this plot. When you apply the operator, you are essentially "integrating" the input function against this mass distribution. For example, a measure concentrated on the diagonal y=x would correspond to the identity operator:  An integral kernel is a measure on the product space of the domain and codomain. */
/* Integral kernel, stochastic process, the kernel p(y∣x) gives the probability density of transitioning from state x to state y. For a simple Markov chain, the kernel is a transition matrix. For a continuous process, the kernel is a function that, at a given x, describes the bell-shaped curve of possible future positions y:  An integral kernel is a conditional probability density function. */
/* Integral kernel, microlocal analysis, we study operators that are not necessarily local, but "almost" local. The kernel of such an operator is not just a function of two variables but also of frequency. The kernel, often called the symbol, can be visualized in phase space (position and momentum). The kernel tells you how the operator transforms a function based on both its value and its oscillations:  The kernel is the symbol of a pseudodifferential operator. */
/* Integral kernel, in a curved manifold, the fundamental solution to a differential equation (e.g., the Laplacian) is the kernel that describes the response to a point source. For example, on a sphere, the fundamental solution to the Laplacian is the potential from a point charge. This kernel, which is a distribution, encapsulates the geometry of the manifold and the behavior of the operator: A kernel is the fundamental solution of a differential operator on a manifold. */
/* Integral kernel, for a stochastic process (e.g., Brownian motion), the kernel p(x,t | y,t0​) represents the probability density of being at point x at time t given that the process started at point y at time t0​. For Brownian motion, this kernel is a Gaussian function that broadens with time: A kernel is the transition density of a stochastic process. */
/* Integral kernel, operator can be defined by a kernel, but the relationship is not always linear. For example, in a Urysohn operator, the kernel K(x,y,f(y)) depends on the value of the function being integrated, making the operator nonlinear. The kernel is like a "filter" whose properties change based on the input signal: A kernel can be used to define a nonlinear operator. */
/* Integral kernel, semigroup is a family of operators that describes how a system evolves over time. The generator of this semigroup is a kernel that describes the "infinitesimal" change in the system. For the heat equation, the generator is the Laplacian, and its kernel is the heat kernel:  The kernel is the generator of a semigroup of operators. */
/* Integral kernel, character is a special type of function on a group that is constant on conjugacy classes. It can be viewed as a distribution kernel that "probes" a representation and reveals its internal structure. For example, the character of a rotation group tells you how many times each irreducible representation appears:  The kernel is the character of a representation. */
/* Integral kernel, system's behavior is completely characterized by its response to a single, sharp input (an impulse, or Dirac delta). This response, which is a distribution kernel, is the "DNA" of the system. By "convolving" any input with this kernel, you can predict the output:  The kernel is the impulse response of a linear time-invariant system. */
/* Integral kernel, numerical integration scheme like the trapezoidal rule, the integral is approximated by a weighted sum of function values. The kernel is the set of weights you use. For the trapezoidal rule, the kernel is a triangular shape that weights the endpoints less than the middle points:  The kernel is the weight function for numerical integration. */
/* Laplace transform, a continuous signal over time, like the voltage in an electronic circuit after a switch is flipped. The Laplace transform is like taking a "snapshot" of the signal's decay behavior and representing it as a point in a complex plane. . The real part of the complex variable s corresponds to the decay rate, and the imaginary part corresponds to the oscillation frequency:  The Laplace transform maps a function f(t) to F(s) via the integral F(s) over real line ​exp(−st) f(t)dt. */
/* Convex optimisation, Laplace transform of a convex function is its convex conjugate. Imagine a convex function like a bowl. The Laplace transform describes this bowl not by its surface but by the set of all its tangent planes. The transform encodes the relationship between the function and its "dual" representation:  The Laplace transform is related to convex optimization through the concept of convex conjugation and the Legendre-Fenchel transform. */
/* Laplace trasnform, semigroup of operators describes the evolution of a system over time. The Laplace transform maps this continuous time evolution to a family of operators in the complex plane. The poles of the transformed operator (the resolvent) correspond to the eigenvalues of the generator. This allows us to find the "resonant frequencies" or "eigenmodes" of the system:  The Laplace transform of a semigroup is the resolvent of its generator. */
/* Laplace transform, "moment-generating function" for this mass distribution. It gives you a function in the complex plane that encodes information about how the mass is distributed on the real line:  The Laplace transform of a measure on R is the integral over positive real line ​exp(−st) dμ(t). */
/* Laplace transform, distribution, like the Dirac delta function δ(t), can be thought of as a generalized function. The Laplace transform of δ(t) is simply 1. The transform converts a singular, "point-like" object in the time domain into a simple, constant function in the complex frequency domain:  The Laplace transform can be extended to tempered distributions with support on the positive real axis. */
/* Laplace transform, random variable X with density f(x), its moment-generating function is M_X​(s)=E[exp(sX) ] = over real line ​exp(sx) f(x)dx. This is essentially the Laplace transform with s replaced by −s. It's a single function that encodes all the statistical moments of the random variable:  The Laplace transform is the moment-generating function of a non-negative random variable. */
/* Laplace transform, study the singularities of functions. The Laplace transform helps to analyze singularities that have an exponential decay. It provides a way to "zoom in" on the singularities and study their behavior in the complex plane:  The Laplace transform is related to the Fourier integral operator when analyzing functions with exponential decay. */
/* Laplace transform, heat kernel on a manifold is the fundamental solution to the heat equation. The Laplace transform of the heat kernel with respect to time is the resolvent of the Laplacian operator on the manifold. This provides a way to study the geometry of the manifold by analyzing the spectrum of the Laplacian:  The Laplace transform is a tool for studying the heat kernel on a manifold. */
/* Laplace transform, semigroup is a family of operators that describes continuous evolution, like the heat semigroup. The Laplace transform of this semigroup, a family of operators that describes the "frequency domain" behavior, is the resolvent of the semigroup's generator. It's a way to move from the continuous evolution of a system to a static representation that encapsulates all its properties:  The Laplace transform is a primary tool for studying one-parameter semigroups of operators. */
/* Laplace transform, Laplace transform can be viewed as a specialization of the Fourier transform. The Fourier transform analyzes signals in a frequency space, while the Laplace transform analyzes signals in a complex frequency space that includes a decay component. This makes it a natural tool for analyzing representations of Lie groups that have a "cone-like" structure:  The Laplace transform is related to the Fourier transform on a cone. */
/* Laplace transform, system's stability can be determined by the location of the poles of its transfer function in the complex s-plane. The Laplace transform maps the system's differential equations to this plane. If all the poles are in the left half of the plane, the system is stable:  The Laplace transform is the primary tool for analyzing the stability of linear time-invariant systems. */
/* Laplace transform, impulse response is a signal's output when a short, sharp pulse is input. The Laplace transform of this response, called the transfer function, describes how the system's output responds to different frequencies. It's a way of representing a system's behavior as a simple algebraic function:  The Laplace transform of an impulse response is the transfer function of a system. */
/* Laplace transform, electrical circuits, components like resistors, capacitors, and inductors have complex frequency-domain representations. The Laplace transform converts a differential equation for a circuit into a simple algebraic equation involving impedances and admittances, which is much easier to solve:  The Laplace transform is a tool for circuit analysis. */
/* Convolution, infimal convolution of two convex functions, (f□g)(x)=infy​{f(y)+g(x−y)}, represents the lower envelope of the sum of the two functions. Imagine two convex bowls. The infimal convolution is a new bowl that you get by "summing" them in a specific way. It's the lowest possible surface you can get by sliding one bowl under the other and adding their heights:  Convolution can be used in convex analysis to define the infimal convolution of convex functions. */
/* Convolution, Convolution Theorem states that the Fourier transform of a convolution is the product of the individual Fourier transforms, F(f∗g)=F(f)⋅F(g). This is a change of perspective from a complex "smearing" operation to a simple point-wise multiplication. It's like switching from the time domain (where a filter convolves a signal) to the frequency domain, where the filter just scales the frequency components of the signal:  Convolution is an operation that becomes a simple multiplication in the frequency domain. */
/* Convolution, discrete set of masses (a discrete measure). Convolving this with a continuous probability density (another measure) "spreads" each point mass into a continuous distribution, like a sum of bell curves. The resulting convolution is a continuous measure:  Convolution is the operation of "smearing" one measure with another. */
/* Convolution, X and Y be two independent random variables. The probability density function of their sum, Z=X+Y, is the convolution of their individual densities, fZ​=fX​∗fY​. Imagine a random variable representing the height of a person and another representing the height of their shoes. The convolution gives you the distribution of their total height:  The convolution of two probability density functions gives the density function of their sum. */
/* Convolution, convolution of a test function with the Dirac delta function δ(t) is simply the original test function, (f∗δ)(x)=f(x). This shows that the Dirac delta acts as the identity element for convolution. The Dirac delta is a "point-like" distribution that, when convolved with a function, doesn't change it:  Convolution extends to distributions, allowing us to define operations on generalized functions. */
/* Convolution, model how singularities propagate and interact. The wave front set of a convolution is contained within the sum of the wave front sets of the individual distributions. This means that a convolution can "smooth out" some singularities or create new ones in a predictable way:  Convolution is a form of multiplication in phase space. */
/* Convolution, with a heat kernel or a smoothing kernel can be used to average a function over a neighborhood. This is a form of geometric "blurring" that is intrinsic to the manifold's geometry. For example, on a sphere, convolving a function with a smoothing kernel averages the function over a small patch of the sphere's surface:  Convolution is a way of "smearing" a function on a manifold. */
/* Convolution, fundamental solution to a linear PDE is the solution for a point source (a Dirac delta function). The solution to the PDE for an arbitrary source is the convolution of the fundamental solution with the source term. For example, the solution to the heat equation with a given initial temperature distribution is the convolution of that distribution with the heat kernel:  Convolution with the fundamental solution is a way to solve linear PDEs. */
/* Convolution, mollifier is a smooth function with a compact support and an integral of 1. Convolving a non-smooth function (e.g., a square wave) with a mollifier "blurs" the sharp edges and turns it into a smooth function. This is a common technique to prove results about non-smooth functions by first proving them for smooth ones:  Convolution can be used to mollify a function, turning a non-smooth function into a smooth one. */
/* Convolution, semigroup of operators describes a system's evolution. The composition of two evolution operators is a convolution in the time domain. For example, the heat semigroup, T(t), is such that T(t1​)T(t2​)=T(t1​+t2​). This corresponds to the convolution of the heat kernels:   */
/* Convolution, harmonic analysis on groups, convolution is the natural way to multiply functions. It's a generalization of polynomial multiplication. The Fourier transform on a group turns this convolution into a simpler operation in the dual space of the group:  Convolution is the multiplication of functions on a Lie group. */
/* Fejer kernel, smooth version of Dirichlet kernel:  a standard Fourier series partial sum for a square wave. Near the discontinuity, it overshoots and oscillates, a phenomenon known as the Gibbs phenomenon. The Fejér kernel is a "smoother" version of the Dirichlet kernel, which is used for standard partial sums. The convolution with the Fejér kernel "blurs" the Gibbs phenomenon, resulting in a more regular and well-behaved approximation that converges uniformly */
