/* Group, set of symmetries:  Set of symmetries of an object, composition of symmetries is group operation */
/* Group, action:  set of transformations that act on sets */
/* Group, axioms:  unital, associative invertible closed magma */
/* Group, puzzle:  elements are moves that change the state of a puzzle (Rubik's cube) */
/* Group, non-empty set with single operation:  Defined by one operation, unlike rings or fields */
/* Group, cancellation laws:  If ab = ac, b = c, solvability of equations */
/* Group, monoid with inverses:  They are monoids with inverses. */
/* Group, group object: A group is a group object in the category of Sets. */
/* Group, category of one object:  Category with one object, group elements are morphisms, group operation is categorical composition */
/* Group, holes are abelian since there is no natural order:  homology groups are abelian is that the "holes" don't have a natural order or direction. A loop can be traversed clockwise or counterclockwise, and the sum of two loops is the same regardless of which one you add first. */
/* Coset, set of elements:  multiply subgroup by fixed element */
/* Coset, equivalence class related to which element in subgroup:  TFAE: xy^-1 in subgroup, x related to y. Form equivalence class */
/* Coset, partition:  Partition group into disjoint subsets, each subset same size as subgroup H */
/* Coset, translate of subgroup:  translate subgroup H by element g in G, represented by gH (left coset), or Hg (right coset). This is somewhat related to the Haar measure. */
/* Coset, orbit of element:  Coset is orbit of element g under action of subgroup H by right multiplication, gives coset gH (left coset) */
/* Coset, homogenous space:  Coset space is a homogenous space, G acts transitively on the set of cosets. */
/* Coset, fibre of homomorphism:  if the homomorphism from a group G to the quotient G/H is a canonical projection homomorphism, then the coset is fibre of this map, specifically the preimage of a single element in the quotient group. */
/* Coset, compositional:  object, elements of a group, structure is action of subgroup */
/* Coset, state space:  Coset partition the state space, each coset is equivalent states, state is group element */
/* Coset, components of quotient group:  Individual elements of a quotient group. Quotient group operation is defined on the cosets */
/* Coset, invariant subset:  Invariant subset under left or right multiplication of elements of subgroup H. */
/* Group action, as a map: a group action is a map from the cartesian product of group G and set X such that for any group homomorphism, we have p(g_1(g_2, x))) is equal to p(g_1g_2, x). */
/* Group action, permutations of a set:  group action is equivalent to a group homomorphism from G to the group of all permutations of X. This means that every element of the group corresponds to a way of rearranging the elements of the set. */
/* Group action, visual analogy:  group action is an ontological model for the symmetries of an object. The group elements correspond to the transformations (like rotations or reflections) that leave the object unchanged. For example, the dihedral group D4​ acts on a square by its symmetries. */
/* Group action, orbit of any element:  orbit of an element x in X is the set of all elements that can be reached from x by the action of the group. The orbits partition the set X. */
/* Group action, stabiliser of an element:  stabilizer of an element x in X is the subgroup of G that leaves x unchanged. Example, imagine rotating about a fixed point of a tetrahedron, it is a cyclic subgroup of order 3. */
/* Group action, transitive action using the visualisation with one orbit:  transitive action has only one orbit. This means every element can be transformed into every other element. */
/* Group action, action on a vector space:  group can act on a vector space by a group homomorphism from G to the group of invertible linear transformations on the space. This is a representation of the group. */
/* Group action, action on a chain complex:  group can act on a chain complex of modules. This means each module in the complex is a module with a group action, and the differentials are equivariant, i.e., they respect the group action. */
/* Group action, group cohomology:  studies the group action on a module by constructing a complex whose homology groups are the cohomology groups of the group. */
/* Group actions, action on a sheaf: a group can act on a sheaf of modules. This means the group acts on the open sets and on the sections of the sheaf in a compatible way. */
/* Group action, act on a spectrum:  group can act on a spectrum by a map from the classifying space of the group to the space of automorphisms of the spectrum. */
/* Quotient scheme, sphere intuition quotient means you identify all points that can be glued into each other by any action: A quotient scheme is a scheme that is the result of a geometric quotient of another scheme by a group action. Imagine a sphere. A group of rotations acts on it. The quotient is a space where all the points that can be rotated into each other are considered the same point. Like collapsing plane to line is not a group action, collapsing points into each other for a sphere is a group action. */
/* Quotient, orbit space, visual intuition of swapping pairs of points:  quotient can be viewed as an orbit space, where you take a space and a group action on it and identify all the points that are in the same orbit. Visual intuition: Take a set of points on a line. A group action swaps pairs of points. The quotient space has only half the number of points, as the pairs are identified. This is like pairing up pairs of points this is the orbit space. */
/* Quotient, spectrum of a quotient ring, carving out smaller variety or quotient by ideal means collapsing plane as variety into line as a subvariety:  ring R and an ideal I, the spectrum of the quotient ring, Spec(R/I), is the closed subscheme of Spec(R) defined by the ideal I. Visual intuition: Spec(R) is an algebraic variety. Taking the quotient by an ideal is like "carving out" a smaller subvariety within it, for example, a line within a plane. */
/* Quotient, identification done up to homotopy for a group action:  homotopical quotient of a topological space by a group action is a quotient where the identification is done up to homotopy. This is often an object called a classifying space. */
/* Induced representation in group theory, visual intuition as smaller tiled floors to larger tiled floors:  Let H be a subgroup of a group G, and V be a representation of H. The induced representation IndHG​(V) is a way to "lift" the representation of the smaller group H to a representation of the larger group G. Imagine group G as a large tiled floor and the subgroup H as a single tile. The representation of H is a pattern on that tile. To get the induced representation, you replicate this patterned tile and its transformations across the entire floor, taking into account how the larger group G acts on the collection of tiles. */
/* Group scheme, multiplying two points to get a third point:  group scheme is a scheme that is also a group, with the group operations (multiplication, inverse, and identity) being morphisms of schemes. This unifies the notions of algebraic groups and groups of rational points on a variety. Imagine a smooth curve or surface (a scheme) that has a group structure on its points. This means you can "multiply" two points on the curve to get a third point, and this multiplication is compatible with the geometric structure. A complex elliptic curve is a perfect example, where the group law is defined by the intersection of lines with the curve. */
/* Group scheme, points functor:  group scheme can be defined by its functor of points. This means specifying how the group acts on every possible test space (scheme). Think of a group scheme not as a single object, but as a recipe for making a group for any geometric space you input. For example, the recipe for the multiplicative group scheme Gm​ gives you the group of units of a ring when you input a ring spectrum. */
/* Group scheme, Hopf algebra as coordinate ring and dual of a group scheme:  coordinate ring of an affine group scheme is a Hopf algebra, which is a commutative ring with additional maps (co-multiplication, co-unit, and antipode) that capture the group operations. The Hopf algebra is the algebraic dual of the group scheme. The group structure (multiplication) on the geometric space is encoded by the co-multiplication on the ring of functions, which "splits" a function into a tensor product of two functions. Recall that you imagined a group scheme as a smooth curve. */
/* Group scheme, Lie algebra of a group scheme, imagine the Lie algebra as tangent space of identity:  For a smooth group scheme, the tangent space at the identity element has a natural Lie algebra structure. Visual Intuition: The Lie algebra is the infinitesimal approximation of the group scheme near the identity. Imagine the group as a smooth manifold. The Lie algebra is the tangent space at the identity, and the Lie bracket is derived from the commutator of nearby group elements. */
/* Group scheme, additive group scheme as line, multiplicative group scheme as line with origin removed:  These are the simplest examples. The additive group scheme Ga​ has points with the group law of addition, while the multiplicative group scheme Gm​ has points with the group law of multiplication. Visual Intuition: The additive group scheme is a line where points are added like vectors. The multiplicative group scheme is the line with the origin removed, where points are multiplied. */
/* Group scheme, example of group object in category of schemes:  group scheme is an example of a group object in the category of schemes. This is a general categorical definition. */
/* Group scheme, loop space of topological groups consists of all closed paths starting and ending at a given point:  The loop space of a topological group is a group, and its properties are closely related to the original group. Visual Intuition: The loop space consists of all closed paths starting and ending at a given point. The group law on the loop space is given by "concatenating" paths. */
/* Group scheme, elliptic curves of a finite field as scattered collection of points on a grid along an elliptic curve:  elliptic curve over a finite field is a scattered collection of points on a grid, but these points form a group. The group law (addition of points) is still defined geometrically, but it is now on a finite set of points. */
/* Group scheme, group scheme acting on another scheme generating trajectories and orbits:  group scheme is a group of transformations acting on a geometric space. This action generates trajectories and orbits, which can be used to study the long-term behavior of the system. */
/* Coset space, partitioning off group by subgroup Consider the group of integers Z under addition and the subgroup of even integers 2Z. The cosets are 0+2Z={…,−2,0,2,…} (the even integers) and 1+2Z={…,−1,1,3,…} (the odd integers). Geometrically, imagine the integers on a number line. You're "identifying" or "collapsing" all even integers to a single point and all odd integers to another point, resulting in a discrete space of two points: A coset space, also known as a quotient space, is the set of all left (or right) cosets of a subgroup H in a group G, denoted by G/H. Each coset is of the form gH={gh∣h∈H}, for some g∈G. It's a way of partitioning the group into disjoint subsets of equal size. Visual Intuition: Consider the group of integers Z under addition and the subgroup of even integers 2Z. The cosets are 0+2Z={…,−2,0,2,…} (the even integers) and 1+2Z={…,−1,1,3,…} (the odd integers). The coset space Z/2Z consists of just these two cosets. Geometrically, imagine the integers on a number line. You're "identifying" or "collapsing" all even integers to a single point and all odd integers to another point, resulting in a discrete space of two points. */
/* Coset space, group of rotations of a circle, which is the group of complex numbers of magnitude 1, denoted U(1) or S1. Let the subgroup H be the n-th roots of unity. The coset space S1/H is also a circle. Visually, we are "collapsing" the circle by a factor of n. For example, if n=2, we identify points separated by π radians. The resulting space is still a circle, but "wrapped" around itself:  In topology, a coset space is a special type of quotient space, where a topological group G is "quotiented" by a subgroup H. This results in a new topological space where the points are the cosets. Visual Intuition: Consider the group of rotations of a circle, which is the group of complex numbers of magnitude 1, denoted U(1) or S1. Let the subgroup H be the n-th roots of unity. The coset space S1/H is also a circle. . Visually, we are "collapsing" the circle by a factor of n. For example, if n=2, we identify points separated by π radians. The resulting space is still a circle, but "wrapped" around itself. */
/* Coset space, example of general linear group GLn(C) acting on the set of all 1-dimensional subspaces of C^n:  An algebraic coset space is a homogeneous space G/H where G is an algebraic group and H is a closed algebraic subgroup. It's a variety on which G acts transitively. Visual Intuition: Consider the general linear group GLn(C) acting on the set of all 1-dimensional subspaces of Cn. The stabilizer of a 1-dimensional subspace is a subgroup of GLn(C). The coset space is the set of all such 1-dimensional subspaces, which is the projective space P_{n-1}(C). This space is geometrically a collection of lines through the origin, and the coset space structure provides a powerful way to study its geometry. */
/* Coset space, G be the group of rotations in 3D space, SO(3), and let H be the subgroup of rotations about the z-axis, SO(2). The coset space SO(3)/SO(2) can be identified with the 2-sphere S^2:  in the theory of Lie groups, a coset space G/H is a homogeneous manifold, where G is a Lie group and H is a closed Lie subgroup. Visual Intuition: Let G be the group of rotations in 3D space, SO(3), and let H be the subgroup of rotations about the z-axis, SO(2). The coset space SO(3)/SO(2) can be identified with the 2-sphere S2. Each coset corresponds to a unique direction in 3D space, which is specified by a point on the sphere. We are "quotienting out" the rotations about a fixed axis to get the space of all possible axis directions. */
/* Coset space, reduced phase space, example of a central force problem, like a planet orbiting a star. The system has rotational symmetry. The group of rotations is SO(2):  In dynamical systems, a coset space can represent a reduced phase space when a system has a symmetry group. The coset space is the space of all possible states of the system after accounting for this symmetry. Visual Intuition: Consider a central force problem, like a planet orbiting a star. The system has rotational symmetry. The group of rotations is SO(2). The coset space can be thought of as the orbit of the planet in the plane, where the angular position is "quotiented out" and all that matters is the distance from the star. The coset space is effectively the radial line segment of possible distances. */
/* Coset space, module over a quotient ring, group algebra Fp​[G] for a finite group G and a prime p dividing the order of G. The Jacobson radical J of this ring is a subgroup. The quotient ring Fp​[G]/J is a direct sum of matrix rings:  In modular representation theory, a coset space can be seen as a module over a quotient ring R/I. The elements of this module are the cosets of the ideal I. Visual Intuition: Consider the group algebra Fp​[G] for a finite group G and a prime pdividing the order of G. The Jacobson radical J of this ring is a subgroup. The quotient ring Fp​[G]/J is a direct sum of matrix rings. A module over this quotient ring is a direct sum of simple modules. Geometrically, we are "collapsing" the "non-semisimple" part of the group algebra (the Jacobson radical) to obtain a "clean" or "semisimple" structure, which is a sum of simple objects. */
/* Coset space, cosets in the ideal class group represents a "class" of ideals that are "equivalent" up to multiplication by a principal ideal:  In arithmetic number theory, the ideal class group of a number field is a coset space. It is the quotient of the group of fractional ideals by the subgroup of principal fractional ideals. Visual Intuition: The ideal class group measures the failure of unique factorization in a number ring. Each coset in the ideal class group represents a "class" of ideals that are "equivalent" up to multiplication by a principal ideal. We are "collapsing" all ideals that are "close" to being principal into a single point, to see the "non-principal" structure of the ring. */
/* Coset space, vector bundle example and moduli spaces: A moduli space of vector bundles on a variety is a coset space. It is a space whose points parameterize the isomorphism classes of vector bundles. Visual Intuition: A vector bundle is a collection of vector spaces "glued" together over a variety. The group of automorphisms of the vector bundle acts on it. The coset space is the collection of all vector bundles that are "equivalent" up to isomorphism. This space "organizes" all possible ways to assign vector spaces to points on the variety. */
/* Cosets, Cayley graph of the group of integers Z with generator 1: Consider the Cayley graph of the group of integers Z with generator 1. It's an infinite line of vertices. Let the subgroup be 2Z. The coset space is a graph with two vertices (corresponding to even and odd numbers) and an edge connecting them. This is a way of "folding" the infinite line into a finite graph, where the vertices are the cosets. */
/* Coset space, upper half-plane is the complex plane with positive imaginary part. The group SL2​(Z) acts on it by fractional linear transformations:  In the theory of modular forms, a coset space is a quotient of the upper half-plane H by a discrete subgroup of SL2​(Z). Visual Intuition: The upper half-plane is the complex plane with positive imaginary part. The group SL2​(Z) acts on it by fractional linear transformations. The coset space H/SL2​(Z) is a fundamental domain for this action, which is a hyperbolic surface with cusps. . We are "collapsing" the infinite repetitions of the fundamental domain to a single object, which has a finite "volume" in hyperbolic geometry. */
/* Coset space, symplectic quotient is a new phase space where the conserved quantity is fixed:  Imagine a physical system with a conserved quantity, like angular momentum. The phase space has a symmetry group (like rotations). The symplectic quotient is a new phase space where the conserved quantity is fixed. We are "collapsing" the original phase space along the orbits of the symmetry group to get a "reduced" phase space. */
/* Coset space, ring can be thought of as a "space" of operators. A maximal left ideal is a "maximal" collection of operators that "annihilate" some vector. The simple module is the vector space itself, after "quotienting out" by the action of these operators:  In non-commutative ring theory, a simple module is a coset space of a ring R by a maximal left ideal I. It is a module that has no proper submodules. Visual Intuition: A ring can be thought of as a "space" of operators. A maximal left ideal is a "maximal" collection of operators that "annihilate" some vector. The simple module is the vector space itself, after "quotienting out" by the action of these operators. It's the "smallest" non-trivial space on which the ring can act. */
/* Coset space, deforming a sphere into a space X while keeping its "equator" inside a subspace A. The coset space is a way of "collapsing" all these deformations that are equivalent up to the "equator's" path inside A. This reveals a finer structure of the "holes" of the pair (X,A):  In homotopy theory, the relative homotopy group πn​(X,A,x0​) is a coset space. It is the quotient of the group of based maps of an n-sphere into X that map the "equator" to A, by the subgroup of those that map the "equator" to a specific point x0​. Visual Intuition: We are studying how to "deform" a sphere into a space X while keeping its "equator" inside a subspace A. The coset space is a way of "collapsing" all these deformations that are equivalent up to the "equator's" path inside A. This reveals a finer structure of the "holes" of the pair (X,A). */
/* Surjective, the ring of 2x2 matrices with real entries, M2​(R), and the ring of real numbers, R. We can define a surjective ring homomorphism p:M2​(R) to R by taking the determinant of the matrix. This map is surjective because every real number x can be represented as the determinant of a matrix, for example, the diagonal matrix with entries x and 1. The "projection" from the space of matrices to the real line covers the entire line: a ring homomorphism ϕ: R to S is surjective if for every element s∈S, there exists an element r in R such that p(r)=s. This is equivalent to saying that the kernel of the homomorphism is a two-sided ideal I of R and S is isomorphic to the quotient ring R/I. */
/* Surjective, a linear map from R3 to R2 that projects a point (x,y,z) to (x,y). This is a surjective map. The domain is a 3D space, and the codomain is a 2D plane. The projection "covers" the entire plane. Any point in the plane has an entire vertical line of points in 3D space that map to it: A linear transformation T:V→W between two vector spaces is surjective if its range is the entire vector space W. This implies that the dimension of the range is equal to the dimension of the codomain, dim(Im(T))=dim(W). */
/* Surjective, the dihedral group D4​ (symmetries of a square) and the cyclic group Z2​ (rotations by 0 and 180 degrees). We can define a surjective homomorphism p : D_4​ to Z/2​ that sends all rotations to 0 and all reflections to 1. This means that we can "project" the complex symmetries of the square onto the simpler two states of Z/2​. Every element in Z/2​ has a corresponding set of elements in D4​ that maps to it, so the projection "covers" all of Z2​: a group homomorphism p: G to H is surjective if the image of p is the entire group H. This means that for every element h in H, there exists at least one element g∈G such that p(g)=h. */
/* Surjective, a system on a circle given by rotation and a system on a line segment given by a map that wraps the segment around. A factor map is a projection from the circle to the line segment that preserves the dynamics. The surjectivity means that every point on the line segment is the image of some point on the circle. The factor map "covers" the entire codomain: A factor map between two dynamical systems (X,f) and (Y,g) is a surjective map p: X to Y such that p(f(x)) = g(p(x)). A factor map is a way to "project" a complex dynamical system onto a simpler one. */
/* Surjective, a map from a module M to a module N. An epimorphism is a map that cannot be "factored out" by any other map. If we have two different maps from N to another module, and they agree on the image of our map, they must be the same map. This is a powerful property that tells us that our map "covers" the entire codomain: a category, a morphism f:A→B is an epimorphism if for any two morphisms g, h: B to C, the equality g * f = h * f for the same section the retractions are equal implies g = h. In the category of modules, epimorphisms are precisely the surjective homomorphisms. */
/* Injectives, group Z (integers with addition) and the group Z2 (pairs of integers with component-wise addition). The homomorphism p : Z to Z/2 given by p(n)=(n,0) is injective. This map "embeds" the integers as a straight line in the integer lattice. No two different integers map to the same point, so the line doesn't "fold back" on itself. The kernel is only the integer 0,which maps to the origin (0,0):  An injective group homomorphism p : G to H is a homomorphism that is injective as a function. This is equivalent to stating that the kernel of the homomorphism is the trivial subgroup, ker(p) = {e}, where e is the identity element of G. */
/* Injective, a linear map from a line in R3 to a plane in R3 that just maps the line into the plane. For example, the map from the x-axis to the xy-plane given by T(x,0,0)=(x,0,0). This map is injective because the null space is just the origin. No two points on the line are "crushed" into the same point on the plane:  injective linear transformation T:V to W between two vector spaces is a linear map that is injective as a function. This is equivalent to stating that the null space of the transformation is the zero vector, null(T) = {0_V​}. This implies that the dimension of the domain is less than or equal to the dimension of the codomain, dim(V) less than or equal to dim(W). */
/* Injective, the ring of integers Z and the ring of rational numbers Q. The inclusion map p: Z to Q is an injective ring homomorphism. This is a very natural embedding where we can visualize the integers as a discrete subset of the rational numbers. The homomorphism doesn't "collapse" any of the integers together:  injective ring homomorphism ϕ: R to S is a ring homomorphism that is injective as a function. This is equivalent to stating that the kernel of the homomorphism is the zero ideal, ker(p)={0}. In this case, R is isomorphic to the subring Im(p) of S, so we say that R is "embedded" into S. */
/* Injective, the map from the affine line A1 to the affine plane A2 given by (x) to (x, x^2). This map "embeds" the line as a parabola in the plane. The map is injective, and the image is a subscheme of the plane. This is a geometric embedding, where no two points on the line are "crushed" together in the plane: A morphism of schemes f:X→Y is an embedding if it is a closed immersion and its image is an affine subscheme. For affine schemes, this corresponds to a surjective ring homomorphism. A more general notion of injectivity is a monomorphism in the category of schemes, where a morphism f: X to Y is a monomorphism if for any two morphisms g,h: Z to X, f * g = f * h implies g = h the sections are the same. */
/* Injectives, inclusion of the boundary of a disk, S1, into the disk itself, D2, is a cofibration. If we have a map from the disk to some other space, and we have a homotopy on the boundary of the disk, we can extend this homotopy to the whole disk. The map is "injective" in a way that allows us to extend maps and homotopies. The boundary is "stuck" in the disk in a well-behaved way: A cofibration is a continuous map i:A to X that satisfies the homotopy extension property. This is a "dual" concept to a fibration and is a form of injective map in the category of topological spaces. A cofibration is an embedding that allows for "pushing homotopies forward." */
/* Injective, the map on the real line given by f(x)=2x. This is an injective map. The distance between two points doubles at each step. This "stretching" is a sign of injectivity in a dynamical system:  for a a dynamical system, an injective map has a positive Lyapunov exponent, which measures the rate of divergence of nearby trajectories. This is a way of saying that the map is "stretching" the space. */
/* Injective, a division ring is a ring where every non-zero element has a multiplicative inverse. A simple module over a division ring is just a vector space. A vector space is an injective module. The vector space is so "flexible" that any map from a subspace can be extended:  In the category of modules over a non-commutative ring, a simple module is a module that has no non-trivial submodules. A simple module is an injective object in a very special case, when the ring is a division ring. */
/* Injective, a finite field as a set of points. The Frobenius map "shuffles" the points. The injectivity means that no two points are mapped to the same point. This is a very strong property that is a key to understanding the structure of finite fields:  The Frobenius map on a finite field F_q​ is the map that sends an element x to x^p. This map is a permutation, so it is both injective and surjective. The injectivity is a key property of the Frobenius map. */
/* Injective, a circle drawn on the surface of a sphere. This is an injective map. We can extend a homotopy from the circle to the whole sphere. The circle is "stuck" in the sphere in a well-behaved way:  The inclusion of a lower-dimensional sphere into a higher-dimensional sphere is an injective map that is a cofibration. For example, the inclusion of S1 into S2 is an injective map that satisfies the homotopy extension property. */
/* Wreath product, imagine H as a group of "movers" and G as a group of "actions". The base group G^H is a collection of ∣H∣ copies of G, one for each element of H. The group H then acts by permuting these copies. For instance, the symmetric group S4​ can be viewed as the wreath product S2​ wreath S2​, which permutes pairs of points. The group S2​ acts on {1,2}, and a second S2​ acts on the set of two such pairs, {{1,2},{3,4}}:  The wreath product G wreath H of groups G and H is a semidirect product GH semidirect H, where GH is the group of functions from H to G, and H acts on GH by shifting the functions. */
/* Wreath product, necklace with |X| beads, where each bead can be in one of |G| states. The group H permutes the beads, and the group G can change the state of each bead. For example, if G = Z_2​ and H = Z)n​, a wreath product element can rotate the beads of the necklace and simultaneously flip some of them. This is a common model for studying Rubik's cubes:  For a group G and a set X with an action of a group H on X, the wreath product G wreath X​H is the group of permutations of the set G×X. Its elements are pairs (f,h) where f:X to G and h in H. */
/* Wreath product, representations of G wreath H as building blocks. The representations of the base group G^H are tensor products of representations of G. The action of H on G^H permutes these tensor factors. The representation of G wreath H is then built by inducing representations from subgroups, creating a rich and intricate structure of representations:  The representation theory of wreath products connects the representations of G wreath H to those of G and H. The irreducible representations of G wreath H can be constructed from the irreducible representations of its base and acting groups. */
/* Wreath product, two stacked layers of symmetries. The lower layer, K/F, has symmetries given by H. The upper layer, L/K, has symmetries given by G. The wreath product captures the combined symmetry of this tower, where the symmetries of the lower layer "permute" the symmetries of the upper layer:  The Galois group of a tower of field extensions, say L/K and K/F, can sometimes be expressed as a wreath product. If L/K is a normal extension and its Galois group Gal(L/K) is isomorphic to a group G, and K/F is a normal extension with Galois group Gal(K/F) isomorphic to H, and if the action of Gal(K/F) on the roots of a polynomial is transitive, then the Galois group of L/F is a wreath product of G and H. */
/* Wreath product, system of cellular automata on a circle. The group of global rotations of the circle is H. At each cell, there is a local state that can be changed by a group G. The wreath product G wreath H describes the symmetries of this system, where H shifts the cells and G acts locally on each cell:  The wreath product can be used to describe the symmetries of certain dynamical systems. For example, a system with two levels of hierarchy, where a set of local dynamics is governed by a global dynamics. */
/* Wreath product, n identical particles moving in a space. The group Sn​ permutes the particles. At each particle, there can be a local symmetry group G describing an internal state (e.g., spin). The wreath product combines the global permutation symmetry with the local internal symmetries:  The configuration space of a collection of points in a topological space can be modeled using the wreath product. For instance, the space of n points in a space X with some local dynamics can be described as a wreath product of the group of local symmetries with the symmetric group S_n​. */
/* Wreath product, homology groups as measuring the "holes" in a topological space. The wreath product is a way to "build" a new space by taking copies of one space and permuting them. The homology of this new space is then determined by the homology of the components. For example, the homology of a space that is a wreath product of two spheres, S2 wreath S1, would be related to the homology of S2 and S1:  The wreath product of groups can be used to construct interesting chain complexes and compute homology. The homology of G wreath H can be related to the homology of G and H using the Künneth formula and spectral sequences. */
/* Wreath product, counting the number of ways to color the vertices of a cube with 2 colors. The group of symmetries of the cube is a wreath product of the rotations of a face with the permutations of the faces. This structure is used to analyze the symmetries and count the number of distinct colorings:  In enumerative combinatorics, the wreath product is used to count the number of objects with certain symmetries. For example, the number of colorings of a graph where the colorings are invariant under the action of a group can be found using the orbit-stabilizer theorem and properties of wreath products. */
/* Wreath product, Lie algebras are the "infinitesimal" versions of Lie groups. The wreath product of Lie algebras captures the same hierarchical structure as the wreath product of groups, but at an infinitesimal level. This is useful for studying symmetries of continuous systems:  The wreath product of Lie algebras is defined by a semidirect product of Lie algebras. It is a fundamental construction in the study of infinite-dimensional Lie algebras. */
/* Wreath product, group cohomology measures the "extensions" of a group by a module. The wreath product is a way to "stack" extensions on top of each other, creating a complex structure. The spectral sequence is a tool to "unstack" this structure and compute the cohomology:  The group cohomology of a wreath product G wreath H can be computed using a spectral sequence that relates it to the cohomology of G and H. */
/* Wreath product, graph as a network of nodes and edges. The wreath product of two graphs, say G1​ and G2​, creates a new graph where each vertex is a "copy" of the graph G2​ at each vertex of G1​. This allows for a hierarchical network structure:  The wreath product of graphs is a construction that creates a new graph from two given graphs. The vertices of the new graph are pairs of vertices from the original graphs. */
