/* Ontology, reinvention:  example, groups, how did the original person reinvent it (permutation group of roots), what is the slickest modern reinvention of this (group as one object groupoid) */
/* Ontology, Bongard problem: find commonality of six images. Problem is to figure out what the problem is. Look at reality repeatedly, less directly. Lower description level, pattern pops out. Model of Science. */
/* Ontology, nebulosity: fluid character of meanings. Eternalism is denial of nebulosity. Corollary: eternal ordering principle. */
/* Ontology, lens control: lens distort to make ugly or beautiful. */
/* Ontology, ontological splitting: distinguish properties to rebuild it. Suitable generalities for suitable purposes. Negative thinking. */
/* Ontology, right definitions: mathematicians put work in making the right definitions or the right ontology. See history of mathematics. Find bad definitions and alternative ontologies. */
/* Ontology, NEDERA and Gendlin focusing: use NEDERA to get labels once you experience the ontology of the pain. In Gendlin focusing, this is felt understanding, or felt sense. Felt sense is physical, felt understanding is unconscious understanding of detail. */
/* Ontology, (IMPORTANT) set of all things tracked: set of all things tracked by you consciously or unconsciously. Goal: increase set by reading more, mostly consists of things you are not tracking consciously, only subconsciously and things you do not have words for. Building skill is learning what to track or ontology building. Teaching is setting up of experiences that let students track the proper ontology of a skill. */
/* Ontology, ontology building: as relation sense what main objects are, how they relate to each other, and make it actionable. Build it yourself. */
/* Ontology, avoid ontological cons: sidestepping issues in lack of understanding or failure to split, example 0.9999 = 1, lots of ontological gaslighting, explicit splitting needs to be tracked or knowledge to help track these subconscious issues helps. */
/* Ontology, remodelling: reconfiguration of individuation criteria, categories, properties, and relationships, advanced meta-rational activity. Ideally, we build up conceptual prerequisites before discussion. */
/* Ontology, three outcomes: (1) disappears when nothing in it, (2) stubbornly nebulous for formality since it is heuristically useful, third, (3) new formal proper definition. Spectrum also, focus on second since it is nearly useless due to imprecision. */
/* Ontology, against the correct answer: fails in math, fails in classifying planets, meta rationalities means all categories (or definitions) as inherently purpose laden. Therefore, what does this definition do, why is this definition is more important. Example, why Poincare define homology as relations with linear combinations. This denies the existence of a general theory of truths. */