/*Vibe coding, refactoring: vibe coding is very good at refactoring code.*/
/*Vibe coding, plain text: plain text in the directories and in the comments helps a lot with the context for the input.*/
/*Vibe coding, comments: in the age of vibe coding, never regretting having too many comments.*/
/*Google internal tools, open source: learn how to use tools externally see <a href="https://github.com/jhuangtw/xg2xg?tab=readme-ov-file">here.</a>*/
/*Facebook internal tools, open source: learn how to use tools externally see <a href="https://github.com/greko6/xfb2xfb?tab=readme-ov-file">here.</a>*/
/*Writing assembly by hand, Ultier: learn here <a href="https://gaultier.github.io/blog/x11_x64.html">at this link.</a>*/
/*Notes from a manager/CEO, calendar as other's calendar: your calendar becomes everyone else's calendar, every gap gets filled.*/
/*Notes from a manager, hardest conversations: they start with do you have a second?*/
/*Notes from a manager, you can no longer blame management: you can no longer blame management since you are not the maangement.*/
/*Notes from a manager, can only talk to cofounder: there is no one to complaint o except your cofounder.*/
/*Notes from a manager, 996: you have to 996, no one else.*/
/*Abstraction, no leaking: a design flaw where an abstraction that is meant to simplify fails to completely hide complexity. Abstractions will need orthogonality.*/
/*Abstraction, reduction in dependencies: dependencies lead to more leaky abstraction.*/
/*Abstraction, few ideas and cleverly combine: few ideas to cleverly combine.*/
/*Abstraction, short code to read and hack on, you need to write code that is short and easy to hack on.*/
/*Abstraction, well tested and easy to reason about: code that is well tested and easy to reason about is a good abstraction.*/
/*Anomaly detection model, underrated: (1) local outlier factor; (2) isolation forest; (3) robust random cut forest.*/
/*Personality due to upbringing: a large chunk of your behaviors are not natural for you, worked very well for your parents, or cultivated to deal with dysfunction in your upbringing, discovering who you are and what you actually value.*/
/*Stupidity, priorities of stupid people: average people seems really stupid since their priorities are different.*/
/*Musk on 10 year plans: how can I accomplish by 10 year plans in 6 months, you will probably fail but you will be far ahead of the person who simply accepted that it will take 10 years.*/
/*Blaming yourself, and others: belief that other people would be happier if they were left alone.*/
/*Biology as technology: technology to build humans is. Only now are we close with our stack. Human DNA is 6 GB. That’s a DVD. In 1970, you couldn’t store 6GB. Today, I can copy it in seconds on my M1 SSD. That’s actually faster than nature. Biology is non-toxic. Biology is efficient. Biology is beautiful. Biology is technology. Biology is not centralized. Biology is not alien. Biology is not rectangular. Biology is not industrial.*/
/*Raising children and AI: A child raised wrong will grow up wrong. And how are we doing right now as a society raising our children, when half the kids are born out of wedlock, up from 5% 70 years ago. Who thinks we can raise an AI?*/
/*Yudkowsky’s minimum IQ: "The minimum IQ required to destroy the world drops by one point every 18 months."*/
/*Wozniak’s Test: machine is required to enter an average American home and figure out how to make coffee. Harder than self driving cars.*/
/*Keller’s three fundamental computing paradigms: CPU: add, multiply, load, store, compare, branch (nothing can be known about anything), GPU: add, multiply, load, store (when things happen is known, but the addresses aren’t) DSP: add, multiply (everything is known except the data)*/
/*Power costs and data locality: the key is data locality. Having to move data costs power. Instruction set and compiler, and while it’s complex, that complexity is only up front to compile the model. After that, it’s way simpler (aka, less power and less issues) at runtime than CUDA and PyTorch. The only questionable choice is why not take this further? The interconnects between the chips cost power.*/
/*Problem of representative democracy, as a vicarious desire: Representative democracy is to get you to vicariously identify with this desire. And this gets a larger group of people, perhaps the most vocal in supporting a candidate, but still nothing near the majority. This is the most evil trick the regime uses. You no longer believe that things will get better, but you are forced to be involved because you fear things will get worse. You are tricked into supporting state power because you fear other state power. Sometimes foreign, sometimes domestic.*/
/*Process in government, and the bridge: goal is not to build the bridge, the goal is to make sure the process is followed to build the bridge. I didn’t really understand this until recently, but this is also how most large organizations work.*/
/*Jim Keller on Chaos: by continually creating chaos, process is incapable of forming, and everyone is forced to work only toward goal.*/
/*Lying to yourself: "I would rather lose than sell out. If you lie to the world you lie to yourself and one day you can no longer tell what’s true or not. I would live under a bridge and eat out of dumpsters if I got to know the truth."*/
/*Landauer’s limit, evolution brutal optimisation: makes sense, if there’s one thing that evolution brutally optimized for it is efficiency.*/
/*Sutton’s quotes on arbitrary scaling or the Bitter Lesson: One thing that should be learned from the bitter lesson is the great power of general purpose methods, of methods that continue to scale with increased computation even as the available computation becomes very great. The two methods that seem to scale arbitrarily in this way are search and learning.*/
/*Radio building and initial conditions: either look at initial conditions of the Italian man or reverse engineering and taking apart each piece.*/
/*Paul Christiano on AI and animal breeding: creation of AI will look a lot less like a visit from an alien produced by natural selection (where you are most certainly dead), and a lot more like animal breeding. */
/*The 100 marshmallow test: instead of a single person, imagine 100 people in a room. One marshmallow is placed on a table. If everyone can leave it alone for 15 minutes, everyone gets 2 marshmallows. But if just one person eats it, everyone gets nothing (except for the guy who ate a marshmallow, he got that marshmallow).*/
/*Self reflections on prediction: Am I the same way? I try extremely hard to constantly test myself, if my predictions are wrong it’s clear I don’t understand. If I can’t build it I don’t understand. I’ll frequently read comments saying I don’t understand, but when I engage with these people they can’t explain what my world model gets wrong. A different meta world model? Or are they just idiots? To anyone who wants to supersede rationality, you better understand how to steelman every rationality argument.*/
/*Random sprinting and engaging with life: I was told recently I’m not engaged in my life, and it’s pretty true. Until I see a solution to this problem, even a sketch of a solution, what’s the point? Why sprint if you aren’t sure where you are going?*/
/*Value profit convexity: The old days of the Internet were this goldmine. The Internet delivered huge value but no profit, and that’s why it was good. Suddenly we had all these new powers.*/
/*Criticism of capital deployment: Communism is dumb cause it goes to the poor (who routinely demonstrate that they poorly deploy capital). Capitalism is dumb cause it goes to the rent-seekers (who frequently deploy capital to increase or maintain their moat). Acceleration is the way.*/
/*Chris McCandless, and the ideal of explorers: explorer, but being born in 1968 meant that the world was already all explored. His clever solution, throw away the map. But that didn’t make him an explorer, it made him an idiot who died 5 miles from a bridge that would have saved his life.*/
/*Reading papers, Denis Nardin: do not try to read in order, (1) statements at least in their opinion are the main results, try to understand the statements, vague idea of definitions; (2) go backwards, what is the MAIN STEP/DEFINITIONS to try to learn and understand the statement of this STEP or TWO STEP or two cases what they consist of and how they are different, and then go different; (3) stop when you run out of paper or interest in things; (4) do not do the main proof.*/